project:
  type: website
  output-dir: docs


resources:
  - Baba.png
  - ruby.csv
  - P38.json


website:
  title: "介護福祉士過去問練習"
  # 大学名などをフッター（ページ最下部）に入れる場合
  page-footer: 
    left: "©2026 新潟医療福祉大学 社会福祉学科"
    right: "AI 准教授 馬場 監修"
  
  navbar:
    background: "#f8dfe7" # ★ここをピンク（Zoom案内と同じ色）に
    collapse: true
    left:
      - href: index.qmd
        text: はじめに
      - text: "介護福祉士過去問"
        menu:
          - href: P38_G.qmd
            text: "第38回（2025年度）"
          - href: P38_G_NUHW.qmd
            text: "2026年度 NUHW"
      - text: "Exam with Ruby"
        menu:
          - href: P38_G_Ruby.qmd
            text: "38"

format:
  html:
    self-contained: false
    theme: 
      - cosmo
      - custom.scss
    css: quiz_multi.css
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/dompurify@3.0.6/dist/purify.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"></script>
          <script src="ruby.js"></script>
          <script src="quiz_multi.js"></script>
    include-after-body: header.html

