---
title: "P36"
output: html_document
---

第36回（令和5年度）介護福祉士国家試験　筆記試験午前の問題
＜領域：人間と社会＞

## 人間の尊厳と自立

問題1  Ａさん（76歳、女性、要支援1）は、一人暮らしである。週1回介護予防通所リハビリテーションを利用しながら、近所の友人たちとの麻雀｛まーじゃん｝を楽しみに生活している。最近、膝に痛みを感じ、変形性膝関節症（knee osteoarthritis）と診断された。同時期に友人が入院し、楽しみにしていた麻雀｛まーじゃん｝ができなくなった。Ａさんは徐々に今後の生活に不安を感じるようになった。ある日、「自宅で暮らし続けたいけど、心配なの…」と介護福祉職に話した。
Ａさんに対する介護福祉職の対応として、最も適切なものを1つ選びなさい。

    1  要介護認定の申請を勧める。
    2  友人のお見舞いを勧める。
    3  膝の精密検査を勧める。
    4  別の趣味活動の希望を聞く。
    5  生活に対する思いを聞く。

問題2  次の記述のうち、介護を必要とする人の自立についての考え方として、最も適切なものを1つ選びなさい。

    1  自立は、他者の支援を受けないことである。
    2  精神的自立は、生活の目標をもち、自らが主体となって物事を進めていくことである。
    3  社会的自立は、社会的な役割から離れて自由になることである。
    4  身体的自立は、介護者の身体的負担を軽減することである。
    5  経済的自立は、経済活動や社会活動に参加せずに、生活を営むことである。

## 人間関係とコミュニケーション

問題3  Ｕ介護老人福祉施設では、利用者の介護計画を担当の介護福祉職が作成している。このため、利用者の個別の介護目標を、介護福祉職のチーム全員で共有することが課題になっている。
この課題を解決するための取り組みとして、最も適切なものを1つ選びなさい。

    1  管理職がチーム全体に注意喚起して、集団規範を形成する。
    2  現場経験の長い介護福祉職の意見を優先して、同調行動を促す。
    3  チームメンバーの懇談会を実施して、内集団バイアスを強化する。
    4  チームメンバー間の集団圧力を利用して、多数派の意見に統一する。
    5  担当以外のチームメンバーもカンファレンス（conference）に参加して、集団凝集性を高める。

問題4  Ｂさん（90歳、女性、要介護3）は、介護老人福祉施設に入所している。入浴日に、担当の介護福祉職が居室を訪問し、「Ｂさん、今日はお風呂の日です。時間は午後3時からです」と伝えた。しかし、Ｂさんは言っていることがわからなかったようで、「はい、何ですか」と困った様子で言った。
このときの、介護福祉職の準言語を活用した対応として、最も適切なものを1つ選びなさい。

    1  強い口調で伝えた。
    2  抑揚をつけずに伝えた。
    3  大きな声でゆっくり伝えた。
    4  急かすように伝えた。
    5  早口で伝えた。

問題5  Ｖ介護老人福祉施設では、感染症が流行したために、緊急的な介護体制で事業を継続することになった。さらに労務管理を担当する職員からは、介護福祉職の精神的健康を守ることを目的とした組織的なマネジメントに取り組む必要性について提案があった。
次の記述のうち、このマネジメントに該当するものとして、最も適切なものを1つ選びなさい。

    1  感染防止対策を強化する。
    2  多職種チームでの連携を強化する。
    3  利用者のストレスをコントロールする。
    4  介護福祉職の燃え尽き症候群（バーンアウト（burnout））を防止する。
    5  利用者家族の面会方法を見直す。

問題6  次のうち、介護老人福祉施設における全体の指揮命令系統を把握するために必要なものとして、最も適切なものを1つ選びなさい。

    1  組織図
    2  勤務表
    3  経営理念
    4  施設の歴史
    5  資格保有者数

## 社会の理解

問題7  次のうち、セルフヘルプグループ（self-help group）の活動に該当するものとして、最も適切なものを1つ選びなさい。

    1  断酒会
    2  施設の社会貢献活動
    3  子ども食堂の運営
    4  傾聴ボランティア
    5  地域の町内会

問題8  特定非営利活動法人（ＮＰＯ法人）に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  社会福祉法に基づいて設置される。
    2  市町村が認証する。
    3  保健、医療又は福祉の増進を図る活動が最も多い。
    4  収益活動は禁じられている。
    5  宗教活動を主たる目的とする団体もある。

問題9  地域福祉において、19世紀後半に始まった、貧困地域に住み込んで実態調査を行いながら住民への教育や生活上の援助を行ったものとして、最も適切なものを1つ選びなさい。

    1  世界保健機関（ＷＨＯ）
    2  福祉事務所
    3  地域包括支援センター
    4  生活協同組合
    5  セツルメント

問題10  社会福祉基礎構造改革に関する次の記述のうち、適切なものを1つ選びなさい。

    1  社会福祉法が社会福祉事業法に改正された。
    2  利用契約制度から措置制度に変更された。
    3  サービス提供事業者は、社会福祉法人に限定された。
    4  障害福祉分野での制度改正は見送られた。
    5  判断能力が不十分な者に対する地域福祉権利擁護事業が創設された。

問題11  Ｃさん（77歳、男性）は、60歳で公務員を定年退職し、年金生活をしている。持病や障害はなく、退職後も趣味のゴルフを楽しみながら健康に過ごしている。ある日、Ｃさんはゴルフ中にけがをして医療機関を受診した。 このとき、Ｃさんに適用される公的医療制度として、正しいものを1つ選びなさい。

    1  国民健康保険
    2  後期高齢者医療制度
    3  共済組合保険
    4  育成医療
    5  更生医療

問題12  次のうち、介護保険法に基づき、都道府県・指定都市・中核市が指定（許可）、監督を行うサービスとして、正しいものを1つ選びなさい。

    1  地域密着型介護サービス
    2  居宅介護支援
    3  施設サービス
    4  夜間対応型訪問介護
    5  介護予防支援

問題13  「障害者差別解消法」に関する次の記述のうち、適切なものを1つ選びなさい。

    1  法の対象者は、身体障害者手帳を交付された者に限定されている。
    2  合理的配慮は、実施するときの負担の大小に関係なく提供する。
    3  個人による差別行為への罰則規定がある。
    4  雇用分野での、障害を理由とした使用者による虐待の禁止が目的である。
    5  障害者基本法の基本的な理念を具体的に実施するために制定された。

    （注）  「障害者差別解消法」とは、「障害を理由とする差別の解消の推進に関する法律」のことである。

問題14  「障害者総合支援法」に規定された移動に関する支援の説明として、最も適切なものを1つ選びなさい。

    1  移動支援については、介護給付費が支給される。
    2  行動援護は、周囲の状況把握ができない視覚障害者が利用する。
    3  同行援護は、危険を回避できない知的障害者が利用する。
    4  重度訪問介護は、重度障害者の外出支援も行う。
    5  共同生活援助（グループホーム）は、地域で生活する障害者の外出支援を行う。

    （注）  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。

問題15  Ｄさん（80歳、男性、要介護2）は、認知症（dementia）がある。訪問介護（ホームヘルプサービス）を利用しながら一人暮らしをしている。
ある日、訪問介護員（ホームヘルパー）がＤさんの自宅を訪問すると、近所に住むＤさんの長女から、「父が、高額な投資信託の電話勧誘を受けて、契約しようかどうか悩んでいるようで心配だ」と相談された。
訪問介護員（ホームヘルパー）が長女に助言する相談先として、最も適切なものを1つ選びなさい。

    1  公正取引委員会
    2  都道府県障害者権利擁護センター
    3  運営適正化委員会
    4  消費生活センター
    5  市町村保健センター

問題16  災害時の福祉避難所に関する次の記述のうち、適切なものを1つ選びなさい。

    1  介護老人福祉施設の入所者は、原則として福祉避難所の対象外である。
    2  介護保険法に基づいて指定される避難所である。
    3  医療的ケアを必要とする者は対象にならない。
    4  訪問介護員（ホームヘルパー）が、災害対策基本法に基づいて派遣される。
    5  同行援護のヘルパーが、災害救助法に基づいて派遣される。

問題17  「感染症法」に基づいて、結核（tuberculosis）を発症した在宅の高齢者に、医療費の公費負担の申請業務や家庭訪問指導などを行う機関として、適切なものを1つ選びなさい。

    1  基幹相談支援センター
    2  地域活動支援センター
    3  保健所
    4  老人福祉センター
    5  医療保護施設

    （注）  「感染症法」とは、「感染症の予防及び感染症の患者に対する医療に関する法律」のことである。 

問題18  Ｅさん（55歳、女性、障害の有無は不明）は、ひきこもりの状態にあり、就労していない。父親の年金で父親とアパートで暮らしていたが、父親が亡くなり、一人暮らしになった。遠方に住む弟は、姉が家賃を滞納していて、生活に困っているようだと、家主から連絡を受けた。
心配した弟が相談する機関として、最も適切なものを1つ選びなさい。

    1  地域包括支援センター
    2  福祉事務所
    3  精神保健福祉センター
    4  公共職業安定所（ハローワーク）
    5  年金事務所

＜領域：こころとからだのしくみ＞

## こころとからだのしくみ

問題19  次のうち、マズロー（Maslow, A.H.）の欲求階層説で成長欲求に該当するものとして、正しいものを1つ選びなさい。

    1  承認欲求
    2  安全欲求
    3  自己実現欲求
    4  生理的欲求
    5  所属・愛情欲求

問題20  次のうち、交感神経の作用に該当するものとして、正しいものを1つ選びなさい。

    1  血管収縮
    2  心拍数減少
    3  気道収縮
    4  消化促進
    5  瞳孔収縮

問題21  Ｆさん（82歳、女性）は、健康診断で骨粗鬆症｛こつそしょうしょう｝（osteoporosis）と診断され、内服治療が開始された。杖歩行｛つえほこう｝で時々ふらつくが、ゆっくりと自立歩行することができる。昼間は自室にこもり、ベッドで横になっていることが多い。リハビリテーションとして週3日歩行訓練を行い、食事は普通食を毎食8割以上摂取している。
Ｆさんの骨粗鬆症｛こつそしょうしょう｝（osteoporosis）の進行を予防するための支援として、最も適切なものを1つ選びなさい。

    1  リハビリテーションを週1日に変更する。
    2  繊維質の多い食事を勧める。
    3  日光浴を日課に取り入れる。
    4  車いすでの移動に変更する。
    5  ビタミンＡ（vitamin A）の摂取を勧める。

問題22  中耳にある耳小骨として、正しいものを1つ選びなさい。

    1  ツチ骨
    2  蝶形骨｛ちょうけいこつ｝
    3  前頭骨
    4  頬骨｛きょうこつ｝
    5  上顎骨

問題23  成人の爪に関する次の記述のうち、正しいものを1つ選びなさい。

    1  主成分はタンパク質である。
    2  1日に1mm程度伸びる。
    3  爪の外表面には爪床がある。
    4  正常な爪は全体が白色である。
    5  爪半月は角質化が進んでいる。

問題24  食物が入り誤嚥｛ごえん｝が生じる部位として、適切なものを1つ選びなさい。

    1  扁桃｛へんとう｝
    2  食道
    3  耳管
    4  気管
    5  咽頭

問題25  Ｇさん（79歳、男性）は、介護老人保健施設に入所している。Ｇさんは普段から食べ物をかきこむように食べる様子がみられ、最近はむせることが多くなった。義歯は使用していない。食事は普通食を摂取している。ある日の昼食時、唐揚げを口の中に入れたあと、喉をつかむようなしぐさをし、苦しそうな表情になった。
Ｇさんに起きていることとして、最も適切なものを1つ選びなさい。

    1  心筋梗塞（myocardial infarction）
    2  蕁麻疹｛じんましん｝（urticaria）
    3  誤嚥性肺炎｛ごえんせいはいえん｝（aspiration pneumonia）
    4  食中毒（foodborne disease）
    5  窒息（choking）

問題26  Ｈさん（60歳、男性）は、身長170cm、体重120kgである。Ｈさんは浴槽で入浴しているときに毎回、「お風呂につかると、からだが軽く感じて楽になります」と話す。胸が苦しいなど、ほかの訴えはない。
Ｈさんが話している内容に関連する入浴の作用として、最も適切なものを1つ選びなさい。

    1  静水圧作用
    2  温熱作用
    3  清潔作用
    4  浮力作用
    5  代謝作用

問題27  男性に比べて女性に尿路感染症（urinary tract infection）が起こりやすい要因として、最も適切なものを1つ選びなさい。

    1  子宮の圧迫がある。
    2  尿道が短く直線的である。
    3  腹部の筋力が弱い。
    4  女性ホルモンの作用がある。
    5  尿道括約筋が弛緩｛しかん｝している。

問題28  次のうち、眠りが浅くなる原因として、最も適切なものを1つ選びなさい。

    1  抗不安薬
    2  就寝前の飲酒
    3  抗アレルギー薬
    4  抗うつ薬
    5  足浴

問題29  概日リズム睡眠障害（circadian rhythm sleep disorder）に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  早朝に目が覚める。
    2  睡眠中に下肢が勝手にピクピクと動いてしまう。
    3  睡眠中に呼吸が止まる。
    4  睡眠中に突然大声を出したり身体を動かしたりする。
    5  夕方に強い眠気を感じて就寝し、深夜に覚醒してしまう。

問題30  鎮痛薬としてモルヒネを使用している利用者に、医療職と連携した介護を実践するときに留意すべき観察点として、最も適切なものを1つ選びなさい。

    1  不眠
    2  下痢
    3  脈拍
    4  呼吸
    5  体温

## 発達と老化の理解

問題31  スキャモン（Scammon, R.E.）の発達曲線に関する次の記述のうち、適切なものを1つ選びなさい。

    1  神経系の組織は、4歳ごろから急速に発達する。
    2  筋骨格系の組織は、4歳ごろから急速に発達する。
    3  生殖器系の組織は、12歳ごろから急速に発達する。
    4  循環器系の組織は、20歳ごろから急速に発達する。
    5  リンパ系の組織は、20歳ごろから急速に発達する。

問題32  幼稚園児のＪさん（6歳、男性）には、広汎性発達障害（pervasive developmental disorder）がある。砂場で砂だんごを作り、きれいに並べることが好きで、毎日、一人で砂だんごを作り続けている。
ある日、園児が帰宅した後に、担任が台風に備えて砂場に青いシートをかけておいた。翌朝、登園したＪさんが、いつものように砂場に行くと、青いシートがかかっていた。Ｊさんはパニックになり、その場で泣き続け、なかなか落ち着くことができなかった。
担任は、Ｊさんにどのように対応すればよかったのか、最も適切なものを1つ選びなさい。

    1  前日に、「あしたは、台風が来るよ」と伝える。
    2  前日に、「あしたは、台風が来るので砂場は使えないよ」と伝える。
    3  前日に、「あしたは、おだんご屋さんは閉店です」と伝える。
    4  その場で、「今日は、砂場は使えないよ」と伝える。
    5  その場で、「今日は、おだんご屋さんは閉店です」と伝える。

問題33  生理的老化に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  環境によって起こる現象である。
    2  訓練によって回復できる現象である。
    3  個体の生命活動に有利にはたらく現象である。
    4  人間固有の現象である。
    5  遺伝的にプログラムされた現象である。

問題34  エイジズム（ageism）に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  高齢を理由にして、偏見をもったり差別したりすることである。
    2  高齢になっても生産的な活動を行うことである。
    3  高齢になることを嫌悪する心理のことである。
    4  加齢に抵抗して、健康的に生きようとすることである。
    5  加齢を受容して、活動的に生きようとすることである。

問題35  Ｋさん（80歳、男性）は、40歳ごろから職場の健康診査で高血圧と高コレステロール血症（hypercholesterolemia）を指摘されていた。最近、階段を上るときに胸の痛みを感じていたが、しばらく休むと軽快していた。喉の違和感や嚥下痛｛えんげつう｝はない。今朝、朝食後から冷や汗を伴う激しい胸痛が起こり、30分しても軽快しないので、救急車を呼んだ。
Ｋさんに考えられる状況として、最も適切なものを1つ選びなさい。

    1  喘息｛ぜんそく｝（bronchial asthma）
    2  肺炎（pneumonia）
    3  脳梗塞（cerebral infarction）
    4  心筋梗塞（myocardial infarction）
    5  逆流性食道炎（reflux esophagitis）

問題36  次のうち、健康寿命の説明として、適切なものを1つ選びなさい。

    1  0歳児の平均余命
    2  65歳時の平均余命
    3  65歳時の平均余命から介護期間を差し引いたもの
    4  介護状態に至らずに死亡する人の平均寿命
    5  健康上の問題で日常生活が制限されることなく生活できる期間

問題37  次のうち、前立腺肥大症（prostatic hypertrophy）に関する記述として、最も適切なものを1つ選びなさい。

    1  抗利尿ホルモンが関与している。
    2  症状が進むと無尿になる。
    3  初期には頻尿が出現する。
    4  進行すると透析の対象になる。
    5  骨盤底筋訓練で回復が期待できる。

問題38  次のうち、高齢期に多い筋骨格系の疾患に関する記述として、適切なものを1つ選びなさい。

    1  骨粗鬆症｛こつそしょうしょう｝（osteoporosis）は男性に多い。
    2  変形性膝関節症（knee osteoarthritis）ではＸ脚に変形する。
    3  関節リウマチ（rheumatoid arthritis）は軟骨の老化によって起こる。
    4  腰部脊柱管狭窄症｛ようぶせきちゅうかんきょうさくしょう｝（lumbar spinal canal stenosis）では下肢のしびれがみられる。
    5  サルコペニア（sarcopenia）は骨量の低下が特徴である。

## 認知症の理解

問題39  高齢者の自動車運転免許に関する次の記述のうち、正しいものを1つ選びなさい。

    1  75歳から免許更新時の認知機能検査が義務づけられている。
    2  80歳から免許更新時の運転技能検査が義務づけられている。
    3  軽度認知障害（mild cognitive impairment）と診断された人は運転免許取消しになる。
    4  認知症（dementia）の人はサポートカー限定免許であれば運転が可能である。
    5  認知症（dementia）による運転免許取消しの後、運転経歴証明書が交付される。

    （注）  「サポートカー限定免許」とは、道路交通法第91条の2の規定に基づく条件が付された免許のことである。

問題40  認知症（dementia）の行動・心理症状（ＢＰＳＤ）であるアパシー（apathy）に関する次の記述のうち、適切なものを1つ選びなさい。

    1  感情の起伏がみられない。
    2  将来に希望がもてない。
    3  気持ちが落ち込む。
    4  理想どおりにいかず悩む。
    5  自分を責める。

問題41  認知症（dementia）の人にみられる、せん妄に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  ゆっくりと発症する。
    2  意識は清明である。
    3  注意機能は保たれる。
    4  体調の変化が誘因になる。
    5  日中に多くみられる。

問題42  レビー小体型認知症（dementia with Lewy bodies）にみられる歩行障害として、最も適切なものを1つ選びなさい。

    1  しばらく歩くと足に痛みを感じて、休みながら歩く。
    2  最初の一歩が踏み出しにくく、小刻みに歩く。
    3  動きがぎこちなく、酔っぱらったように歩く。
    4  下肢は伸展し、つま先を引きずるように歩く。
    5  歩くごとに骨盤が傾き、腰を左右に振って歩く。

問題43  次の記述のうち、若年性認知症（dementia with early onset）の特徴として、最も適切なものを1つ選びなさい。

    1  高齢の認知症（dementia）に比べて、症状の進行速度は緩やかなことが多い。
    2  男性よりも女性の発症者が多い。
    3  50歳代よりも30歳代の有病率が高い。
    4  特定健康診査で発見されることが多い。
    5  高齢の認知症（dementia）に比べて、就労支援が必要になることが多い。

問題44  Ｌさん（78歳、女性、要介護1）は、3年前にアルツハイマー型認知症（dementia of the Alzheimer’s type）と診断された。訪問介護（ホームヘルプサービス）を利用し、夫の介護を受けながら二人で暮らしている。ある日、訪問介護員（ホームヘルパー）が訪問すると夫から、「用事で外出しようとすると『外で女性に会っている』と言って興奮することが増えて困っている」と相談を受けた。 Ｌさんの症状に該当するものとして、最も適切なものを1つ選びなさい。

    1  誤認
    2  観念失行
    3  嫉妬妄想
    4  視覚失認
    5  幻視

問題45  認知機能障害による生活への影響に関する記述として、最も適切なものを1つ選びなさい。

    1  遂行機能障害により、自宅がわからない。
    2  記憶障害により、出された食事を食べない。
    3  相貌失認により、目の前の家族がわからない。
    4  視空間認知障害により、今日の日付がわからない。
    5  病識低下により、うつ状態になりやすい。

問題46  バリデーション（validation）に基づく、認知症（dementia）の人の動きや感情に合わせるコミュニケーション技法として、正しいものを1つ選びなさい。

    1  センタリング（centering）
    2  リフレージング（rephrasing）
    3  レミニシング（reminiscing）
    4  ミラーリング（mirroring）
    5  カリブレーション（calibration）

問題47  Ｍさん（80歳、女性、要介護1）は、アルツハイマー型認知症（dementia of the Alzheimer’s type）であり、3日前に認知症対応型共同生活介護（認知症高齢者グループホーム）に入居した。主治医から向精神薬が処方されている。居室では穏やかに過ごしていた。夕食後、表情が険しくなり、「こんなところにはいられません。私は家に帰ります」と大声を上げ、ほかの利用者にも、「あなたも一緒に帰りましょう」と声をかけて皆が落ち着かなくなることがあった。 Ｍさんの介護を検討するときに優先することとして、最も適切なものを1つ選びなさい。

    1  Ｍさんが訴えている内容
    2  Ｍさんの日中の過ごし方
    3  ほかの利用者が落ち着かなくなったこと
    4  対応に困ったこと
    5  薬が効かなかったこと

問題48  Ａさん（80歳、男性、要介護1）は、認知症（dementia）で、妻の介護を受けながら二人で暮らしている。「夫は昼夜逆転がある。在宅介護を続けたいが、私が体調を崩し数日間の入院が必要になった」と言う妻に提案する、Ａさんへの介護サービスとして、最も適切なものを1つ選びなさい。

    1  認知症対応型通所介護（認知症対応型デイサービス）
    2  短期入所生活介護（ショートステイ）
    3  認知症対応型共同生活介護（認知症高齢者グループホーム）
    4  特定施設入居者生活介護
    5  介護老人福祉施設

## 障害の理解

問題49  次のうち、ノーマライゼーション（normalization）の原理を盛り込んだ法律（いわゆる「1959年法」）を制定した最初の国として、正しいものを1つ選びなさい。

    1  デンマーク
    2  イギリス
    3  アメリカ
    4  スウェーデン
    5  ノルウェー

問題50  法定後見制度において、成年後見人等を選任する機関等として、正しいものを1つ選びなさい。

    1  法務局
    2  家庭裁判所
    3  都道府県知事
    4  市町村長
    5  福祉事務所

問題51  次の記述のうち、障害を受容した心理的段階にみられる言動として、最も適切なものを1つ選びなさい。

    1  障害があるという自覚がない。
    2  周囲に不満をぶつける。
    3  自分が悪いと悲観する。
    4  価値観が転換し始める。
    5  できることに目を向けて行動する。

問題52  統合失調症（schizophrenia）の特徴的な症状として、最も適切なものを1つ選びなさい。

    1  振戦せん妄
    2  妄想
    3  強迫性障害
    4  抑うつ気分
    5  健忘

問題53  Ｂさん（60歳、男性）は、一人暮らしをしている。糖尿病性網膜症（diabetic retinopathy）による視覚障害（身体障害者手帳1級）があり、末梢神経障害｛まっしょうしんけいしょうがい｝の症状がでている。Ｂさんの日常生活において、介護福祉職が留意すべき点として、最も適切なものを1つ選びなさい。

    1  水晶体の白濁
    2  口腔粘膜｛こうくうねんまく｝や外陰部の潰瘍
    3  振戦や筋固縮
    4  足先の傷や壊疽｛えそ｝などの病変
    5  感音性の難聴

問題54  Ｃさん（55歳、男性）は、5年前に筋萎縮性側索硬化症（amyotrophic lateral sclerosis：ＡＬＳ）と診断された。現在は症状が進行して、日常生活動作に介護が必要で、自宅では電動車いすと特殊寝台を使用している。
次の記述のうち、Ｃさんの現在の状態として、最も適切なものを1つ選びなさい。
    1  誤嚥｛ごえん｝せずに食事することが可能である。
    2  明瞭に話すことができる。
    3  身体の痛みがわかる。
    4  自力で痰｛たん｝を排出できる。
    5  箸を上手に使える。

問題55  Ｄさん（36歳、女性、療育手帳所持）は、一人暮らしをしながら地域の作業所に通っている。身の回りのことはほとんど自分でできるが、お金の計算、特に計画的にお金を使うのが苦手だった。そこで、社会福祉協議会の生活支援員と一緒に銀行へ行って、1週間ごとにお金をおろして生活するようになった。小遣い帳に記録をするようにアドバイスを受けて、お金を計画的に使うことができるようになった。
次のうち、Ｄさんが活用した支援を実施する事業として、最も適切なものを1つ選びなさい。

    1  障害者相談支援事業
    2  自立生活援助事業
    3  日常生活自立支援事業
    4  成年後見制度利用支援事業
    5  日常生活用具給付等事業

問題56  次のうち、障害の特性に応じた休憩時間の調整など、柔軟に対応することで障害者の権利を確保する考え方を示すものとして、最も適切なものを1つ選びなさい。

    1  全人間的復権
    2  合理的配慮
    3  自立生活運動
    4  意思決定支援
    5  共同生活援助

問題57  「障害者総合支援法」において、障害福祉サービスを利用する人の意向のもとにサービス等利用計画案を作成する事業所に置かなければならない専門職として、最も適切なものを1つ選びなさい。

    1  介護支援専門員（ケアマネジャー）
    2  社会福祉士
    3  介護福祉士
    4  民生委員
    5  相談支援専門員

    （注）  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。

問題58  家族の介護力をアセスメントするときの視点に関する記述として、最も適切なものを1つ選びなさい。

    1  障害者個人のニーズを重視する。
    2  家族のニーズを重視する。
    3  家族構成員の主観の共通部分を重視する。
    4  家族を構成する個人と家族全体の生活を見る。
    5  支援者の視点や価値観を基準にする。

＜領域：医療的ケア＞

## 医療的ケア

問題59  次の記述のうち、喀痰吸引等｛かくたんきゅういんとう｝を実施する訪問介護事業所として登録するときに、事業所が行うべき事項として、正しいものを1つ選びなさい。

    1  登録研修機関になる。
    2  医師が設置する安全委員会に参加する。
    3  喀痰吸引等計画書｛かくたんきゅういんとうけいかくしょ｝の作成を看護師に依頼する。
    4  介護支援専門員（ケアマネジャー）の文書による指示を受ける。
    5  医療関係者との連携体制を確保する。

問題60  次のうち、呼吸器官の部位の説明に関する記述として、正しいものを1つ選びなさい。

    1  鼻腔｛びくう｝は、上葉・中葉・下葉に分かれている。
    2  咽頭は、左右に分岐している。
    3  喉頭は、食べ物の通り道である。
    4  気管は、空気の通り道である。
    5  肺は、腹腔内｛ふくくうない｝にある。

問題61  次のうち、痰｛たん｝の吸引の準備に関する記述として、最も適切なものを1つ選びなさい。

    1  吸引器は、陰圧になることを確認する。
    2  吸引びんは、滅菌したものを用意する。
    3  吸引チューブのサイズは、痰｛たん｝の量に応じたものにする。
    4  洗浄水は、決められた消毒薬を入れておく。
    5  清浄綿は、次亜塩素酸ナトリウムに浸しておく。

問題62  次のうち、経管栄養で起こるトラブルに関する記述として、最も適切なものを1つ選びなさい。

    1  チューブの誤挿入は、下痢を起こす可能性がある。
    2  注入速度が速いときは、嘔吐｛おうと｝を起こす可能性がある。
    3  注入物の温度の調整不良は、脱水を起こす可能性がある。
    4  注入物の濃度の間違いは、感染を起こす可能性がある。
    5  注入中の姿勢の不良は、便秘を起こす可能性がある。

問題63  Ｅさん（75歳、女性）は、介護老人福祉施設に入所している。脳梗塞（cerebral infarction）の後遺症があり、介護福祉士が胃ろうによる経管栄養を行っている。
ある日、半座位で栄養剤の注入を開始し、半分程度を順調に注入したところで、体調に変わりがないかを聞くと、「少しお腹が張ってきたような気がする」とＥさんは答えた。意識レベルや顔色に変化はなく、腹痛や嘔気｛おうき｝はない。
次のうち、介護福祉士が看護職員に相談する前に行う対応として、最も適切なものを1つ選びなさい。

    1  嘔吐｛おうと｝していないので、そのまま様子をみる。
    2  仰臥位｛ぎょうがい｝（背臥位｛はいがい｝）にする。
    3  腹部が圧迫されていないかを確認する。
    4  注入速度を速める。
    5  栄養剤の注入を終了する。


＜領域：介護＞

## 介護の基本

問題64  介護を取り巻く状況に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  ダブルケアとは、夫婦が助け合って子育てをすることである。
    2  要介護・要支援の認定者数は、介護保険制度の導入時から年々減少している。
    3  家族介護を支えていた家制度は、地域包括ケアシステムによって廃止された。
    4  要介護・要支援の認定者のいる三世代世帯の構成割合は、介護保険制度の導入時から年々増加している。
    5  家族が担っていた介護の役割は、家族機能の低下によって社会で代替する必要が生じた。

問題65  介護福祉士に関する次の記述のうち、適切なものを1つ選びなさい。

    1  傷病者に対する療養上の世話又は診療の補助を業とする。
    2  喀痰吸引｛かくたんきゅういん｝を行うときは市町村の窓口に申請する。
    3  業務独占の資格である。
    4  資格を更新するために5年ごとに研修を受講する。
    5  信用を傷つけるような行為は禁止されている。

問題66  施設利用者の個人情報の保護に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  職員がすべての個人情報を自由に閲覧できるように、パスワードを共有する。
    2  個人情報を記載した書類は、そのまま新聞紙と一緒に捨てる。
    3  個人情報保護に関する研修会を定期的に開催し、意識の向上を図る。
    4  職員への守秘義務の提示は、採用時ではなく退職時に書面で行う。
    5  利用者の音声情報は、同意を得ずに使用できる。

問題67  個別性や多様性を踏まえた介護に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  その人らしさは、障害特性から判断する。
    2  生活習慣は、生活してきた環境から理解する。
    3  生活歴は、成人期以降の情報から収集する。
    4  生活様式は、同居する家族と同一にする。
    5  衣服は、施設の方針によって統一する。

問題68  Ａさん（48歳、女性、要介護1）は、若年性認知症（dementia with early onset）で、夫、長女（高校1年生）と同居している。Ａさんは家族と過ごすことを希望し、小規模多機能型居宅介護で通いを中心に利用を始めた。Ａさんのことが心配な長女は、部活動を諦めて学校が終わるとすぐに帰宅していた。
ある日、夫が、「長女が、学校の先生たちにも相談しているが、今の状況をわかってくれる人がいないと涙を流すことがある」と介護福祉職に相談をした。
夫の話を聞いた介護福祉職の対応として、最も適切なものを1つ選びなさい。

    1  長女に、掃除や洗濯の方法を教える。
    2  家族でもっと頑張るように、夫を励ます。
    3  同じような体験をしている人と交流できる場について情報を提供する。
    4  介護老人福祉施設への入所の申込みを勧める。
    5  介護支援専門員（ケアマネジャー）に介護サービスの変更を提案する。

問題69  Ｂさん（61歳、男性、要介護3）は、脳梗塞（cerebral infarction）による左片麻痺｛ひだりかたまひ｝がある。週2回訪問介護（ホームヘルプサービス）を利用し、妻（58歳）と二人暮らしである。自宅での入浴が好きで、妻の介助を受けながら、毎日入浴している。サービス提供責任者に、Ｂさんから、「浴槽から立ち上がるのがつらくなってきた。何かいい方法はないですか」と相談があった。
Ｂさんへのサービス提供責任者の対応として、最も適切なものを1つ選びなさい。

    1  Ｂさんがひとりで入浴できるように、自立生活援助の利用を勧める。
    2  浴室を広くするために、居宅介護住宅改修費を利用した改築を勧める。
    3  妻の入浴介助の負担が軽くなるように、行動援護の利用を勧める。
    4  入浴補助用具で本人の力を生かせるように、特定福祉用具販売の利用を勧める。
    5  Ｂさんが入浴を継続できるように、通所介護（デイサービス）の利用を勧める。

問題70  社会奉仕の精神をもって、住民の立場に立って相談に応じ、必要な援助を行い、社会福祉の増進に努める者として、適切なものを1つ選びなさい。

    1  民生委員
    2  生活相談員
    3  訪問介護員（ホームヘルパー）
    4  通所介護職員
    5  介護支援専門員（ケアマネジャー）

問題71  3階建て介護老人福祉施設がある住宅地に、洪水・内水氾濫の図記号マークに関連した警戒レベル3が発令された。介護福祉職がとるべき行動として、最も適切なものを1つ選びなさい。

    1  玄関のドアを開けたままにする。
    2  消火器で、初期消火する。
    3  垂直避難誘導をする。
    4  利用者家族に安否情報を連絡する。
    5  転倒の危険性があるものを固定する。

問題72  次の記述のうち、介護における感染症対策として、最も適切なものを1つ選びなさい。

    1  手洗いは、液体石鹸｛えきたいせっけん｝よりも固形石鹸｛こけいせっけん｝を使用する。
    2  配膳時にくしゃみが出たときは、口元をおさえた手でそのまま行う。
    3  嘔吐物｛おうとぶつ｝の処理は、素手で行う。
    4  排泄｛はいせつ｝の介護は、利用者ごとに手袋を交換する。
    5  うがい用のコップは、共用にする。

問題73  介護福祉士が行う服薬の介護に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  服薬時間は、食後に統一する。
    2  服用できずに残った薬は、介護福祉士の判断で処分する。
    3  多種類の薬を処方された場合は、介護福祉士が一包化する。
    4  内服薬の用量は、利用者のその日の体調で決める。
    5  副作用の知識をもって、服薬の介護を行う。

## コミュニケーション技術

問題74  Ｃさん（85歳、女性、要介護3）は、介護老人保健施設に入所しており、軽度の難聴がある。数日前から、職員は感染症対策として日常的にマスクを着用して勤務することになった。
ある日、Ｄ介護福祉職がＣさんの居室を訪問すると、「孫が絵を描いて送ってくれたの」と笑いながら絵を見せてくれた。Ｄ介護福祉職はＣさんの言動に共感的理解を示すために、意図的に非言語コミュニケーションを用いて対応した。
このときのＤ介護福祉職のＣさんへの対応として、最も適切なものを1つ選びなさい。

    1  「よかったですね」と紙に書いて渡した。
    2  目元を意識した笑顔を作り、大きくうなずいた。
    3  「お孫さんの絵が届いて、うれしかったですね」と耳元で話した。
    4  「私もうれしいです」と、ゆっくり話した。
    5  「えがとてもじょうずです」と五十音表を用いて伝えた。

問題75  利用者の家族との信頼関係の構築を目的としたコミュニケーションとして、最も適切なものを1つ選びなさい。

    1  家族に介護技術を教える。
    2  家族に介護をしている当事者の会に参加することを提案する。
    3  家族から介護の体験を共感的に聴く。
    4  家族に介護を続ける強い気持ちがあるかを質問する。
    5  家族に介護保険が使える範囲を説明する。

問題76  Ｅさん（70歳、女性）は、脳梗塞（cerebral infarction）の後遺症で言語に障害がある。発語はできるが、話したいことをうまく言葉に言い表せない。聴覚機能に問題はなく、日常会話で使用する単語はだいたい理解できるが、単語がつながる文章になるとうまく理解できない。ある日、Ｅさんに介護福祉職が、「お風呂は、今日ではなくあしたですよ」と伝えると、Ｅさんはしばらく黙って考え、理解できない様子だった。
このとき、Ｅさんへの介護福祉職の対応として、最も適切なものを1つ選びなさい。

    1  「何がわからないのか教えてください」と質問する。
    2  「お風呂、あした」と短い言葉で伝える。
    3  「今日、お風呂に入りたいのですね」と確かめる。
    4  「あしたがお風呂の日で、今日は違いますよ」と言い換える。
    5  「お・ふ・ろ・は・あ・し・た」と1音ずつ言葉を区切って伝える。

問題77  Ｆさん（70歳、女性）は、最近、抑うつ状態（depressive state）にあり、ベッドに寝ていることが多く、「もう死んでしまいたい」とつぶやいていた。
Ｆさんの発言に対する、介護福祉職の言葉かけとして、最も適切なものを1つ選びなさい。

    1  「落ちこんだらだめですよ」
    2  「とてもつらいのですね」
    3  「どうしてそんなに寝てばかりいるのですか」
    4  「食堂へおしゃべりに行きましょう」
    5  「元気を出して、頑張ってください」

問題78  Ｇさん（70歳、女性、要介護1）は、有料老人ホームに入居していて、網膜色素変性症（retinitis pigmentosa）による夜盲がある。ある日の夕方、Ｇさんがうす暗い廊下を歩いているのをＨ介護福祉職が発見し、「Ｈです。大丈夫ですか」と声をかけた。Ｇさんは、「びっくりした。見えにくくて、わからなかった…」と暗い表情で返事をした。
このときのＧさんに対するＨ介護福祉職の受容的な対応として、最も適切なものを1つ選びなさい。

    1  「驚かせてしまいましたね。一緒に歩きましょうか」
    2  「明るいところを歩きましょう。電気をつけたほうがいいですよ」
    3  「見えにくくなってきたのですね。一緒に点字の練習を始めましょう」
    4  「白杖｛はくじょう｝があるかを確認しておきます。白杖｛はくじょう｝を使うようにしましょう」
    5  「暗い顔をしないでください。頑張りましょう」

問題79  事例検討の目的に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  家族に介護計画を説明し、同意を得る。
    2  上司に利用者への対応の結果を報告し、了解を得る。
    3  介護計画の検討をとおして、チームの交流を深める。
    4  チームで事例の課題を共有し、解決策を見いだす。
    5  各職種の日頃の悩みを共有する。

## 生活支援技術

問題80  介護老人福祉施設における、レクリエーション活動に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  利用者全員が参加することを重視する。
    2  毎回、異なるプログラムを企画する。
    3  プログラムに買い物や調理も取り入れる。
    4  利用者の過去の趣味を、プログラムに取り入れることは避ける。
    5  地域のボランティアの参加は、遠慮してもらう。

問題81  関節リウマチ（rheumatoid arthritis）で、関節の変形や痛みがある人への住まいに関する介護福祉職の助言として、最も適切なものを1つ選びなさい。

    1  手すりは、握らずに利用できる平手すりを勧める。
    2  いすの座面の高さは、低いものを勧める。
    3  ベッドよりも、床に布団を敷いて寝るように勧める。
    4  部屋のドアは、開き戸を勧める。
    5  2階建ての家の場合、居室は2階にすることを勧める。

問題82  心身機能が低下した高齢者の住環境の改善に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  玄関から道路までは、コンクリートから砂利敷きにする。
    2  扉の取っ手は、レバーハンドルから丸いドアノブにする。
    3  階段の足が乗る板と板の先端部分は、反対色から同系色にする。
    4  車いすを使用する居室の床は、畳から板製床材（フローリング）にする。
    5  浴槽は、和洋折衷式から洋式にする。

問題83  仰臥位｛ぎょうがい｝（背臥位｛はいがい｝）から半座位（ファーラー位）にするとき、ギャッチベッドの背上げを行う前の介護に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  背部の圧抜きを行う。
    2  臀部｛でんぶ｝をベッド中央部の曲がる部分に合わせる。
    3  ベッドの高さを最も低い高さにする。
    4  利用者の足がフットボードに付くまで水平移動する。
    5  利用者のからだをベッドに対して斜めにする。

問題84  回復期にある左片麻痺｛ひだりかたまひ｝の利用者が、ベッドで端座位から立位になるときの基本的な介護方法に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  利用者の右側に立つ。
    2  利用者に、ベッドに深く座るように促す。
    3  利用者に、背すじを伸ばして真上に立ち上がるように促す。
    4  利用者の左側に荷重がかかるように支える。
    5  利用者の左の膝頭に手を当てて保持し、膝折れを防ぐ。

問題85  標準型車いすを用いた移動の介護に関する次の記述のうち、適切なものを1つ選びなさい。

    1  急な上り坂は、すばやく進む。
    2  急な下り坂は、前向きで進む。
    3  踏切を渡るときは、駆動輪を上げて進む。
    4  エレベーターに乗るときは、正面からまっすぐに進む。
    5  段差を降りるときは、前輪から下りる。

問題86  医学的管理の必要がない高齢者の爪の手入れに関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  爪は、入浴の前に切る。
    2  爪の先の白い部分は、残らないように切る。
    3  爪は、一度にまっすぐ横に切る。
    4  爪の両端は、切らずに残す。
    5  爪切り後は、やすりをかけて滑らかにする。

問題87  左片麻痺｛ひだりかたまひ｝の利用者が、端座位でズボンを着脱するときの介護に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  最初に、左側の腰を少し上げて脱ぐように促す。
    2  右膝を高く上げて、脱ぐように促す。
    3  左足を右の大腿｛だいたい｝の上にのせて、ズボンを通すように促す。
    4  立ち上がる前に、ズボンを膝下まで上げるように促す。
    5  介護福祉職は右側に立って、ズボンを上げるように促す。

問題88  次のうち、嚥下機能｛えんげきのう｝の低下している利用者に提供するおやつとして、最も適切なものを1つ選びなさい。

    1  クッキー
    2  カステラ
    3  もなか
    4  餅
    5  プリン

問題89  介護老人福祉施設の介護福祉職が、管理栄養士と連携することが必要な利用者の状態として、最も適切なものを1つ選びなさい。

    1  利用者の食べ残しが目立つ。
    2  経管栄養をしている利用者が嘔吐｛おうと｝する。
    3  利用者の食事中の姿勢が不安定である。
    4  利用者の義歯がぐらついている。
    5  利用者の摂食・嚥下｛えんげ｝の機能訓練が必要である。

問題90  次の記述のうち、血液透析を受けている利用者への食事の介護として、最も適切なものを1つ選びなさい。

    1  塩分の多い食品をとるように勧める。
    2  ゆでこぼした野菜をとるように勧める。
    3  乳製品を多くとるように勧める。
    4  水分を多くとるように勧める。
    5  魚や肉を使った料理を多くとるように勧める。

問題91  介護老人福祉施設の一般浴（個浴）で、右片麻痺｛みぎかたまひ｝の利用者が移乗台に座っている。その状態から安全に入浴をするための介護福祉職の助言として、最も適切なものを1つ選びなさい。

    1  「浴槽に入るときは、右足から入りましょう」
    2  「湯につかるときは、左膝に手をついてゆっくり入りましょう」
    3  「浴槽内では、足で浴槽の壁を押すようにして姿勢を安定させましょう」
    4  「浴槽内では、後ろの壁に寄りかかり足を伸ばしましょう」
    5  「浴槽から出るときは、真上方向に立ち上がりましょう」

問題92  次の記述のうち、椅座位で足浴を行う介護方法として、最も適切なものを1つ選びなさい。

    1  ズボンを脱いだ状態で行う。
    2  湯温の確認は、介護福祉職より先に利用者にしてもらう。
    3  足底は、足浴用容器の底面に付いていることを確認する。
    4  足に付いた石鹸｛せっけん｝の泡は、洗い流さずに拭き取る。
    5  足浴用容器から足を上げた後は、自然乾燥させる。

問題93  身体機能が低下している高齢者が、ストレッチャータイプの特殊浴槽を利用するときの入浴介護の留意点として、最も適切なものを1つ選びなさい。

    1  介護福祉職2名で、洗髪と洗身を同時に行う。
    2  背部を洗うときは、側臥位｛そくがい｝にして行う。
    3  浴槽に入るときは、両腕の上から固定ベルトを装着する。
    4  浴槽では、首までつかるようにする。
    5  浴槽につかる時間は、20分程度とする。

問題94  Ｊさん（84歳、女性、要介護3）は、認知症（dementia）があり、夫（86歳、要支援1）と二人暮らしである。Ｊさんは尿意はあるが、夫の介護負担を軽減するため終日おむつを使用しており、尿路感染症（urinary tract infection）を繰り返していた。夫が体調不良になったので、Ｊさんは介護老人福祉施設に入所した。
Ｊさんの尿路感染症（urinary tract infection）を予防する介護として、最も適切なものを1つ選びなさい。

    1  尿の性状を観察する。
    2  体温の変化を観察する。
    3  陰部洗浄の回数を検討する。
    4  おむつを使わないで、トイレに誘導する。
    5  膀胱留置｛ぼうこうりゅうち｝カテーテルの使用を提案する。

問題95  夜間、自宅のトイレでの排泄｛はいせつ｝が間に合わずに失敗してしまう高齢者への介護福祉職の助言として、最も適切なものを1つ選びなさい。

    1  水分摂取量を減らすように勧める。
    2  終日、リハビリパンツを使用するように勧める。
    3  睡眠薬を服用するように勧める。
    4  泌尿器科を受診するように勧める。
    5  夜間は、ポータブルトイレを使用するように勧める。

問題96  介護福祉職が行うことができる、市販のディスポーザブルグリセリン浣腸器｛かんちょうき｝を用いた排便の介護に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  浣腸液｛かんちょうえき｝は、39℃～40℃に温める。
    2  浣腸液｛かんちょうえき｝を注入するときは、立位をとるように声をかける。
    3  浣腸液｛かんちょうえき｝は、すばやく注入する。
    4  浣腸液｛かんちょうえき｝を注入したら、すぐに排便するように声をかける。
    5  排便がない場合は、新しい浣腸液｛かんちょうえき｝を再注入する。

問題97  訪問介護員（ホームヘルパー）が行う見守り的援助として、最も適切なものを1つ選びなさい。

    1  ゴミの分別ができるように声をかける。
    2  利用者がテレビを見ている間に洗濯物を干す。
    3  着られなくなった服を作り直す。
    4  調理したものを盛り付け、食事を提供する。
    5  冷蔵庫の中を整理し、賞味期限が切れた食品を捨てておく。

問題98  高齢者が靴下・靴を選ぶときの介護福祉職の対応として、最も適切なものを1つ選びなさい。

    1  靴下は、指つきのきついものを勧める。
    2  靴下は、足底に滑り止めがあるものを勧める。
    3  靴は、床面からつま先までの高さが小さいものを勧める。
    4  靴は、踵｛かかと｝のない脱ぎやすいものを勧める。
    5  靴は、先端部に0.5～1cmの余裕があるものを勧める。

問題99  Ｋさん（77歳、女性、要支援2）は、もの忘れが目立ちはじめ、訪問介護（ホームヘルプサービス）を利用しながら夫と二人で生活している。訪問時、Ｋさん夫婦から、「Ｋさんがテレビショッピングで購入した健康食品が毎月届いてしまい、高額の支払いが発生して困っている」と相談があった。
Ｋさん夫婦に対する訪問介護員（ホームヘルパー）の発言として、最も適切なものを1つ選びなさい。

    1  「健康食品は処分しましょう」
    2  「クーリング・オフをしましょう」
    3  「買い物は夫がするようにしましょう」
    4  「契約内容を一緒に確認しましょう」
    5  「テレビショッピングでの買い物はやめましょう」

問題100  消化管ストーマを造設した利用者への睡眠の介護に関する記述として、最も適切なものを1つ選びなさい。

    1  寝る前にストーマから出血がある場合は、軟膏｛なんこう｝を塗布する。
    2  寝る前に、パウチに便がたまっていたら捨てる。
    3  寝る前に、ストーマ装具を新しいものに交換する。
    4  便の漏れが心配な場合は、パウチの上からおむつを強く巻く。
    5  睡眠を妨げないように、パウチの観察は控える。

問題101  Ｌさん（79歳、男性、要介護2）は、介護老人保健施設に入所して1か月が経過した。睡眠中に大きないびきをかいていることが多く、いびきの音が途切れることもある。夜間に目を覚ましていたり、起床時にだるそうにしている様子もしばしば見られている。
介護福祉職がＬさんについて収集すべき情報として、最も優先度の高いものを1つ選びなさい。

    1  枕の高さ
    2  マットレスの硬さ
    3  掛け布団の重さ
    4  睡眠中の足の動き
    5  睡眠中の呼吸状態

問題102  Ｍさん（98歳、男性、要介護5）は、介護老人福祉施設に入所している。誤嚥性肺炎｛ごえんせいはいえん｝（aspiration pneumonia）で入退院を繰り返し、医師からは終末期が近い状態であるといわれている。
介護福祉職が確認すべきこととして、最も優先度の高いものを1つ選びなさい。
    1  主治医の今後の見通し
    2  誤嚥性肺炎｛ごえんせいはいえん｝（aspiration pneumonia）の発症時の入院先
    3  経口摂取に対する本人の意向
    4  経口摂取に対する家族の意向
    5  延命治療に対する家族の希望

問題103  デスカンファレンス（death conference）の目的に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  一般的な死の受容過程を学習する。
    2  終末期を迎えている利用者の介護について検討する。
    3  利用者の家族に対して、死が近づいたときの身体の変化を説明する。
    4  亡くなった利用者の事例を振り返り、今後の介護に活用する。
    5  終末期の介護に必要な死生観を統一する。

問題104  福祉用具を活用するときの基本的な考え方として、最も適切なものを1つ選びなさい。

    1  福祉用具が活用できれば、住宅改修は検討しない。
    2  複数の福祉用具を使用するときは、状況に合わせた組合せを考える。
    3  福祉用具の選択に迷うときは、社会福祉士に選択を依頼する。
    4  家族介護者の負担軽減を最優先して選ぶ。
    5  福祉用具の利用状況のモニタリング（monitoring）は不要である。

問題105  次のうち、握力の低下がある利用者が使用する杖｛つえ｝として、最も適切なものを1つ選びなさい。

    1  T字杖
    2  オフセット杖
    3  ロフストランド・クラッチ
    4  多点杖
    5  サイドケイン

## 介護過程

問題106  介護福祉職が、初回の面談で情報を収集するときの留意点として、最も適切なものを1つ選びなさい。

    1  用意した項目を次から次に質問する。
    2  目的を意識しながら話を聴く。
    3  ほかの利用者が同席する状況で質問する。
    4  最初に経済状態に関する質問をする。
    5  家族の要望を中心に話を聴く。

問題107  介護過程の評価に関する次の記述のうち、最も適切なものを1つ選びなさい。

    1  生活状況が変化しても、介護計画で設定した日に評価する。
    2  サービス担当者会議で評価する。
    3  相談支援専門員が中心になって評価する。
    4  利用者の満足度を踏まえて評価する。
    5  介護計画の実施中に評価基準を設定する。

問題108  次の記述のうち、介護老人保健施設で多職種連携によるチームアプローチ（team approach）を実践するとき、介護福祉職が担う役割として、最も適切なものを1つ選びなさい。

    1  利用者の生活状況の変化に関する情報を提供する。
    2  総合的な支援の方向性を決める。
    3  サービス担当者会議を開催する。
    4  必要な検査を指示する。
    5  ほかの職種が担う貢献度を評価する。

次の事例を読んで、問題109、問題110について答えなさい。
〔事  例〕
Ａさん（75歳、女性）は、一人暮らしで、身体機能に問題はない。70歳まで地域の子どもたちに大正琴を教えていた。認知症（dementia）の進行が疑われて、心配した友人が地域包括支援センターに相談した結果、Ａさんは介護老人福祉施設に入所することになった。入所時のＡさんの要介護度は3であった。
入所後、短期目標を、「施設に慣れ、安心して生活する（3か月）」と設定し、計画は順調に進んでいた。Ａさんは施設の大正琴クラブに自ら進んで参加し、演奏したり、ほかの利用者に大正琴を笑顔で教えたりしていた。ある日、クラブの終了後に、Ａさんは部屋に戻らずに、エレベーターの前で立ち止まっていた。介護職員が声をかけると、Ａさんが、「あの子たちが待っているの」と強い口調で言った。

問題109  大正琴クラブが終わった後のＡさんの行動を解釈するために必要な情報として、最も優先すべきものを1つ選びなさい。

    1  介護職員の声かけのタイミング
    2  Ａさんが演奏した時間
    3  「あの子たちが待っているの」という発言
    4  クラブに参加した利用者の人数
    5  居室とエレベーターの位置関係

問題110  Ａさんの状況から支援を見直すことになった。
次の記述のうち、新たな支援の方向性として、最も適切なものを1つ選びなさい。

    1  介護職員との関係を改善する。
    2  身体機能を改善する。
    3  演奏できる自信を取り戻す。
    4  エレベーターの前に座れる環境を整える。
    5  大正琴を教える役割をもつ。

次の事例を読んで、問題111、問題112について答えなさい。
〔事  例〕
Ｂさん（50歳、男性、障害支援区分3）は、49歳のときに脳梗塞（cerebral infarction）を発症し、左片麻痺｛ひだりかたまひ｝で高次脳機能障害（higher brain dysfunction）と診断された。以前は大工で、手先が器用だったと言っている。
現在は就労継続支援Ｂ型事業所に通っている。短期目標を、「右手を使い、作業を自分ひとりで行える（3か月）」と設定し、製品を箱に入れる単純作業を任されていた。ほかの利用者との人間関係も良好で、左片麻痺｛ひだりかたまひ｝に合わせた作業台で、毎日の作業目標を達成していた。生活支援員には、「将来は手先を使う仕事に就きたい」と希望を話していた。
将来に向けて、生活支援員が新たに製品の組立て作業を提案すると、Ｂさんも喜んで受け入れた。初日に、「ひとりで頑張る」と始めたが、途中で何度も手が止まり、完成品に不備が見られた。生活支援員が声をかけると、「こんなの、できない」と大声を出した。

問題111  生活支援員の声かけに対し、Ｂさんが大声を出した理由を解釈する視点として、最も適切なものを1つ選びなさい。

    1  ほかの利用者との人間関係
    2  生活支援員に話した将来の希望
    3  製品を箱に入れる毎日の作業量
    4  製品の組立て作業の状況
    5  左片麻痺｛ひだりかたまひ｝に合わせた作業台

問題112  Ｂさんに対するカンファレンス（conference）が開催され、短期目標を達成するための具体的な支援について見直すことになった。
次の記述のうち、見直した支援内容として、最も適切なものを1つ選びなさい。

    1  完成品の不備を出すことへの反省を促す。
    2  左側に部品を置いて作業するように促す。
    3  完成までの手順を理解しやすいように示す。
    4  生活支援員が横に座り続けて作業内容を指示する。
    5  製品を箱に入れる単純作業も同時に行うように調整する。

問題113  事例研究を行うときに、遵守すべき倫理的配慮として、適切なものを1つ選びなさい。

    1  研究内容を説明して、事例対象者の同意を得る。
    2  個人が特定できるように、氏名を記載する。
    3  得られたデータは、研究終了後すぐに破棄する。
    4  論文の一部であれば、引用元を明示せずに利用できる。
    5  研究成果を得るために、事実を拡大解釈する。

＜総合問題＞

## 総合問題

（総合問題1）

次の事例を読んで、問題114から問題116までについて答えなさい。
〔事  例〕
Ｃさん（59歳、男性）は、妻（55歳）と二人暮らしであり、専業農家である。Ｃさんはおとなしい性格であったが、最近怒りやすくなったと妻は感じていた。Ｃさんは毎日同じ時間に同じコースを散歩している。ある日、散歩コースの途中にあり、昔からよく行く八百屋から、「Ｃさんが代金を支払わずに商品を持っていった。今回で2回目になる。お金を支払いにきてもらえないか」と妻に連絡があった。妻がＣさんに確認したところ、悪いことをした認識がなかった。心配になった妻がＣさんと病院に行くと、前頭側頭型認知症（frontotemporal dementia）と診断を受けた。妻は今後同じようなことが起きないように、Ｃさんの行動を常に見守り、外出を制限したが、疲労がたまり、今後の生活に不安を感じた。そこで、地域包括支援センターに相談し、要介護認定の申請を行い、訪問介護（ホームヘルプサービス）を利用することになった。

問題114  Ｃさんが八百屋でとった行動から考えられる状態として、最も適切なものを1つ選びなさい。

    1  脱抑制
    2  記憶障害
    3  感情失禁
    4  見当識障害
    5  遂行機能障害

問題115  Ｃさんの介護保険制度の利用に関する次の記述のうち、適切なものを1つ選びなさい。

    1  介護保険サービスの利用者負担割合は1割である。
    2  介護保険料は特別徴収によって納付する。
    3  要介護認定の結果が出る前に介護保険サービスを利用することはできない。
    4  要介護認定の利用者負担割合は2割である。
    5  介護保険サービスの費用はサービスの利用回数に関わらず定額である。

問題116  その後、妻に外出を制限されたＣさんは不穏となった。困った妻が訪問介護員（ホームヘルパー）に相談したところ、「八百屋に事情を話して事前にお金を渡して、Ｃさんが品物を持ち去ったときは、渡したお金から商品代金を支払うようにお願いしてはどうか」とアドバイスを受けた。
訪問介護員（ホームヘルパー）が意図したＣさんへの関わりをＩＣＦ（International Classification of Functioning, Disability and Health：国際生活機能分類）に当てはめた記述として、最も適切なものを1つ選びなさい。

    1  個人因子への影響を意図して、健康状態に働きかける。
    2  健康状態への影響を意図して、心身機能に働きかける。
    3  活動への影響を意図して、身体構造に働きかける。
    4  参加への影響を意図して、環境因子に働きかける。
    5  環境因子への影響を意図して、個人因子に働きかける。

（総合問題2）

次の事例を読んで、問題117から問題119までについて答えなさい。
〔事  例〕
Ｄさん（70歳、男性）は、自宅で妻と二人暮らしで、年金収入で生活している。ある日、車を運転中に事故に遭い救急搬送された。医師からは、第4胸髄節まで機能が残存している脊髄損傷（spinal cord injury）と説明を受けた。Ｄさんは、入院中に要介護3の認定を受けた。
Ｄさんは、退院後は自宅で生活することを望んでいた。妻は一緒に暮らしたいと思うが、Ｄさんの身体状況を考えると不安を感じていた。介護支援専門員（ケアマネジャー）は、「退院後は、在宅復帰を目的に、一定の期間、リハビリテーション専門職がいる施設で生活してはどうか」とＤさんに提案した。Ｄさんは妻と退院後の生活について話し合った結果、一定期間施設に入所して、その間に、自宅の住宅改修を行うことにして、介護支援専門員（ケアマネジャー）に居宅介護住宅改修費について相談した。

問題117  次のうち、Ｄさんが提案を受けた施設として、最も適切なものを1つ選びなさい。

    1  養護老人ホーム
    2  軽費老人ホーム
    3  介護老人福祉施設
    4  介護老人保健施設
    5  介護医療院

問題118  次のうち、介護支援専門員（ケアマネジャー）がＤさんに説明する居宅介護住宅改修費の支給限度基準額として、適切なものを1つ選びなさい。

    1  10万円
    2  15万円
    3  20万円
    4  25万円
    5  30万円

問題119  Ｄさんが施設入所してから3か月後、住宅改修を終えた自宅に戻ることになった。Ｄさんは自宅での生活を楽しみにしている。その一方で、不安も抱えていたため、担当の介護福祉士は、理学療法士と作業療法士に相談して、生活上の留意点を記載した冊子を作成して、Ｄさんに手渡した。
次の記述のうち、冊子の内容として、最も適切なものを1つ選びなさい。

    1  食事では、スプーンを自助具で手に固定する。
    2  移動には、リクライニング式車いすを使用する。
    3  寝具は、エアーマットを使用する。
    4  更衣は、ボタンエイドを使用する。
    5  外出するときには、事前に多機能トイレの場所を確認する。

（総合問題3）

次の事例を読んで、問題120から問題122までについて答えなさい。
〔事  例〕
Ｅさん（34歳、女性、障害支援区分3）は、特別支援学校の高等部を卒業後、週2回、生活介護を利用しながら自宅で生活している。Ｅさんはアテトーゼ型（athetosis）の脳性麻痺｛のうせいまひ｝（cerebral palsy）で不随意運動があり、首を振る動作が見られる。
食事は首の動きに合わせて、自助具を使って食べている。食事中は不随意運動が強く、食事が終わると、「首が痛い、しびれる」と言ってベッドに横になるときがある。
また、お茶を飲むときは取っ手つきのコップで飲んでいるが、コップを口元に運ぶまでにお茶がこぼれるようになってきた。日頃から自分のことは自分でやりたいと考えていて、お茶が上手に飲めなくなってきたことを気にしている。
Ｅさんは、生活介護事業所で油絵を描くことを楽しみにしている。以前から隣町の油絵教室に通い技術を高めたいと話していた。そこでＥさんは、「自宅から油絵教室に通うときの介助をお願いするにはどうしたらよいか」と介護福祉職に相談した。

問題120  Ｅさんの食事の様子から、今後、引き起こされる可能性が高いと考えられる二次障害として、最も適切なものを1つ選びなさい。

    1  変形性股関節症（coxarthrosis）
    2  廃用症候群（disuse syndrome）
    3  起立性低血圧（orthostatic hypotension）
    4  脊柱側弯症｛せきちゅうそくわんしょう｝（scoliosis）
    5  頚椎症性脊髄症｛けいついしょうせいせきずいしょう｝（cervical spondylotic myelopathy）

問題121  Ｅさんがお茶を飲むときの介護福祉職の対応として、最も適切なものを1つ選びなさい。

    1  吸い飲みに変更する。
    2  ストローつきコップに変更する。
    3  重いコップに変更する。
    4  コップを両手で持つように伝える。
    5  全介助を行う。

問題122  介護福祉職は、Ｅさんが隣町の油絵教室に通うことができるようにサービスを提案したいと考えている。
次のうち、Ｅさんが利用するサービスとして、最も適切なものを1つ選びなさい。

    1  自立生活援助
    2  療養介護
    3  移動支援
    4  自立訓練
    5  同行援護

（総合問題4）

次の事例を読んで、問題123から問題125までについて答えなさい。
〔事  例〕
Ｆさん（20歳、男性）は、自閉症スペクトラム障害（autism spectrum disorder）と重度の知的障害があり、自宅で母親（50歳）、姉（25歳）と3人で暮らしている。
Ｆさんは生活介護事業所を利用している。事業所では比較的落ち着いているが、自宅に帰ってくると母親に対してかみつきや頭突きをすることがあった。また、自分で頭をたたくなどの自傷行為もたびたび見られる。
仕事をしている母親に代わり、小さい頃から食事や排泄｛はいせつ｝の介護をしている姉は、これまでＦさんの行動を止めることができていたが、最近ではからだが大きくなり力も強くなって、母親と協力しても止めることが難しくなっていた。
家族で今後のことを考えた結果、Ｆさんは障害者支援施設に入所することになった。

問題123  次のうち、Ｆさんが自宅に帰ってきたときの状態に該当するものとして、最も適切なものを1つ選びなさい。

    1  学習障害
    2  注意欠陥多動性障害
    3  高次脳機能障害
    4  強度行動障害
    5  気分障害

問題124  Ｆさんが入所してからも月1、2回は、姉が施設を訪ね、Ｆさんの世話をしている。
ある日、担当の介護福祉職が姉に声をかけると、「小学生の頃から、学校が終わると友だちと遊ばずにまっすぐ家に帰り、母親に代わって、弟の世話をしてきた。今は、弟を見捨てたようで、申し訳ない」などと話す。
介護福祉職の姉への対応として、最も適切なものを1つ選びなさい。

    1  「これからもＦさんのお世話をしっかり行ってください」
    2  「Ｆさんは落ち着いていて、自傷他害行為があるようには見えませんね」
    3  「お姉さんは、小さい頃からお母さんの代わりをしてきたのですね」
    4  「訪問回数を減らしてはどうですか」
    5  「施設入所を後悔しているのですね。もう一度在宅ケアを考えましょう」

問題125  Ｆさんが施設に入所して1年が経った。介護福祉職は、Ｆさん、母親、姉と共にこれまでの生活と支援を振り返り、当面、施設で安定した生活が送れるように検討した。
次のうち、Ｆさんの支援を修正するときに利用するサービスとして、正しいものを1つ選びなさい。

    1  地域定着支援
    2  計画相談支援
    3  地域移行支援
    4  基幹相談支援
    5  基本相談支援

## 解答一覧
  
   1 5
   2 2
   3 5
   4 3
   5 4
   6 1
   7 1
   8 3
   9 5
  10 5
  
  11 2
  12 3
  13 5
  14 4
  15 4
  16 1
  17 3
  18 2
  19 3
  20 1
  
  21 3
  22 1
  23 1  
  24 4
  25 5
  26 4
  27 2
  28 2
  29 5
  30 4
  
  31 3
  32 2
  33 5
  34 1
  35 4
  36 5
  37 3
  38 4
  39 1
  40 1
  
  41 4
  42 2
  43 5
  44 3
  45 3
  46 4  # 4,５が正答
  47 1
  48 2
  49 1
  50 2
  
  51 5
  52 2
  53 4
  54 3
  55 3
  56 2
  57 5
  58 4
  59 5
  60 4
  
  61 1
  62 2
  63 3
  64 5
  65 5
  66 3
  67 2
  68 3
  69 4
  70 1
  
  71 3
  72 4
  73 5
  74 2
  75 3
  76 2
  77 2
  78 1
  79 4
  80 3
  
  81 1
  82 4
  83 2
  84 5
  85 4
  86 5
  87 3
  88 5
  89 1
  90 2
  
  91 3
  92 3
  93 2
  94 4
  95 5
  96 1
  97 1
  98 5
  99 4
 100 2
  
 101 5
 102 3
 103 4
 104 2
 105 3
 106 2
 107 4
 108 1
 109 3
 110 5
  
 111 4 
 112 3
 113 1
 114 1
 115 1
 116 4
 117 4
 118 3
 119 5
 120 5
  
 121 2
 122 3
 123 4
 124 3
 125 2






