
第36回（令和5年度）社会福祉士国家試験午前の問題
人体の構造と機能及び疾病

問題1  成熟時の発達を100％としたスキャモン（Scammon, R.）の臓器別発育曲線に関する次の記述のうち、正しいものを1つ選びなさい。
    1  25歳を100％として表している図である。
    2  身長など一般型はＳ字型カーブを示す。
    3  リンパ型は12歳頃に約90％となる。
    4  神経型は12歳頃に最も発達する。
    5  生殖型は12歳頃に70％となる。

問題2  事例を読んで、国際生活機能分類（ＩＣＦ）のモデルに基づく記述として、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（78歳、男性）は脳梗塞を発症し左片麻痺｛かたまひ｝となった。室内は手すりを伝って歩いている。外出時は車いすが必要で、近隣に住む長女が車いすを押して買物に出かけている。週1回のデイサービスでのレクリエーションに参加するのを楽しみにしている。
    1  年齢、性別は「心身機能」に分類される。
    2  左片麻痺は「個人因子」に分類される。
    3  手すりに伝って歩くことは「活動」に分類される。
    4  近隣に長女が住んでいるのは「参加」に分類される。
    5  デイサービスの利用は「環境因子」に分類される。

問題3  次のうち、身体障害者手帳の交付対象となる内部障害として、正しいものを1つ選びなさい。
    1  視覚障害
    2  そしゃく機能障害
    3  平衡機能障害
    4  ヒト免疫不全ウイルスによる免疫機能障害
    5  体幹機能障害

問題4  目の構造と病気に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  眼球の外層にある白目の部分は角膜である。
    2  白内障は水晶体が混濁してものが見えにくくなる。
    3  緑内障は眼圧が下がって視野障害を来す。
    4  加齢黄斑変性症では視力は保たれる。
    5  糖尿病性網膜症では失明は起こらない。

問題5  自閉スペクトラム症（ＡＳＤ）に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  成人になってから発症する。
    2  こだわりは強くない。
    3  幻覚がみられる。
    4  常同的な行動は認められない。
    5  相手の気持ちを理解することが苦手である。

問題6  次のうち、精神疾患の診断・統計マニュアル（ＤＳＭ－5）において、発達障害に当たる「神経発達症群/神経発達障害群」に分類されるものとして、正しいものを1つ選びなさい。
    1  神経性無食欲症
    2  統合失調症
    3  パニック障害
    4  適応障害
    5  注意欠如・多動症（ＡＤＨＤ）

問題7  廃用症候群に関する次の記述のうち、正しいものを1つ選びなさい。
    1  若年者にも生じる。
    2  数日間の安静では、筋力低下は起こらない。
    3  長期臥床｛がしょう｝により筋肉量が増加する。
    4  骨粗鬆症｛こつそしょうしょう｝は安静臥床により改善する。
    5  予防することはできない。

心理学理論と心理的支援

問題8  知覚に関する次の記述のうち、大きさの恒常性の事例として、最も適切なものを1つ選びなさい。
    1  形と大きさが同じ図形は、空間内でまとまっているように知覚される。
    2  電光掲示板で表示されている絵や文字が動いて、大きさが変化して見える。
    3  同じ人物が遠くにいる場合と近くにいる場合とでは、距離の違いほどに人の大きさが違って見えない。
    4  線遠近法を使った絵画では、奥行きを感じることで書かれている物の大きさの違いが知覚される。
    5  月を見ると、建物の上など低い位置にあるときは、天空高くにあるときよりも大きく見える。

問題9  次の記述のうち、オペラント条件づけの事例として、最も適切なものを1つ選びなさい。
    1  電車に乗っているときに事故にあってしまい、それ以降電車に乗るのが怖くなってしまった。
    2  以前に食べたときに体調が悪くなった食品を見ただけで、気分が悪くなってしまった。
    3  犬にベルの音を聞かせながら食事を与えていると、ベルの音だけで唾液が分泌するようになった。
    4  人に迷惑をかけるいたずらをした子どもを叱ったら、その行動をしなくなった。
    5  病院で受けた注射で痛い経験をした子どもが、予防接種のときに医師の白衣を見ただけで怖くなって泣き出した。

問題10  記憶に関する次の記述のうち、ワーキングメモリー（作動記憶）について、最も適切なものを1つ選びなさい。
    1  自転車の運転など、一連の動作に関する記憶である。
    2  休みの日に外出したなど、個人の経験に関する記憶である。
    3  カラスは鳥であるなど、一般的な知識に関する記憶である。
    4  感覚器が受け取った情報を、長期間そのまま保持する記憶である。
    5  暗算をするときなど、入力された情報とその処理に関する一時的な記憶である。

問題11  職場でうまく適応できない原因に関する相談者の次の発言のうち、ワイナー（Weiner, B.）による原因帰属の理論に基づき、安定し、かつ外的な原因による例として、最も適切なものを1つ選びなさい。
    1  自分の能力不足が原因だと思います。
    2  最近の体調不良が原因です。
    3  業務内容が難しかったことが原因です。
    4  たまたま運が悪かったのが原因です。
    5  自分の努力不足が原因だと感じています。

問題12  心的外傷後ストレス障害（ＰＴＳＤ）の症状に関する次の記述のうち、回避症状の事例として、最も適切なものを1つ選びなさい。
    1  ささいな事でもひどく驚いてしまうようになった。
    2  事故が起きたのは全て自分のせいだと考えてしまう。
    3  つらかった出来事を急に思い出すことがある。
    4  交通事故にあった場所を通らないようにして通勤している。
    5  大声を聞くと虐待されていたことを思い出し苦しくなる。

問題13  次のうち、小学校就学前の5歳児を対象とできる心理検査として、最も適切なものを1つ選びなさい。
    1  矢田部ギルフォード（ＹＧ）性格検査
    2  田中ビネー知能検査Ｖ
    3  ミネソタ多面人格目録（ＭＭＰＩ）
    4  文章完成法テスト（ＳＣＴ）
    5  ＷＡＩＳ－Ⅳ

問題14  クライエント中心療法に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  クライエントの話を非指示的に傾聴していく。
    2  解決に焦点をあわせ、クライエントの強みを発展させる。
    3  クライエントの家族関係を変容しようとする。
    4  クライエントの意識を無意識化していく。
    5  クライエントの認知や行動に焦点を当てていく。

社会理論と社会システム

問題15  持続可能な開発目標（ＳＤＧｓ）に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  1989年にアメリカのオレゴン州で策定された、行政評価のための指標である。
    2  生活に関する八つの活動領域から構成された指標である。
    3  貧困に終止符を打つとともに、気候変動への具体的な対策を求めている。
    4  1995年より毎年各国の指数が公表されている。
    5  貨幣換算した共通の尺度によって、一律に各指標を測定する。

問題16  次の記述のうち、ウェルマン（Wellman, B.）のコミュニティ解放論の説明として、最も適切なものを1つ選びなさい。
    1  特定の関心に基づくアソシエーションが、地域を基盤としたコミュニティにおいて多様に展開しているとした。
    2  現代社会ではコミュニティが地域という空間に限定されない形で展開されるとした。
    3  人口の量と密度と異質性から都市に特徴的な生活様式を捉えた。
    4  都市の発展過程は、住民階層の違いに基づいて中心部から同心円状に拡大するとした。
    5  アメリカの94のコミュニティの定義を収集・分析し、コミュニティ概念の共通性を見いだした。

問題17  次のうち、人々が社会状況について誤った認識をし、その認識に基づいて行動することで、結果としてその認識どおりの状況が実現してしまうことを指す概念として、最も適切なものを1つ選びなさい。
    1  予言の自己成就
    2  創発特性
    3  複雑性の縮減
    4  ホメオスタシス
    5  逆機能

問題18  「第16回出生動向基本調査結果の概要（2022年（令和4年））」（国立社会保障・人口問題研究所）に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  「いずれ結婚するつもり」と回答した未婚者の割合が、これまでの出生動向基本調査の中で最も高かった。
    2  第1子の妊娠が分かった時に就業していた妻が、子どもが1歳になった時も就業していたことを示す「就業継続率」は、2015年（平成27年）の調査の時よりも低下した。
    3  「結婚したら子どもを持つべき」との考えに賛成する未婚者の割合は、2015年（平成27年）の調査の時よりも上昇した。
    4  未婚男性がパートナーとなる女性に望む生き方として、結婚し、子どもをもつが、仕事も続ける「両立コース」が最も多く選択された。
    5  子どもを追加する予定がほぼない結婚持続期間15～19年の夫婦の平均出生子ども数（完結出生子ども数）は、2015年（平成27年）の調査の時よりも上昇した。

問題19  次の記述のうち、ライフサイクルについての説明として、最も適切なものを1つ選びなさい。
    1  個人の発達の諸段階であり、生物学的、心理学的、社会学的、経済学的な現象がそれに伴って起きることを示す概念である。
    2  生活を構成する諸要素間の相対的に安定したパターンを指す概念である。
    3  社会的存在としての人間の一生を、生まれた時代や様々な出来事に関連付けて捉える概念である。
    4  個人の人生の横断面に見られる生活の様式や構造、価値観を捉えるための概念である。
    5  人間の出生から死に至るプロセスに着目し、標準的な段階を設定して人間の一生の規則性を捉える概念である。

問題20  次のうち、信頼、規範、ネットワークなどによる人々のつながりの豊かさを表すために、パットナム（Putnam, R.）によって提唱された概念として、正しいものを1つ選びなさい。
    1  ハビトゥス
    2  ソーシャルキャピタル（社会関係資本）
    3  文化資本
    4  機械的連帯
    5  外集団

問題21  次の記述のうち、囚人のジレンマに関する説明として、最も適切なものを1つ選びなさい。
    1  協力し合うことが互いの利益になるにもかかわらず、非協力への個人的誘因が存在する状況。
    2  一人の人間が二つの矛盾した命令を受けて、身動きがとれない状況。
    3  相手のことをよく知らない人同士が、お互いの行為をすれ違いなく了解している状況。
    4  非協力的行動には罰を、協力的行動には報酬を与えることで、協力的行動が促される状況。
    5  公共財の供給に貢献せずに、それを利用するだけの成員が生まれる状況。

現代社会と福祉

問題22  福祉における政府と民間の役割に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  平行棒理論とは、救済に値する貧民は救貧行政が扱い、救済に値しない貧民は民間慈善事業が扱うべきだとする考え方を指す。
    2  繰り出し梯子｛はしご｝理論とは、ナショナルミニマムが保障された社会では、民間慈善事業が不要になるとの考え方を指す。
    3  社会市場のもとでは、ニーズと資源との調整は、価格メカニズムにより行われ、そこに政府が関与することはない。
    4  準市場のもとでは、サービスの供給に当たり、競争や選択の要素を取り入れつつ、人々の購買力の違いによる不平等を緩和するための施策が講じられることがある。
    5  ニュー・パブリック・マネジメント（ＮＰＭ）とは、福祉サービスの供給に参入した民間企業の経営効率化のために、その経営に行政職員を参画させる取組を指す。

問題23  次のうち、1930年代のアメリカにおけるニューディール政策での取組として、正しいものを1つ選びなさい。
    1  社会保障法の制定
    2  公民権法の制定
    3  メディケア（高齢者等の医療保険）の導入
    4  ＡＤＡ（障害を持つアメリカ人法）の制定
    5  ＴＡＮＦ（貧困家族一時扶助）の導入

    （注）  「障害を持つアメリカ人法」とは、「障害に基づく差別の明確かつ包括的な禁止について定める法律」のことである。

問題24  日本の貧困に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  日本の2010年代における「貧困率」は、経済協力開発機構（ＯＥＣＤ）加盟国の平均を大きく下回っている。
    2  「2019年国民生活基礎調査の概況」（厚生労働省）によれば、子どもがいる現役世帯の世帯員の「貧困率」は、「大人が二人以上」の世帯員よりも「大人が一人」の世帯員の方が高い。
    3  「2019年国民生活基礎調査の概況」（厚生労働省）によれば、子どもの「貧困率」は10％を下回っている。
    4  「平成29年版厚生労働白書」によれば、高齢者の「貧困率」は、子どもの「貧困率」に比べて低い。
    5  2018年（平成30年）の時点で、生活保護世帯に属する子どもの大学進学率は60％を超えている。

    （注）  ここでいう「貧困率」とは、等価可処分所得が中央値の半分に満たない世帯員の割合（相対的貧困率）を指す。

問題25  次の記述のうち、ブラッドショー（Bradshaw, J.）のニード類型を踏まえたニードの説明として、最も適切なものを1つ選びなさい。
    1  クライエントがニードを表明しなければ、ニードのアセスメントを行うことはできない。
    2  社会規範に照らしてニードの有無が判断されることはない。
    3  クライエントと専門職との間で、ニードの有無の判断が食い違うことはない。
    4  他人と比較してニードの有無が判断されることはない。
    5  クライエントがニードを自覚しなければ、クライエントからのニードは表明されない。

問題26  次のうち、日本における第1次ベビーブーム期の出生者が後期高齢者になるために、国が示した、医療や介護等の供給体制を整備する目途となる年次として、最も適切なものを1つ選びなさい。
    1  1973年（昭和48年）
    2  1990年（平成2年）
    3  2000年（平成12年）
    4  2025年（令和7年）
    5  2035年（令和17年）

問題27  次のうち、「外国人との共生社会の実現に向けたロードマップ」で示された内容として、最も適切なものを1つ選びなさい。
    1  在留外国人の出身国籍が多様化する傾向が止まり、南米諸国出身の日系人が在留者の大部分を占めるようになった。
    2  日本社会に活力を取り込むために、高度で専門的な技術・知識を有する者以外の外国人材の受入れを抑制する。
    3  外国人との共生社会は、一人ひとりの外国人が日本社会に適応するための努力をすれば実現可能である。
    4  外国人が安全に安心して暮らせるように、外国人に対する情報発信や相談体制を強化する。
    5  共生社会の実現のために、在留外国人には納税及び社会保険への加入の義務を免除する。

    （注）  「外国人との共生社会の実現に向けたロードマップ」とは、外国人材の受入れ・共生に関する関係閣僚会議が2022年（令和4年）6月14日に策定した文書のことである。 

問題28  次のうち、エスピン－アンデルセン（Esping-Andersen, G.）の福祉レジーム論に関する記述として、最も適切なものを1つ選びなさい。
    1  福祉レジームは、残余的モデルと制度的モデルの2つの類型からなる。
    2  市場や家族の有する福祉機能は、福祉レジームの分析対象とはされない。
    3  スウェーデンとドイツは同一の福祉レジームに属する。
    4  各国の社会保障支出の大小といった量的差異に限定した分析を行っている。
    5  福祉レジームの分析に当たり、脱商品化という概念を用いる。

問題29  所得の再分配に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  市場での所得分配によって生じる格差を是正する機能を有しうる。
    2  現物給付を通して所得が再分配されることはない。
    3  同一の所得階層内部での所得の移転を、垂直的な所得再分配という。
    4  積立方式による公的年金では、世代間の所得再分配が行われる。
    5  高所得者から低所得者への所得の移転を、水平的な所得再分配という。

問題30  次のうち、社会福祉法に設置根拠をもつものとして、正しいものを2つ選びなさい。
    1  地域包括支援センター
    2  母子家庭等就業・自立支援センター
    3  福祉に関する事務所（福祉事務所）
    4  運営適正化委員会
    5  要保護児童対策地域協議会

問題31  居住支援に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  住宅確保要配慮者居住支援協議会は、住宅確保要配慮者に対して家賃の貸付けを行っている。
    2  住居確保給付金は、収入が一定水準を下回る被用者に限定して、家賃を支給するものである。
    3  シルバーハウジングにおけるライフサポートアドバイザーは、身体介護を行うために配置されている。
    4  「住宅セーフティネット法」は、住宅確保要配慮者が住宅を購入するための費用負担についても定めている。
    5  地方公共団体は、公営住宅法に基づき、住宅に困窮する低額所得者を対象とする公営住宅を供給している。

    （注）  「住宅セーフティネット法」とは、「住宅確保要配慮者に対する賃貸住宅の供給の促進に関する法律」のことである。 

地域福祉の理論と方法

問題32  社会福祉協議会の歴史に関する次の記述のうち、正しいものを1つ選びなさい。
    1  1951年（昭和26年）に制定された社会福祉事業法で、市町村社会福祉協議会が法制化された。
    2  1962年（昭和37年）に社会福祉協議会基本要項が策定され、在宅福祉サービスを市町村社会福祉協議会の事業として積極的に位置づける方針が示された。
    3  1983年（昭和58年）に社会福祉事業法が一部改正され、都道府県社会福祉協議会を実施主体とする地域福祉権利擁護事業が開始された。
    4  1992年（平成4年）に新・社会福祉協議会基本要項が策定され、社会福祉協議会の活動原則として住民主体の原則が初めて位置づけられた。
    5  2000年（平成12年）に社会福祉法へ改正されたことにより、市町村社会福祉協議会の目的は地域福祉の推進にあることが明文化された。

問題33  地域福祉に関連する法律、事業に規定されている対象に関する次の記述のうち、正しいものを1つ選びなさい。
    1  ひきこもり支援推進事業の対象となるひきこもり状態にある者のひきこもりとは、「ひきこもりの評価・支援に関するガイドライン」によれば、原則的には2年以上家庭にとどまり続けていることをいう。
    2  ヤングケアラー支援体制強化事業におけるヤングケアラーとは、家族への世話などを日常的に行っている18歳から39歳までの者をいう。
    3  生活福祉資金の貸付対象における低所得世帯とは、資金の貸付けにあわせて必要な支援を受けることにより独立自活できると認められる世帯であって、必要な資金の融通を他から受けることが困難である者をいう。
    4  生活困窮者自立支援法における生活困窮者とは、最低限度の生活を維持できていない者をいう。
    5  日常生活自立支援事業の対象者とは、本事業の契約内容について理解できない者のうち、成年後見制度を利用していない者をいう。

    （注）  「ひきこもりの評価・支援に関するガイドライン」とは、厚生労働科学研究費補助金こころの健康科学研究事業（厚生労働省）においてまとめられたものである。

問題34  次の記述のうち、市町村地域福祉計画に関する社会福祉法の規定として、正しいものを1つ選びなさい。
    1  社会福祉を目的とする事業に従事する者の確保又は資質の向上に関する事項について定める。
    2  福祉サービスの適切な利用の推進及び社会福祉を目的とする事業の健全な発達のための基盤整備に関する事項について定める。
    3  地域における高齢者の福祉、障害者の福祉、児童の福祉その他の福祉に関し、共通して取り組むべき事項について定める。
    4  市町村地域福祉計画を定め、または変更しようとするときは、あらかじめ、都道府県の意見を聞かなければならない。
    5  市町村地域福祉計画の公表に当たって、市町村はその内容等について、都道府県の承認を受けなければならない。

問題35  社会福祉法に規定されている市町村による重層的支援体制整備事業に関する次の記述のうち、正しいものを1つ選びなさい。
    1  重層的支援体制整備事業は、地域生活課題の解決に資する包括的な支援体制を整備するための事業である。
    2  重層的支援体制整備事業は、市町村の必須事業である。
    3  市町村は、重層的支援体制整備事業の実施にあたって、包括的相談支援事業、参加支援事業、地域づくり事業のいずれか一つを選択して、実施することができる。
    4  重層的支援体制整備事業のうち、包括的相談支援事業は、住宅確保要配慮者に対する居住支援を行う事業である。
    5  市町村は、重層的支援体制整備事業実施計画を策定しなければならない。

問題36  地域福祉に係る組織、団体に関する現行法上の規定の内容として、最も適切なものを1つ選びなさい。
    1  特定非営利活動促進法において、特定非営利活動法人は、内閣府の認可により設立される。
    2  民生委員法において、民生委員協議会は、民生委員の職務に関して、関係各庁に意見を具申することができる。
    3  社会福祉法において、社会福祉法人は、社会福祉事業以外の事業を実施してはならない。
    4  保護司法において、保護司会連合会は、市町村ごとに組織されなければならない。
    5  社会福祉法において、市町村社会福祉協議会の役員には、関係行政庁の職員が5分の1以上就任しなければならない。

問題37  事例を読んで、生活困窮者自立相談支援事業のＢ相談支援員（社会福祉士）の支援方針として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｃさん（60歳）は、一人暮らしで猫を多頭飼育している。以前は近所付き合いがあったが今はなく、家はいわゆるごみ屋敷の状態である。Ｂ相談支援員は、近隣住民から苦情が出ていると民生委員から相談を受けた。そこでＢがＣさん宅を複数回訪問すると、Ｃさんは猫を可愛がっており、餌代がかかるため、自身の食事代を切り詰めて生活していることが分かった。Ｃさんは、今の生活で困っていることは特になく、近隣の苦情にどのように対応すればよいか分からない、と言っている。
    1  Ｃさんの衛生環境改善のため、市の清掃局にごみを強制的に回収してもらうことにする。
    2  Ｃさんの健康のため、保健所に連絡をして猫を引き取ってもらうことにする。
    3  Ｃさんの地域とのつながりを回復するため、苦情を言う住民も含めて、今後の関わり方を検討することにする。
    4  Ｃさんの主体性を尊重するため、Ｃさんに積極的に関わることを控えることにする。
    5  Ｃさんと地域とのコンフリクトを避けるため、引っ越しのあっせんを行うことにする。

問題38  地域福祉の財源に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  市区町村社会福祉協議会の平均財源構成比（2019年（平成31年））をみると、会費・共同募金配分金・寄付金を合計した財源の比率が最も高い。
    2  共同募金は、社会福祉を目的とする事業を経営する者以外にも配分できる。
    3  社会福祉法人による地域における公益的な取組とは、地元企業に投資し、法人の自主財源を増やしていくことである。
    4  個人又は法人が認定特定非営利活動法人に寄付をした場合は、税制上の優遇措置の対象となる。
    5  フィランソロピーとは、ＳＮＳなどを通じて、自らの活動を不特定多数に発信し寄附金を募る仕組みである。

問題39  事例を読んで、Ｎ市において地域福祉計画の策定を担当しているＤ職員（社会福祉士）が策定委員会での意見を踏まえて提案したニーズ把握の方法として、最も適切なものを1つ選びなさい。
〔事  例〕
地域福祉計画の改定時期を迎えたＮ市では、その見直しに向け策定委員会で協議を行った。委員の一人から、「子育て世代に向けた施策や活動が十分ではない」という提起があった。また、これに呼応して、「子育て世代といっても、様々な環境で子育てをしている人がいる」「まずは子育て中の人の生の声を実際に聞いた方がよい」といった意見に賛同が集まった。Ｄは、こうした声を踏まえて、どのように多様な子育て世代のニーズを把握すれば良いかについて考え、最も有効と思われる方法を策定委員会に提案した。
    1  Ｎ市の子育て支援課の職員（社会福祉士）を対象とした個別インタビュー
    2  子育て中の親のうち、世代や環境等の異なる親たちを対象としたグループインタビュー
    3  利用者支援事業の相談記録を対象とした質的な分析
    4  特定の小学校に通う子どもの保護者を対象とした座談会
    5  保育所を利用している全世帯を対象としたアンケート調査

問題40  事例を読んで、包括的な支援体制の構築に向けて、社会福祉協議会のＥ職員（社会福祉士）が行う支援の方針として、適切なものを2つ選びなさい。
〔事  例〕
Ｐ地区では、Ｑ国の外国人居住者が増加している。Ｆさんは、Ｑ国の外国人居住者のまとめ役を担っており、Ｅのところに相談に訪れた。Ｆさんは、日常会話程度の日本語は話せるが、日本の慣習に不慣れなために、過去に近隣住民とトラブルが生じてしまい、地域で気軽に相談できる日本人がいない。Ｆさんを含めて、Ｐ地区で暮らす外国人の多くが、地域活動にはあまり参加していない状態で、地域から孤立しているようである。Ｅは、このような外国人居住者の社会的孤立の問題を解決するための対策を検討した。
    1  Ｆさんらを講師として招き、地域で暮らす外国人居住者の暮らしや文化について、近隣住民が学ぶ機会を設ける。
    2  日本語が上達できるよう、Ｆさんに日本語の学習教材を提供する。
    3  外国人居住者が主体的に参加できるように、これまでの地域活動のあり方を見直す。
    4  近隣住民と再びトラブルが生じることを避けるため、自治会長に外国人居住者に対する生活指導を依頼する。
    5  外国人居住者に日本の文化や慣習を遵守させるため、地域のルールを作成する。

問題41  事例を読んで、Ａ市社会福祉協議会のＧ生活支援コーディネーター（社会福祉士）が提案する支援策等として、適切なものを2つ選びなさい。
〔事  例〕
Ａ市のＵボランティアグループのメンバーから地域の空き家を活用した活動をしたいという相談があった。そこでＧが「協議体」の会議で地区の民生委員に相談すると、その地区では外出せずに閉じこもりがちな高齢者が多いということであった。Ｇはグループのメンバーと相談し、そのような高齢者が自由に話のできる場にすることを目標に、週2回、通いの場を開設した。1年後、メンバーからは「顔馴染みの参加者は多くなったが、地域で孤立した高齢者が来ていない」という声が上がった。
    1  地域で孤立していると思われる高齢者が、通いの場になにを望んでいるかについて、地区の民生委員に聞き取り調査への協力を依頼する。
    2  通いの場に参加している高齢者に対して、活動の満足度を調査する。
    3  孤立した高齢者のための通いの場にするためにはなにが必要かについて「協議体」で議論する。
    4  孤立した高齢者が参加するという目標を、現在の活動に合ったものに見直す。
    5  孤立している高齢者向けに健康体操等の体を動かすプログラムを取り入れる。

    （注）  ここでいう「協議体」とは、介護保険制度の生活支援・介護予防サービスの体制整備に向けて、市町村が資源開発を推進するために設置するものである。 

福祉行財政と福祉計画

問題42  次のうち、法律で規定されている福祉計画の記述として、最も適切なものを1つ選びなさい。
    1  市町村障害者計画は、市町村が各年度における指定障害福祉サービスの種類ごとの必要な量の見込みについて定める計画である。
    2  都道府県子ども・若者計画は、都道府県が子どもの貧困対策について定める計画である。
    3  都道府県老人福祉計画は、都道府県が介護保険事業に係る保険給付の円滑な実施の支援について定める計画である。
    4  市町村地域福祉計画は、市町村が地域福祉の推進について市町村社会福祉協議会の地域福祉活動計画と一体的に定める計画である。
    5  市町村子ども・子育て支援事業計画は、市町村が教育・保育及び地域子ども・子育て支援事業の提供体制の確保について定める計画である。

問題43  次のうち、入所の仕組みを利用契約制度と措置制度に分けた場合、措置制度に分類されている施設として、適切なものを2つ選びなさい。
    1  軽費老人ホーム
    2  老人短期入所施設
    3  障害者支援施設
    4  児童養護施設
    5  救護施設

問題44  地方公共団体の事務に関する次の記述のうち、正しいものを1つ選びなさい。
    1  地方公共団体の事務は、自治事務、法定受託事務、団体委任事務、機関委任事務の4つに分類される。
    2  児童扶養手当の給付事務は、自治事務である。
    3  社会福祉法人の認可事務は、法定受託事務である。
    4  生活保護の決定事務は、団体委任事務である。
    5  児童福祉施設の監査事務は、機関委任事務である。

問題45  「令和5年版地方財政白書（令和3年度決算）」（総務省）に示された民生費に関する次の記述のうち、正しいものを1つ選びなさい。
    1  歳出純計決算額は、前年度に比べて減少した。
    2  目的別歳出の割合は、都道府県では社会福祉費よりも災害救助費の方が高い。
    3  目的別歳出の割合は、市町村では児童福祉費よりも老人福祉費の方が高い。
    4  性質別歳出の割合は、都道府県では繰出金よりも人件費の方が高い。
    5  性質別歳出の割合は、市町村では補助費等よりも扶助費の方が高い。

問題46  社会福祉に係る法定の機関に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  都道府県は、児童相談所を設置しなければならない。
    2  都道府県は、発達障害者支援センターを設置しなければならない。
    3  市町村は、保健所を設置しなければならない。
    4  市町村は、地方社会福祉審議会を設置しなければならない。
    5  市町村は、身体障害者更生相談所を設置しなければならない。

問題47  次のうち、現行法上、計画期間が3年を1期とすると規定されている計画として、正しいものを1つ選びなさい。
    1  市町村こども計画
    2  市町村介護保険事業計画
    3  市町村障害者計画
    4  市町村健康増進計画
    5  市町村地域福祉計画

問題48  次のうち、福祉計画を策定する際に用いられるパブリックコメントに関する記述として、最も適切なものを1つ選びなさい。
    1  行政機関が計画の素案を公表して広く意見や情報を募集する機会を設けることにより、人々の意見を計画に反映させる。
    2  特定のニーズに対応するサービスの種類と必要量を客観的に算出することにより、サービスの整備目標を算出する。
    3  専門家等に対して同じ内容のアンケート調査を繰り返し実施することにより、意見を集約していく。
    4  集団のメンバーが互いの知恵や発想を自由に出し合うことにより、独創的なアイデアを生み出す。
    5  意見やアイデアを記したカードをグループ化していくことにより、様々な情報を分類・整理していく。

社会保障

問題49  「国立社会保障・人口問題研究所の人口推計」に関する次の記述のうち、正しいものを1つ選びなさい。
    1  2020年から2045年にかけて、0～14歳人口は増加する。
    2  2020年から2045年にかけて、高齢化率は上昇する。
    3  2020年から2045年にかけて、15～64歳人口は増加する。
    4  65歳以上人口は、2045年には5,000万人を超えている。
    5  2020年から2045年にかけて、総人口は半減する。

    （注）  「国立社会保障・人口問題研究所の人口推計」とは、「日本の将来推計人口（令和5年推計）」の出生中位（死亡中位）の仮定の場合を指す。 

問題50  出産・育児に係る社会保障の給付等に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  「産前産後期間」の間は、国民年金保険料を納付することを要しない。
    2  出産育児一時金は、産前産後休業中の所得保障のために支給される。
    3  育児休業給付金は、最長で子が3歳に達するまで支給される。
    4  児童手当の費用は、国と地方自治体が折半して負担する。
    5  児童扶養手当の月額は、第1子の額よりも、第2子以降の加算額の方が高い。

    （注）  「産前産後期間」とは、国民年金の第1号被保険者の出産予定日又は出産日が属する月の前月から4か月間（多胎妊娠の場合は、出産予定日又は出産日が属する月の3月前から6か月間）を指す。 

問題51  社会保険の負担に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  国民年金の第1号被保険者の月々の保険料は、その月の収入に応じて決まる。
    2  介護保険の保険料は、都道府県ごとに決められる。
    3  後期高齢者医療の保険料は、全国一律である。
    4  障害基礎年金を受給しているときは、国民年金保険料を納付することを要しない。
    5  国民健康保険の保険料は、世帯所得にかかわらず、定額である。

問題52  事例を読んで、Ｈさんに支給される社会保障給付として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｈさん（45歳）は、妻と中学生の子との3人家族だったが、先日、妻が業務上の事故によって死亡した。Ｈさんは、数年前に、持病のためそれまで勤めていた会社を退職し、それ以来、無職、無収入のまま民間企業で働く妻の健康保険の被扶養者になっていた。
    1  国民年金法に基づく死亡一時金
    2  厚生年金保険法に基づく遺族厚生年金
    3  国民年金法に基づく遺族基礎年金
    4  健康保険法に基づく埋葬料
    5  労働者災害補償保険法に基づく傷病補償年金

問題53  労働保険に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  労働者災害補償保険の療養補償給付を受ける場合、自己負担は原則1割である。
    2  労働者災害補償保険は、政府が管掌する。
    3  日雇労働者は、雇用保険の適用除外とされている。
    4  雇用保険の失業等給付の保険料は、その全額を事業主が負担する。
    5  教育訓練給付は、雇用保険の被保険者ではなくなった者には支給されない。

問題54  事例を読んで、障害者の所得保障制度に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ｊさんは、以前休日にオートバイを運転して行楽に出かける途中、誤ってガードレールに衝突する自損事故を起こし、それが原因で、その時から障害基礎年金の1級相当の障害者となった。現在は30歳で、自宅で電動車いすを利用して暮らしている。
    1  Ｊさんの障害の原因となった事故が17歳の時のものである場合は、20歳以降に障害基礎年金を受給できるが、Ｊさんの所得によっては、その一部又は全部が停止される可能性がある。
    2  Ｊさんの障害の原因となった事故が25歳の時のものであった場合は、年金制度への加入歴が定められた期間に満たないので、障害基礎年金を受給できない。
    3  Ｊさんの障害の原因となった事故が雇用労働者であった時のものである場合は、労働者災害補償保険の障害補償給付を受けられる。
    4  Ｊさんに未成年の子がある場合は、Ｊさんは特別障害者手当を受給できる。
    5  Ｊさんが障害の原因となった事故を起こした時に、健康保険の被保険者であった場合は、給与の全額に相当する傷病手当金を継続して受給することができる。

問題55  老齢基礎年金に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  老齢基礎年金は、受給者の選択により55歳から繰り上げ受給をすることができる。
    2  老齢基礎年金は、保険料納付済期間が25年以上なければ、受給することができない。
    3  老齢基礎年金と老齢厚生年金は、どちらか一方しか受給することができない。
    4  老齢基礎年金は、支給開始時に決められた額が死亡時まで変わらずに支給される。
    5  老齢基礎年金の年金額の算定には、保険料免除を受けた期間の月数が反映される。

障害者に対する支援と障害者自立支援制度

問題56  障害者等の法律上の定義に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  「障害者虐待防止法」における障害者とは、心身の機能の障害がある者であって、虐待を受けたものをいう。
    2  「障害者総合支援法」における障害者の定義では、難病等により一定の障害がある者を含む。
    3  知的障害者福祉法における知的障害者とは、知的障害がある者であって、都道府県知事から療育手帳の交付を受けたものをいう。
    4  発達障害者支援法における発達障害者とは、発達障害がある者であって、教育支援を必要とするものをいう。
    5  児童福祉法における障害児の定義では、障害がある者のうち、20歳未満の者をいう。

    （注）1  「障害者虐待防止法」とは、「障害者虐待の防止、障害者の養護者に対する支援等に関する法律」のことである。
        2  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。 

問題57  障害者福祉制度の発展過程に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  1949年（昭和24年）に制定された身体障害者福祉法では、障害者福祉の対象が生活困窮者に限定された。
    2  1987年（昭和62年）に精神衛生法が精神保健法に改正され、保護者制度が廃止された。
    3  2004年（平成16年）に改正された障害者基本法では、障害者に対する差別の禁止が基本理念として明文化された。
    4  2005年（平成17年）に制定された障害者自立支援法では、利用者負担は所得に応じた応能負担が原則となった。
    5  2011年（平成23年）に障害者基本法が改正され、法律名が心身障害者対策基本法に改められた。

問題58  「障害者総合支援法」における指定特定相談支援事業所の相談支援専門員の役割に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  障害福祉サービスを利用する障害者等に対して、サービス等利用計画案を作成する。
    2  障害福祉サービスを利用する障害者等に対して個別支援計画を作成し、従業者に対して、技術指導、助言を行う。
    3  障害福祉サービスを利用する障害者等に対して、居宅において入浴、排せつ又は食事の介護等を行う。
    4  一般就労を希望する障害者に対して、就業面と生活面の一体的な相談、支援を行う。
    5  障害福祉サービスを利用する障害者等に対して、支給決定を行う。

問題59  「障害者総合支援法」による自立支援医療に関する次の記述のうち、正しいものを1つ選びなさい。
    1  自立支援医療の種類には、更生医療が含まれる。
    2  自立支援医療の種類にかかわらず、支給認定は都道府県が行う。
    3  利用者の自己負担割合は、原則として3割である。
    4  精神通院医療では、精神障害者保健福祉手帳の所持者以外は支給対象とならない。
    5  利用者は、自立支援医療を利用する場合には、自由に医療機関を選択できる。

問題60  事例を読んで、Ｖ相談支援事業所のＫ相談支援専門員がこの段階で紹介する障害福祉サービスとして、最も適切なものを1つ選びなさい。
〔事  例〕
Ｌさん（30歳、統合失調症）は、週1回の精神科デイケアを利用している。Ｌさんは、過去に何度かアルバイトをしたことはあるが、症状の再燃により、短期間で辞めていた。最近になって、症状が改善し、生活リズムも安定したことから、将来を見据えて一般就労を希望するようになった。ただし、自分の能力や適性がわからないため、不安が強い。Ｌさんの相談を受けたＫ相談支援専門員は、障害福祉サービスを紹介することにした。
    1  就労継続支援Ａ型
    2  就労継続支援Ｂ型
    3  就労移行支援
    4  就労定着支援
    5  職場適応援助者（ジョブコーチ）

問題61  「障害者総合支援法」における障害支援区分に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  障害支援区分に係る一次判定の認定調査の項目は全国一律ではなく、市町村独自の項目を追加してもよい。
    2  障害支援区分の認定は、都道府県が行うものとされている。
    3  市町村は、認定調査を医療機関に委託しなければならない。
    4  障害支援区分として、区分1から区分6までがある。
    5  就労継続支援Ａ型に係る支給決定においては、障害支援区分の認定を必要とする。

問題62  事例を読んで、Ｍ相談支援専門員（社会福祉士）がこの段階で行う支援として、適切なものを2つ選びなさい。
〔事  例〕
軽度の知的障害があるＡさん（22歳）は、両親と実家で暮らしている。特別支援学校高等部を卒業後、地元企業に就職したが職場に馴染｛なじ｝めず3か月で辞めてしまい、その後、自宅に引きこもっている。最近、Ａさんは学校時代の友人が就労継続支援Ｂ型を利用していると聞き、福祉的就労に関心を持ち始めた。Ａさんと両親は、市の相談窓口で紹介されたＷ基幹相談支援事業所に行き、今後についてＭ相談支援専門員に相談した。
    1  友人と自分を比べると焦りが生じるため、自身の将来に集中するように助言する。
    2  一般企業で働いた経験があるので、再度、一般就労を目指すよう励ます。
    3  地域にある就労継続支援Ｂ型の体験利用をすぐに申し込むよう促す。
    4  Ａさん自身がどのような形の就労を望んでいるかＡさんの話を十分に聞く。
    5  Ａさんの日常生活の状況や就労の希望について、両親にも確認する。

低所得者に対する支援と生活保護制度

問題63  生活保護法に関する次の記述のうち、正しいものを2つ選びなさい。
    1  保護が実施機関の職権によって開始されることはない。
    2  保護は、生活困窮に陥った原因に基づいて決定される。
    3  最低限度の生活を保障することを目的としている。
    4  自立の見込みがあることを要件として、保護を受けることができる。
    5  自立を助長することを目的としている。

問題64  事例を読んで、生活保護法の定める内容に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
単身で2ＬＤＫの賃貸マンション暮らしのＢさん（44歳）は、建設業に従事していたが半年前に自宅で骨折をして仕事を続けられなくなり、退職した。Ｂさんには遠く離れた故郷に父親（75歳）がいるが、父親も生活に余裕がない。Ｂさんは生活費が底をつき、生活保護を受給し、リハビリに励むこととなった。その後Ｂさんはリハビリが終わり、医師から軽労働なら就労できる状態だと診断された。求職活動をしたものの、年齢や技能の関係で仕事は見つかっていない。そこでＢさんは今よりもう少し安い家賃のアパートに移ろうかと考えている。
    1  就労に必要な技能修得の費用が生業扶助から支給される。
    2  アパートに転居する際の敷金が生活扶助から支給される。
    3  父親から仕送りを受けると、その金額の多寡にかかわらず保護は廃止される。
    4  医師から就労できる状態だと診断された時点で、保護は廃止される。
    5  父親は後期高齢者であるため、Ｂさんを扶養する義務はない。

問題65  生活保護の種類と内容に関する次の記述のうち、正しいものを1つ選びなさい。
    1  生活扶助の第1類の経費は、世帯共通の費用とされている。
    2  住宅扶助には、住宅の補修その他住宅の維持のために必要な経費が含まれる。
    3  介護扶助には、介護保険の保険料が含まれる。
    4  医療扶助によって、入院中の被保護者に対して入院患者日用品費が支給される。
    5  出産扶助は、原則として現物給付によって行われる。

問題66  生活保護制度における都道府県及び都道府県知事の役割や権限に関する次の記述のうち、正しいものを1つ選びなさい。
    1  都道府県は、福祉事務所を任意に設置できる。
    2  都道府県知事は、地域の実情を踏まえて生活保護法上の保護基準を変更することができる。
    3  都道府県は、町村が福祉事務所を設置する場合、その保護費の一部を負担する。
    4  都道府県知事は、保護施設の設備及び運営について、基準を定めるよう努めることとされている。
    5  都道府県知事は、生活保護法に定めるその職権の一部を、その管理に属する行政庁に委任することができる。

問題67  事例を読んで、Ｃさんが生活福祉資金貸付制度を利用する場合の内容に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ｃさん（50歳）は、Ｒ市で一人暮らしをしていたが、会社が倒産し、無職となった。雇用保険（基本手当）の給付を受けていたが、受給期間終了後も再就職先が見つからず、生活が苦しくなったので生活福祉資金貸付制度の総合支援資金を利用したいと思い、Ｒ市の社会福祉協議会に相談に訪れた。
    1  貸付を受けるためには、連帯保証人が必須となる。
    2  貸付金の償還が免除されることはない。
    3  離職理由によって、最終貸付日から返済が開始されるまでの据置期間が異なる。
    4  借入れの申込み先は、Ｒ市の福祉事務所である。
    5  資金の貸付けを受ける場合には、必要な相談支援を受けることが求められる。

問題68  事例を読んで、生活困窮者自立相談支援機関のＤ相談支援員（社会福祉士）が提案する自立支援計画案の内容に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ｅさん（50歳）は、実家で両親と3人暮らしである。両親はともに80代で、実家は持ち家だが他に資産はなく、一家は両親の老齢基礎年金で生活している。Ｅさんは大学卒業後、出身地の会社に就職したが人間関係がこじれて5年前に退職し、その後は定職に就かず、実家でひきこもり状態である。Ｅさんの状況を両親が心配し、またＥさん自身もこの状況をどうにかしたいと考えて、Ｅさんは両親とともに生活困窮者自立相談支援機関に来所した。Ｄ相談支援員は、アセスメントを経て、Ｅさんに今後の支援内容を提案した。
    1  社会福祉協議会での被保護者就労支援事業の利用
    2  公共職業安定所（ハローワーク）での生活困窮者就労準備支援事業の利用
    3  認定事業者での生活困窮者就労訓練の利用
    4  地域若者サポートステーションでの「求職者支援制度」の利用
    5  生活保護法に基づく授産施設の利用

    （注）  「求職者支援制度」とは、職業訓練の実施等による特定求職者の就職に関する法律（求職者支援法）に基づく制度のことである。 

問題69  「ホームレスの実態に関する全国調査」（厚生労働省）に関する次の記述のうち、正しいものを1つ選びなさい。
    1  概数調査によれば、全国のホームレス数は2022年に比べて増加している。
    2  概数調査によれば、性別人数では男性より女性が多数を占めている。
    3  生活実態調査によれば、ホームレスの平均年齢は2016年調査に比べて低下している。
    4  生活実態調査によれば、路上生活期間「10年以上」は2016年調査に比べて増加している。
    5  生活実態調査によれば、「生活保護を利用したことがある」と回答した人は全体の約7割程度である。

    （注）  「ホームレスの実態に関する全国調査」（厚生労働省）とは、「ホームレスの実態に関する全国調査（概数調査）」（2023年（令和5年））及び「ホームレスの実態に関する全国調査（生活実態調査）」（2021年（令和3年））を指している。 

保健医療サービス

問題70  公的医療保険における一部負担金に関する次の記述のうち、正しいものを1つ選びなさい。
    1  療養の給付に要した費用の一部負担金の割合は、一律3割である。
    2  被用者保険に加入中の生活保護の被保護者は、一部負担金のみが医療扶助の対象となる。
    3  正常な分娩｛ぶんべん｝による出産費用の一部負担金の割合は、3割である。
    4  1か月の医療費の一部負担金が限度額を超えた場合、保険外併用療養費制度により払戻しが行われる。
    5  入院時の食事提供の費用は、全額自己負担である。

問題71  「令和2（2020）年度国民医療費の概況」（厚生労働省）に示された日本の医療費に関する次の記述のうち、正しいものを1つ選びなさい。
    1  国民医療費の総額は40兆円を超えている。
    2  人口一人当たりの国民医療費は60万円を超えている。
    3  国民医療費に占める薬局調剤医療費の割合は、入院医療費の割合よりも高い。
    4  国民医療費の財源に占める公費の割合は、保険料の割合よりも高い。
    5  国民医療費に占める歯科診療医療費の割合は、入院外医療費の割合より高い。

問題72  診療報酬に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  診療報酬の請求は、各月分について行わなければならない。
    2  請求された診療報酬は、中央社会保険医療協議会が審査する。
    3  医療機関が診療報酬を請求してから報酬を受け取るまで約6か月掛かる。
    4  診療報酬点数表には、医科、歯科、高齢の点数表がある。
    5  診療報酬点数は、1点の単価が1円とされている。

問題73  医療法に基づく医療計画に関する次の記述のうち、正しいものを1つ選びなさい。
    1  国が、地域の実情に合わせて策定することになっている。
    2  医療提供体制の確保を図るためのものである。
    3  医療圏は、一次医療圏と二次医療圏の2つから構成されている。
    4  病院の定義や人員、設備の基準を定めることになっている。
    5  2年ごとに見直される。

問題74  訪問看護に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  訪問看護は、看護師の指示で訪問看護サービスを開始する。
    2  訪問看護ステーションには、栄養士を配置しなければならない。
    3  訪問看護の対象は、65歳以上の者に限定されている。
    4  訪問看護ステーションの管理者は、医師でなければならない。
    5  訪問看護は、居宅において看護師等により行われる療養上の世話又は必要な診療の補助を行う。

問題75  次の事例を読んで、医療ソーシャルワーカー（社会福祉士）が紹介した現時点で利用可能な制度として、適切なものを2つ選びなさい。
〔事  例〕
入院中のＦさん（39歳、会社員）は、大学卒業後から継続して協会けんぽ（全国健康保険協会管掌健康保険）の被保険者であり、同じ会社の正社員である妻35歳と息子7歳との3人暮らしである。20代より生活習慣病を患い、保健指導と治療がなされたが行動変容は難しかった。Ｆさんは、3日前に糖尿病性腎症による人工透析導入のため入院することとなった。医師からは、約1か月間の入院となり、退院後は週に3日の継続的な透析治療が必要との説明を受けた。Ｆさんは、仕事は継続したいが、医療費や入院期間中の収入面の不安を訴えたことから、医師より医療ソーシャルワーカーを紹介された。
    1  生活保護制度
    2  労働者災害補償保険制度
    3  高額療養費制度
    4  傷病手当金制度
    5  雇用保険制度

問題76  「人生の最終段階における医療・ケアの決定プロセスに関するガイドライン（2018年（平成30年）改訂版）」（厚生労働省）に沿った対応の方針として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｇさん（72歳）は、妻（70歳）と二人暮らし。10年前より筋萎縮性側索硬化症（ＡＬＳ）と診断を受け、在宅で療養を続けてきた。診断を受けた当初、「人工呼吸器は装着せずに、自宅で自然な状態で最期を迎えたい」と言っていた。1か月前から言語の表出、自発呼吸が困難となり、人工呼吸器の装着について検討することとなった。
    1  診断を受けた当初のＧさんの意思を優先する。
    2  Ｇさんに代わって、妻の判断を優先する。
    3  Ｇさん、家族、医療・ケアチームによる話し合いの場を設定する。
    4  家庭裁判所に判断を求める。
    5  医師の医学的判断により決定する。

権利擁護と成年後見制度

問題77  次のうち、日本国憲法における社会権として、正しいものを2つ選びなさい。
    1  財産権
    2  肖像権
    3  教育を受ける権利
    4  団体交渉権
    5  自己決定権

問題78  事例を読んで、Ｈの相続における法定相続分に関する次の記述のうち、正しいものを1つ選びなさい。
〔事  例〕
Ｈは、多額の財産を遺して死亡した。Ｈの相続人は、配偶者Ｊ、子のＫ・Ｌ・Ｍ、Ｈよりも先に死亡した子Ａの子（Ｈの孫）であるＢ・Ｃの計6人である。なお、Ｌは養子であり、Ｍは非嫡出子である。Ｈは生前にＭを認知している。
    1  配偶者Ｊの法定相続分は3分の1である。
    2  子Ｋの法定相続分は6分の1である。
    3  養子Ｌの法定相続分は7分の1である。
    4  非嫡出子Ｍの法定相続分は8分の1である。
    5  孫Ｂの法定相続分は7分の1である。

問題79  遺言に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  成年被後見人は、事理弁識能力が一時回復した時であっても遺言をすることができない。
    2  自筆証書遺言を発見した相続人は、家庭裁判所の検認を請求しなければならない。
    3  公正証書によって遺言をするには、遺言者がその全文を自書しなければならない。
    4  自筆証書によって遺言をするには、証人2人以上の立会いがなければならない。
    5  遺言に相続人の遺留分を侵害する内容がある場合は、その相続人の請求によって遺言自体が無効となる。

問題80  事例を読んで、Ｄさんについての後見開始の審判をＥさんが申し立てた主な理由として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｄさん（80歳）は、子のＥさんが所有する建物に居住していたが、認知症のため、現在は指定介護老人福祉施設に入所している。Ｄさんの年金だけでは施設利用料の支払いが不足するので、不足分はＥさんの預金口座から引き落とされている。施設で安定した生活を営んでいるものの医師からは白内障の手術を勧められている。近時、Ｄさんの弟であるＦさんが多額の財産を遺して亡くなり、Ｄさんは、Ｄさんの他の兄弟とともにＦさんの財産を相続することとなった。Ｅさんは、家庭裁判所に対しＤさんについて後見を開始する旨の審判を申し立てた。
    1  Ｄさんの手術についての同意
    2  Ｄさんが入所する指定介護老人福祉施設との入所契約の解約
    3  Ｄさんが参加するＦさんについての遺産分割協議
    4  Ｄさんが入所前に居住していたＥさん所有の建物の売却
    5  Ｄさんの利用料不足分を支払っているＥさんの預金の払戻し

問題81  事例を読んで、Ｇさんの成年後見監督人に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
知的障害のあるＧさん（30歳）は、兄であるＨさんが成年後見人に選任され支援を受けていた。しかし、数年後にＧさんとＨさんの関係が悪化したため、成年後見監督人が選任されることとなった。
    1  Ｇさんは、成年後見監督人の選任請求を家庭裁判所に行うことができない。
    2  Ｈさんの妻は、Ｈさんの成年後見監督人になることができる。
    3  ＧさんとＨさんに利益相反関係が生じた際、成年後見監督人はＧさんを代理することができない。
    4  成年後見監督人は、Ｈさんが成年後見人を辞任した場合、成年後見人を引き継がなければならない。
    5  成年後見監督人は、ＧさんとＨさんの関係がさらに悪化し、Ｈさんが後見業務を放置した場合、Ｈさんの解任請求を家庭裁判所に行うことができる。

問題82  次のうち、「成年後見関係事件の概況（令和4年1月～12月）」（最高裁判所事務総局家庭局）に示された「成年後見人等」に選任された最も多い者として、正しいものを1つ選びなさい。
    1  親族
    2  弁護士
    3  司法書士
    4  社会福祉士
    5  市民後見人

    （注）  「成年後見人等」とは、成年後見人、保佐人及び補助人のことである。 


第36回（令和5年度）社会福祉士国家試験午後の問題
社会調査の基礎

問題84  次のうち、統計法における基幹統計調査として、正しいものを1つ選びなさい。
    1  社会福祉施設等調査
    2  福祉行政報告例
    3  介護サービス施設・事業所調査
    4  労働安全衛生調査
    5  国民生活基礎調査

問題85  社会調査における倫理に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  社会調査の対象者の抽出では、住民基本台帳から制約なく個人情報を閲覧できる。
    2  調査の協力は自由意志であるので、対象者への調査に関する説明は不要である。
    3  社会調査では、対象者に調査協力の謝礼を渡すことが不可欠である。
    4  調査前に対象者の協力同意書があっても、調査の途中又は調査後の対象者からのデータ削除要請に応じることが求められる。
    5  仮説に反した調査結果が出た場合、調査結果の公表を差し控える必要がある。

問題86  次の事例を読んで、Ｓ県が実施した標本調査の母集団として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｓ県内の高校に在籍している全ての生徒のうち、日常的に家族の世話や介護等を担っている高校生が、どのくらい存在するかを調べるために、標本調査を実施した。
    1  全国の高校に在籍する全生徒
    2  全国の高校に在籍する全生徒のうち、日常的に家族の世話や介護等を担っている者
    3  Ｓ県内の高校に在籍する全生徒
    4  Ｓ県内の高校に在籍する全生徒のうち、日常的に家族の世話や介護等を担っている者
    5  Ｓ県内の高校に在籍する全生徒のうち、標本となった者

問題87  次のうち、質問への回答を他計式で記入する社会調査として、適切なものを2つ選びなさい。
    1  郵送調査
    2  留置調査
    3  個別面接調査
    4  集合調査
    5  オペレーターによる電話調査

問題88  尺度に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  比例尺度では、平均値を算出することができる。
    2  順序尺度で測定した1と2の差と、3と4の差の等間隔性は担保されている。
    3  名義尺度で測定した変数は、中央値を求めることができる。
    4  間隔尺度では、測定値の間隔が数値として意味をもつことはない。
    5  名義尺度、間隔尺度、順序尺度、比例尺度の順で、尺度としての水準が高い。

問題89  調査手法としての面接法に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  構造化面接では、対象者に語りたいことを自由に話してもらうことが重要である。
    2  非構造化面接では、調査者は事前に10項目以上の質問項目と質問の順番を設定し、その順番どおりに質問していく必要がある。
    3  半構造化面接では、インタビューのおおむね半分程度の時間を、質問内容や質問の順番などが詳細に決められた質問紙によって面接が進められる。
    4  面接調査では、表情や身振りといった非言語表現も重視する。
    5  グループ・インタビューの調査者は、対象者同士の会話を促さないようにする。

問題90  社会調査における記録の方法とデータ収集法に関する次の記述のうち、適切なものを2つ選びなさい。
    1  質的調査で対象者を選定するときには、無作為抽出法を行うことが不可欠である。
    2  アクションリサーチでは、量的調査でデータを収集することがある。
    3  ドキュメント分析の対象となるデータには、手紙や日記などの私的文章も含まれる。
    4  質的調査のデータとしては、画像や映像の使用を避ける方が望ましい。
    5  フィールドノーツは、調査者の解釈を含めずに作成する必要がある。

相談援助の基盤と専門職

問題91  社会福祉士及び介護福祉士法における社会福祉士の義務等に関連する次の記述のうち、正しいものを1つ選びなさい。
    1  後継者の育成に努めなければならない。
    2  秘密保持義務として、その業務に関して知り得た人の秘密は、いかなる理由があっても開示してはならない。
    3  社会福祉士の信用を傷つけるような行為を禁じている。
    4  社会福祉士ではなくとも、その名称を使用できる。
    5  誠実義務の対象は、福祉サービスを提供する事業者とされている。

問題92  次の事例を読んで、福祉事務所に勤務するＫ職員（社会福祉士）が取り組む様々な対応のうち、メゾレベルの対応として、適切なものを2つ選びなさい。
〔事  例〕
Ｌ民生委員は、Ｍさん（45歳）の件で市の福祉事務所を訪れ、Ｋに相談をした。Ｍさんは勤め先を3年前に人員整理で解雇されてからは仕事をせず、親が残してくれた自宅で一人、昼夜逆転の生活をしているとのことであった。現時点では、Ｍさんには緊急の要保護性は感じられないが、仕事をしておらず、生活費が底をつく心配がある。Ｍさんは「今すぐに仕事をする自信はないが、今後に備えて相談をしたい」と望んでおり、Ｍさんの了解のもとに相談に訪れたとのことであった。
    1  中高年を対象とする就労支援制度の課題を、所属機関を通して国に提示する。
    2  相談意欲のあるＭさんと相談援助の関係を樹立する。
    3  Ｍさんに対して、生活費を確保するために、不動産担保型生活資金を検討するよう勧める。
    4  市内の事業所に対して、Ｍさんのような中高年者が利用可能な自立相談支援に関する事業の実施状況の情報を収集する。
    5  Ｌ民生委員からの情報をもとに、同様の事例に関する今後の支援について、所内で検討する。

問題93  「ソーシャルワーク専門職のグローバル定義」（2014年）に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  人間尊重、人間の社会性、変化の可能性の3つの価値を前提とした活動である。
    2  人、問題、場所、過程を構成要素とする。
    3  価値の体系、知識の体系、調整活動のレパートリーを本質的な要素とする。
    4  ソーシャルワーク実践は、価値、目的、サンクション、知識及び方法の集合体である。
    5  社会変革と社会開発、社会的結束、および人々のエンパワメントと解放を促進する。

    （注）  「ソーシャルワーク専門職のグローバル定義」とは、2014年7月の国際ソーシャルワーカー連盟（ＩＦＳＷ）と国際ソーシャルワーク学校連盟（ＩＡＳＳＷ）の総会・合同会議で採択されたものを指す。 

問題94  障害者の自立生活運動に関する次の記述のうち、適切なものを2つ選びなさい。
    1  当事者が人の手を借りずに、可能な限り自分のことは自分ですることを提起している。
    2  ピアカウンセリングを重視している。
    3  施設において、管理的な保護のもとでの生活ができることを支持している。
    4  当事者の自己決定権の行使を提起している。
    5  危険に挑む選択に対して、指導し、抑止することを重視している。

問題95  ソーシャルワークを発展させた人物に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  レヴィ（Levy, C.）は、倫理とは、人間関係とその交互作用に対して価値が適用されたものであるとした。
    2  トール（Towle, C.）は、ジェネラリストの観点からソーシャルワークの統合化を図り、ジェネラリスト・ソーシャルワークを提唱した。
    3  アプテカー（Aptekar, H.）は、相互連結理論アプローチを提唱し、それぞれの理論は相互に影響を及ぼし合い、結びついていると論じた。
    4  ジョンソン（Johnson, L.）は、社会的目標を達成するために不可欠な要素として、4つの基本的ニーズを提示した。
    5  ターナー（Turner, F.）は、機能主義の立場に立ちつつ、診断主義の理論を積極的に取り入れ、ケースワークとカウンセリングを区別した。

問題96  事例を読んで、Ｘ小学校に配置されているＡスクールソーシャルワーカー（社会福祉士）が、Ｂさんの意思を尊重することに対する倫理的ジレンマとして、適切なものを2つ選びなさい。
〔事  例〕
Ａは、2学期に入ったある日、暗い顔をしているＢさん（小学5年生）に声をかけた。Ｂさんは、初めは何も語らなかったが、一部の同級生からいじめを受けていることを少しずつ話し出した。そして、「今話していることが知られたら、ますますいじめられるようになり、学校にいづらくなる。いじめられていることは、自分が我慢すればよいので、他の人には言わないで欲しい」と思いつめたような表情で話した。
    1  クライエントの保護に関する責任
    2  別の小学校に配置されているスクールソーシャルワーカーに報告する責任
    3  学校に報告する責任
    4  保護者会に報告する責任
    5  いじめている子の保護者に対する責任

問題97  次の事例の場面において、複数のシステムの相互作用をもたらすシュワルツ（Schwartz, W.）の媒介機能を意図した支援として、最も適切なものを1つ選びなさい。
〔事  例〕
自閉傾向のあるＣさん（10歳）の母親が、市の子育て支援課の窓口に久しぶりに相談に来た。Ｄ相談員（社会福祉士）がＣさんについて、この間の様子を聞いたところ、言語的なコミュニケーションは少ないが、最近は絵を描くことが好きになってきたとのことであった。
    1  次回面接では親子で来所することと、Ｃさんの描いた絵を持ってくるよう依頼した。
    2  親子で共通する話題や目的をつくるために、市主催のアートコンクールに出展する絵を描くよう勧めた。
    3  絵によるコミュニケーションカードを親子で作成し、日常生活で使うよう勧めた。
    4  市内にある大きな文房具店を紹介し、親子で一緒に絵を描く道具を見に行くことを勧めた。
    5  障害児と親が活発に参加している絵画サークルに親子で参加し、児童や親達と交流することを勧めた。

相談援助の理論と方法

問題98  ソーシャルワーク実践におけるシステム理論の考え方に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  ピンカス（Pincus, A.）とミナハン（Minahan, A.）の実践モデルにおけるターゲットシステムは、目標達成のために、ソーシャルワーカーと協力していく人々を指す。
    2  開放システムの変容の最終状態は、初期条件によって一義的に決定される。
    3  システムには、他の要素から正負のフィードバックを受けることで、自己を変化・維持させようとする仕組みがある。
    4  クライエントの生活上の問題に関し、問題を生じさせている原因と結果の因果関係に着目する。
    5  家族の問題に対して、課題を個々の家族員の次元で捉え、個々人に焦点を当てたサービスを提供する。

問題99  ソーシャルワークの実践モデルに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  生活モデルは、問題を抱えるクライエントの人格に焦点を絞り、問題の原因究明を重視する。
    2  生活モデルは、人と環境の交互作用に焦点を当て、人の生活を全体的視点から捉える。
    3  治療モデルは、人が疎外される背景にある社会の抑圧構造に注目する。
    4  治療モデルは、問題を抱えるクライエントのもつ強さ、資源に焦点を当てる。
    5  ストレングスモデルは、クライエントの病理を正確に捉えることを重視する。

問題100  ソーシャルワークのアプローチに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  機能的アプローチでは、4つのＰを実践の構成要素として、クライエントのコンピテンス、動機づけとワーカビリティを高めることを目指す。
    2  問題解決アプローチでは、女性にとっての差別や抑圧などの社会的現実を顕在化させ、個人のエンパワメントと社会的抑圧の根絶を目指す。
    3  ユニタリーアプローチでは、ソーシャルワーカーが所属する機関の機能と専門職の役割機能の活用を重視し、クライエントのもつ意志の力を十分に発揮できるよう促すことを目指す。
    4  実存主義アプローチでは、クライエントが自我に囚われた状態から抜け出すために、他者とのつながりを形成することで、自らの生きる意味を把握し、疎外からの解放を目指す。
    5  フェミニストアプローチでは、システム理論に基づいて問題を定義し、ソーシャルワーカーのクライエントに対する教育的役割を重視し、段階的に目的を達成することを目指す。

問題101  事例を読んで、就労継続支援Ｂ型事業所のＥ職員（社会福祉士）が、クライエントに危険が及ぶような行動を減らすために、行動変容アプローチを応用して行う対応として、最も適切なものを1つ選びなさい。
〔事  例〕
知的障害があるＦさん（20歳）は、作業中に興味があるものが目に入ると勢いよく外に飛び出してしまうことや、作業時間中でも床に寝転がること等の行動が度々あった。寝転がっているところに起き上がるよう声かけを行うと、引っ張り合いになっていた。Ｆさんのこれらの行動は、職員や仲間からの注目・関心を集めていた。そこで、Ｅは、Ｆさんが席に座って作業を継続することを目標行動にして支援を開始した。
    1  Ｆさんが何かに気を取られて席を立つたびに、報酬を与える。
    2  支援を始めて1か月後に、目標行動の変化を評価しベースラインをつける。
    3  不適切行動のモデリングとして、職員が寝転がって見せる。
    4  作業が継続できるたびにベルを鳴らし、ベルの音と作業を条件づける。
    5  寝転がる前の先行条件、寝転がった後の結果といった行動の仕組みを分析する。

問題102  事例を読んで、乳児院のＧ家庭支援専門相談員（社会福祉士）が活用するアセスメントツールに関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
一人暮らしのＨさんは、慢性疾患による入退院を繰り返しながら出産したが、直後に長期の入院治療が必要となり、息子は乳児院に入所となった。Ｈさんは2か月前に退院し、職場にも復帰したので、息子と一緒に暮らしたいとＧに相談した。ただ、「職場の同僚ともうまくいかず、助けてくれる人もいないので、一人で不安だ」とも話した。そこでＧは、引き取りに向けて支援するため、アセスメントツールを活用することにした。
    1  同僚との関係を整理するために、ジェノグラムを作成する。
    2  息子の発育状況を整理するために、エコマップを作成する。
    3  周囲からのサポートを整理するために、エコマップを作成する。
    4  自宅周辺の生活環境を整理するために、ソシオグラムを作成する。
    5  Ｈさんの病状を整理するために、ソシオグラムを作成する。

問題103  ソーシャルワークのプランニングにおける、目標の設定とクライエントの意欲に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  ソーシャルワーカーが、独自の判断で高い目標を設定すると、クライエントの意欲は高まる。
    2  クライエントが自分でもできそうだと思う目標を段階的に設定すると、クライエントの意欲は低下する。
    3  クライエントが具体的に何をすべきかがわかる目標を設定すると、クライエントの意欲が高まる。
    4  クライエントにとって興味がある目標を設定すると、クライエントの意欲は低下する。
    5  最終的に実現したい生活像とは切り離して目標を設定すると、クライエントの意欲が高まる。

問題104  次の事例は、在宅療養支援におけるモニタリングの段階に関するものである。この段階におけるＪ医療ソーシャルワーカー（社会福祉士）の対応として、適切なものを2つ選びなさい。
〔事  例〕
Ｋさん（60歳）は、呼吸器機能に障害があり病院に入院していたが、退院後には自宅で在宅酸素療法を行うことになった。Ｋさんとその夫は、在宅療養支援診療所のＪと話し合いながら、訪問診療、訪問看護、訪問介護等を導入して自宅療養体制を整えた。療養開始後1か月が経ち、Ｊはモニタリングを行うことにした。
    1  Ｋさんに「自宅での療養で困っていることはありますか」と聞き、新たな要望やニーズの有無を確認する。
    2  Ｋさんの夫に「病気になる前はどのように暮らしていましたか」と聞き、Ｋさんの生活歴を確認する。
    3  訪問介護員に「医療上、何かすべきことはありますか」と医療的ケアの課題を確認する。
    4  主治医に「入院前の病状はいかがでしたか」と過去の治療状況を確認する。
    5  訪問看護師に「サービス実施状況はどうですか」と経過や課題を確認する。

問題105  ソーシャルワークの過程におけるアフターケアに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  ソーシャルワーカーや支援チームの状況変化に応じて行う。
    2  クライエントとの間に信頼関係を形成することが目的となる。
    3  アセスメントの精度を高めることが目的である。
    4  問題の新たな発生や再発が起きていないか確認をする。
    5  支援計画が十分に実施されたかを評価する。

問題106  ソーシャルワークの援助関係に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  共感的理解とは、クライエントの世界を、あたかもソーシャルワーカーも体験したかのように理解することである。
    2  目的志向性とは、クライエントを意図的に導くことにより、ソーシャルワーカーの自己覚知を促進することである。
    3  パターナリズムとは、ソーシャルワーカーの権威と自由裁量を否定し、対等な立場を重視した援助関係のことである。
    4  受容とは、クライエントの逸脱した態度や行動に対しても、同調した上で、それを許容することである。
    5  ソーシャルワーカーの自己開示とは、クライエントの行動や感情における矛盾を指摘することである。

問題107  次の記述のうち、ケアマネジメントの一連の過程における再アセスメントに関するものとして、最も適切なものを1つ選びなさい。
    1  サービスを新たに開始するために、クライエントの望む生活に向けた目標を設定し、その実現に向けて支援内容を決定した。
    2  クライエントの生活状況の変化によるサービス内容の見直しのために、新たに情報収集し、課題の分析を行った。
    3  クライエントの課題が解決したため、ケアマネジメントを終了することを確認した。
    4  クライエントになる可能性のある人の自宅やその地域を訪問し、ニーズを把握した。
    5  サービスの終結をした者から、新たにサービス利用の申し出があったため、情報の収集を行った。

問題108  ロスマン（Rothman, J.）が1960年代に提唱したコミュニティ・オーガニゼーション実践のモデルに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  組織化モデルとは、住民の地域生活支援を目標として、当事者の個別支援と連動させて、地域の生活基盤の整備に向けた地域支援を展開する方法である。
    2  小地域開発モデルとは、不利な立場に置かれた人々が直面する状況を自らの力では変革できない時に、同じ問題意識を共有する人々と連帯し、権力構造に対して政治的に働きかける方法である。
    3  社会計画モデルとは、住民や当事者が求めるサービスや資源の提供を達成するために地域のニーズを調査して、サービス提供機関間の調整を図る方法である。
    4  ソーシャルアクションモデルとは、地域が求める目標を達成するために、サービス提供機関が地域の資源を利用して活動を推進する方法である。
    5  統合モデルとは、地方自治体による政策実践と、福祉施設等における運営管理実践を一体のものとして、地域を変革することを主たる目標とする方法である。

問題109  グループワークに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  グループの発達過程は、メンバー間の関係の変化に影響を受ける。
    2  波長合わせとは、メンバー間の親しい接触を通して、お互いに刺激し、影響し合うことである。
    3  グループメンバー間の暗黙の葛藤に対しては、それが表面化しないように働きかける。
    4  プログラム活動では、全員が同じ動きを行うことを優先するように求める。
    5  終結期には、メンバー間の感情の表出や分かち合いを避ける。

問題110  スーパービジョンに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  スーパーバイジーは、スーパーバイザーより知識も技量も高い。
    2  スーパービジョンの契約は、スーパービジョンの展開過程の終結段階で行われる。
    3  スーパービジョンにおける管理的機能では、スーパーバイジーの業務遂行の適切さを確認する。
    4  パラレルプロセスは、スーパーバイジーが過去の特定の人間関係をスーパーバイザーとの関係の中に投影することである。
    5  スーパーバイザーは、クライエントに最良のサービスを直接提供する。

問題111  記録の方式の一つにＳＯＡＰ方式がある。その内容に関して、最も適切なものを1つ選びなさい。
    1  Ｓは、客観的情報であり、利用者の行動を観察した内容を記述する。
    2  Оは、主観的情報であり、利用者の語った内容を記述する。
    3  Ａは、支援計画であり、他機関や他専門職からの情報を記述する。
    4  Ｐは、プロセスであり、利用者の言葉や他機関からの情報に関する判断を記述する。
    5  ＳＯＡＰ記録は、問題と援助者の思考が明確になる問題志向型記録の一つである。

問題112  「個人情報保護法」に関する次の記述のうち、正しいものを1つ選びなさい。
    1  個人情報取扱事業者には、国の機関は除外されている。
    2  本人の生命の保護に必要がある場合であっても、本人の同意を得ることが困難であるときは、個人情報を第三者に提供してはならない。
    3  オンラインによる個人情報の提供は、ウイルスや不正アクセス等のリスクを伴うため禁止されている。
    4  クレジットカード番号は、個人識別符号に含まれる。
    5  事業者は、サービス利用者から本人のサービス記録の開示を求められた場合でも、これに応じる義務はない。

    （注）  「個人情報保護法」とは、「個人情報の保護に関する法律」のことである。 

問題113  事例分析の対象を手段的事例と固有事例に分けたとき、手段的事例の例として、最も適切なものを1つ選びなさい。
    1  ソーシャルワーカーが担当しているクライエントの支援において、今後の方向性を考えるために、クライエントと共に事例分析をした。
    2  新人のソーシャルワーカーが担当しているクライエントの支援過程について、指導的立場のソーシャルワーカーと一緒に、事例分析をした。
    3  ソーシャルワーカーが担当している事例で、支援結果が良好なものがあったので、その要因を明らかにするため、事例分析をした。
    4  ソーシャルワーカーが担当している事例で、複雑な問題を抱え支援が困難なクライエントがおり、事例分析をした。
    5  ソーシャルワーカーが担当している地区で、高齢者から振り込め詐欺に関する相談が頻繁にあるため、研修を目的とした事例分析をした。

問題114  事例を読んで、Ｎ市社会福祉協議会のＭ職員（社会福祉士）の対応として、適切なものを2つ選びなさい。
〔事  例〕
Ｎ市社会福祉協議会は、Ｎ市から避難行動要支援者への支援に関して委託事業を受けている。Ｍは、その事業のコーディネート役を担当しており、Ｎ市が海岸線の近くにあり、高台が少ないことから、大地震の際の津波などによる被害を心配している。Ｍは、日頃から「備えあれば憂いなし」と周りの職員たちに言い、避難行動要支援者を中心にした、平常時からのネットワーキングがＮ市には必要と考えて、支援活動をしている。
    1  近隣の住民に声をかけ、避難行動要支援者と一緒に避難訓練を行う。
    2  災害発生に備えて、避難行動要支援者名簿を地域の全戸に配布する。
    3  自力で避難できるよう、避難行動要支援者を個別に訪問して指導する。
    4  避難支援等関係者よりも、避難行動要支援者の安全確保を最優先するよう関係者に指示する。
    5  避難支援等関係機関と一緒に福祉避難所を確認する機会をもつ。

問題115  事例を読んで、Ａスクールソーシャルワーカー（社会福祉士）の解決志向アプローチに基づく問いかけとして、適切なものを2つ選びなさい。
〔事  例〕
Ｂさん（高校1年生）は、父親、弟（小学4年生）、妹（小学1年生）の4人家族である。父親は長距離トラックの運転手で、Ｂさんは長女として家事と弟妹の世話を引き受けている。ある日、Ａスクールソーシャルワーカーに、「家族のためにやれることをやるのは当然だし、喜んでもらえるのもうれしい。でも毎日勉強とバイトと家事で精一杯。これ以上はもう無理かも…」とつぶやいた。ＡはこれまでのＢさんの頑張りをねぎらいながら、以下の問いかけをした。
    1  「もし奇跡が起こって何もかもうまくいくとしたら、どうなると思いますか？」
    2  「最悪な状況を0、何もかも解決したのが10なら、今は何点になりますか？」
    3  「Ｂさんが『もう無理かも』と思ったのは、どのようなときですか？」
    4  「Ｂさんが想像する、最悪の事態はどのようなものでしょうか？」
    5  「今、Ｂさんが抱える状況の根本の原因は何だと思いますか？」

問題116  事例を読んで、Ｙ地域包括支援センターのＣ社会福祉士が参加している認知症初期集中支援チームの対応として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｙ地域包括支援センターに「夫の物忘れがひどく、指摘するとすぐに怒りだすことと、時折暴力を振るうことで困っている」とＤさん（72歳）から電話相談があった。その後、Ｄさんが来所して夫の日常の様子を詳しく話した。夫に病院で受診をしてもらおうとしたが、「俺はどこも悪くないから病院には行かない」と拒否され、困っているという。そこでＣは、認知症初期集中支援チームにおける対応が必要と考え、ケース会議の開催を要請した。
    1  夫を刺激しないように、認知症サポーターとＣが自宅を訪問する。
    2  Ｄさんが一人の時間を持てるように自宅を訪問し、夫の利用可能な認知症カフェの案内を手渡す。
    3  夫の状態について、認知症サポート医から専門的知見による助言を求める。
    4  夫の生活の様子を聞くために、介護福祉士とＣが自宅を訪問する。
    5  Ｄさんへの暴力回避のために、保健所の職員とＣが自宅を訪問する。

問題117  事例を読んで、ひきこもり地域支援センターのＦ職員（社会福祉士）による、グループワークのこの段階における関わりとして、最も適切なものを1つ選びなさい。
〔事  例〕
Ｆは、ひきこもり地域支援センターが1か月前に開設した、ひきこもり状態にある人たちのための居場所であるカフェで、グループへの支援を行っている。Ｆは2年前から根気強く訪問していたＧさん（38歳、男性）にもこのグループへ参加しないかと声をかけたところ、「どんなメンバーで、どんなことをしているのか」と興味を示し、久しぶりに外出し、カフェに初めて姿を見せた。Ｇさんは対人関係のつまずきからひきこもり状態となった経緯があり、人見知りがある。
    1  人見知りが激しいことを知っているので、他のメンバーに対応を委ねる。
    2  関係づくりができていることを活かしたいので、Ｇさんと二人で会話を続ける。
    3  以前から参加している他のメンバーと話せるように橋渡しをする。
    4  メンバー同士の関係を活用し、Ｇさんの長いひきこもり体験をメンバー間で分かち合うよう促す。
    5  Ｇさんの過去の対人関係をメンバー間で振り返り、気持ちの分かち合いを促す。

問題118  ソーシャルワークの面接技術に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  明確化によって、クライエントに特別な行動をするように伝えて、課題解決を促す。
    2  言い換えによって、クライエントの話す内容や感情を別の言葉で表現し、気づきを促す。
    3  閉じられた質問によって、クライエントが自由に話すのを促す。
    4  要約によって、より多くの情報を収集するために、クライエントの自己開示を促す。
    5  問題への直面化によって、クライエントとの信頼関係を構築する。

福祉サービスの組織と経営

問題119  社会福祉法人に関する次の記述のうち、正しいものを2つ選びなさい。
    1  主たる事務所の所在地において設立の登記をすることによって成立する。
    2  収支計算書の公表は任意である。
    3  他の社会福祉法人と合併することはできない。
    4  評議員、評議員会、理事、理事会、監事を設置することが義務づけられている。
    5  評議員は無報酬でなければならない。

問題120  経営の基礎理論に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  バーナード（Barnard, C.）によれば、非公式組織とは、意識的で、計画的で、目的をもつような人々相互間の協働である。
    2  テイラー（Taylor, F.）は科学的管理法を提唱し、作業現場の管理について、合理的な規則と手続きによる管理の重要性を強調した。
    3  ハインリッヒ（Heinrich, H.）は、軽微な事故への対策を実施しても、重大な事故を未然に防ぐことはできないことを明らかにした。
    4  アッシュ（Asch, S.）は、個人として正しい判断ができていれば、多数派の力には負けることはないという現象を明らかにした。
    5  メイヨー（Mayo, G.）とレスリスバーガー（Roethlisberger, F.）は、組織における経済的合理性を追求する、経済人モデルを提唱した。

問題121  集団やチームに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  集団浅慮とは、集団を構成する個々のメンバーが、個人で考えるよりも多面的な検討を行うことができるようになる現象のことである。
    2  集団の規範とは、メンバーが誰かの努力や成果にただ乗りして、自分自身は力を出し切らないことである。
    3  集団の凝集性は、集団を構成するメンバーを離散させ、個々人に分離させる傾向をもつ。
    4  チームの生産性は、チームメンバー間で信頼や尊敬の念が育まれていると低くなる。
    5  集団内のコンフリクトには、集団に悪影響を及ぼす非生産的コンフリクトと、集団に好影響を及ぼす生産的コンフリクトの両方の側面がある。

問題122  福祉サービス提供組織の財源に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  障害福祉サービスを行う事業者の収入の総額は、市町村からの補助金の総額に等しい。
    2  介護保険事業を行う事業者の収入の総額は、利用者が自己負担する利用料の総額に等しい。
    3  ファンドレイジングとは、事業や活動を行うために必要な資金を様々な方法を使って調達することを指す。
    4  社会福祉法人が解散する場合、定款の定めにかかわらず、その法人に対して寄付を行ってきた個人は、寄付した割合に応じて残余財産の分配を受けることができる。
    5  特定非営利活動法人は、特定非営利活動に係る事業に支障がない限り、事業によって得られた利益を自由に分配することができる。

問題123  福祉サービス提供組織の運営に関する次の記述のうち、適切なものを2つ選びなさい。
    1  アカウンタビリティとは、ステークホルダーに対する説明責任を指す。
    2  社会福祉法人における評議員会とは、法人の日常的な業務執行の決定などを行う機関である。
    3  社会福祉法人の監事には、法人の評議員会の業務執行を監査し、その内容について監査報告書を作成する役割がある。
    4  コンプライアンスとは、組織が法令や組織内外のルールを守ることにより、社会的責任を果たすことをいう。
    5  社会福祉法人における理事会とは、定款の変更や役員の選任などの体制の決定を行う機関である。

問題124  事例を読んで、Ｈ施設管理者が実施した人材育成の手法について、最も適切なものを1つ選びなさい。
〔事  例〕
Ｚ高齢者介護施設は、定期的に職場内において勉強会を実施している。このほど、Ｚ施設が立地するＰ県主催の「高齢者虐待の防止について」という研修会の通知が届いた。Ｚ施設のＨ施設管理者は、職員数名をこの研修会に参加させ、新たな知見を得てもらうこととした。
    1  コーチング
    2  ＯＦＦ－ＪＴ
    3  ジョブ（職務）ローテーション
    4  ＯＪＴ
    5  目標管理制度

問題125  「育児・介護休業法」に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  子の養育及び家族の介護を容易にするため、所定労働時間等に関し事業主が講ずべき措置を定めている。
    2  育児休業とは、産後8週までの女性に対し、使用者が休業を与えるものである。
    3  対象家族に無職かつ健康な同居者がいる場合は、介護休業を取得することができない。
    4  期間を定めて雇用される者は、雇用の期間にかかわらず介護休業を取得することができない。
    5  対象家族一人について、介護休業を分割して取得することはできない。

    （注）  「育児・介護休業法」とは、「育児休業、介護休業等育児又は家族介護を行う労働者の福祉に関する法律」のことである。

高齢者に対する支援と介護保険制度

問題126  「令和5年版高齢社会白書」（内閣府）に示された日本の高齢者を取り巻く社会情勢に関する次の記述のうち、正しいものを1つ選びなさい。
    1  人口の高齢化率は、2022年（令和4年）10月1日現在で、約16％となっている。
    2  高齢化率の「倍加年数」をアジア諸国で比較すると、韓国は日本よりも短い年数となっている。
    3  総人口に占める75歳以上の人口の割合は、2070年（令和52年）に約40％に達すると推計されている。
    4  2022年（令和4年）の労働力人口総数に占める65歳以上の者の割合は、2013年（平成25年）以降の10年間でみると、漸減傾向にある。
    5  2021年（令和3年）の65歳以上の者の死因別の死亡率をみると、悪性新生物よりも肺炎の方が高くなっている。

    （注）  「倍加年数」とは、人口の高齢化率が7％から14％に達するまでに要した年数のことである。

問題127  第二次世界大戦後の日本における高齢者保健福祉制度の展開過程に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  1950年（昭和25年）の生活保護法では、常時介護を必要とする老人の家庭を訪問する老人家庭奉仕員が規定された。
    2  1963年（昭和38年）の老人福祉法では、養護老人ホーム、特別養護老人ホーム、軽費老人ホームを含む、老人福祉施設が規定された。
    3  1982年（昭和57年）の老人保健法では、70歳以上の高齢者にかかる医療費のうち、その自己負担分を無料化する老人医療費支給制度が規定された。
    4  1997年（平成9年）の介護保険法では、要介護認定を受け、要介護と判定された高齢者等は、原則3割の利用者負担で、介護サービスを利用できることが規定された。
    5  2000年（平成12年）の社会福祉法の改正では、高齢者保健福祉推進十か年戦略（ゴールドプラン）が策定されたことを受け、地域包括ケアシステムが規定された。

問題128  事例を読んで、地域包括支援センターの社会福祉士によるＪさんの長女への助言として、適切なものを2つ選びなさい。
〔事  例〕
自宅で一人暮らしのＪさん（82歳、男性）は、脳梗塞の後遺症により軽い左片麻痺｛ひだりかたまひ｝があり、要支援1の認定を受けているが介護保険サービスは利用していない。2か月前に買物に行こうとして玄関先で転倒し、軽傷ですんだものの、それ以来自宅から出ようとしなくなった。近隣に住んでいる長女は、週に2、3度自宅を訪れ、買物や掃除・洗濯を手伝ってきた。しかし、「父は一人で大丈夫というが、むせることもあり食事量が減ってきて心配です。父はどのようなサービスが利用できますか」と地域包括支援センターに相談に来た。
    1  看護小規模多機能型居宅介護の利用
    2  介護老人福祉施設への入所
    3  介護予防通所リハビリテーションの利用
    4  短期入所生活介護の利用
    5  管理栄養士による介護予防居宅療養管理指導の利用

問題129  移動の介護に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  片麻痺がある人が杖｛つえ｝歩行を行う場合、杖は麻痺側に持つ。
    2  左片麻痺者が階段を上る時は、杖の次に左足を上げる。
    3  視覚障害者の歩行介助を行う場合、介助者は視覚障害者の後方を歩く。
    4  片麻痺がある人のベッドから車いすへの移乗では、車いすを要介護者の健側に置く。
    5  車いすで大きな段差を下るときは、前向きで降りる。

問題130  介護保険法に定める福祉用具貸与の種目として、最も適切なものを1つ選びなさい。
    1  腰掛便座
    2  移動用リフトの吊｛つ｝り具の部分
    3  認知症老人徘徊感知機器
    4  簡易浴槽
    5  入浴補助用具

問題131  介護保険制度における厚生労働大臣の役割に関する次の記述のうち、正しいものを1つ選びなさい。
    1  要介護認定の審査及び判定に関する基準を定める。
    2  要介護者等に対する介護給付費の支給決定を行う。
    3  介護支援専門員実務研修を実施する。
    4  介護給付等費用適正化事業を実施する。
    5  財政安定化基金を設置する。

問題132  事例を読んで、病院のＫ医療ソーシャルワーカー（社会福祉士）が、この時点でＬさんへの支援のために検討すべきこととして、最も適切なものを1つ選びなさい。
〔事  例〕
Ｋは、変形性膝関節症で外来通院中のＬさん（82歳、女性、独居、要支援2）から相談を受けた。Ｌさんは屋外の歩行が不自由で杖を使っているが、介護サービス等は利用していない。Ｌさんは、数年ぶりに趣味の歌舞伎鑑賞に出かけようと思い、介護保険制度のサービス利用について市役所に問い合わせたところ「本市では趣味のための移動支援は実施していない」と説明されたと言う。Ｌさんは転倒の心配もあり、歌舞伎鑑賞には見守り支援を利用したいと言っている。
    1  Ｌさんの支援を在宅医療・介護連携推進事業の担当者に依頼する。
    2  市役所の対応に関して、都道府県国民健康保険団体連合会へ苦情の申し立てを行うよう、Ｌさんに提案・助言を行う。
    3  Ｌさんの歩行機能の改善を図るため、地域介護予防活動支援事業の利用を勧める。
    4  Ｌさんの疑問や不安に対応してもらえるよう、介護サービス相談員と連携を図る。
    5  Ｌさんの居住地を担当する「生活支援コーディネーター（第2層）」に連絡を取り、Ｌさんが利用できる、制度外の外出時の見守り支援策について相談・調整を図る。

    （注）  「生活支援コーディネーター（第2層）」は、中学校区域を基本とする日常生活圏域で業務に当たる職員である。

問題133  介護福祉士に関する次の記述のうち、正しいものを1つ選びなさい。
    1  介護福祉士の法律上の定義には、介護者に対して介護に関する指導を行うことを業とすることが含まれている。
    2  介護福祉士が介護保険制度における訪問介護員として従事する際には、その資格とは別に、政令で定める研修を修了していることがその要件となる。
    3  介護福祉士は、医師の指示のもと、所定の条件下であれば、医療的ケアの一つとして脱水症状に対する点滴を実施することができる。
    4  介護福祉士は業務独占資格の一つであり、法令で定める専門的な介護業務については、他の者が行うことは禁じられている。
    5  認定介護福祉士を認定する仕組みは、2005年（平成17年）に制定された介護保険法等の一部を改正する法律において法定化され、その翌年から施行された。

問題134  事例を読んで、地域包括支援センターのＭ職員（社会福祉士）が訪問・相談を行った時点での対応として、適切なものを2つ選びなさい。
〔事  例〕
Ｑ市に住むＡさん（85歳、女性、要介護3）は長男（56歳）と二人暮らしである。Ａさんは5年前から物忘れが進み、排せつには介助を要し、日常的に長男が介護をしている。また、短期入所生活介護を2か月に1回利用している。今朝、長男から「気分が落ち込んでしまいここ3日ほどは眠れない」「当分は母の介護ができそうにない」と沈んだ声で地域包括支援センターに電話相談があった。これまでにもこのような相談が度々あり、それを受け、Ｍ職員がすぐに訪問・相談を行った。
    1  Ａさんの要介護状態の改善を図る必要があるため、介護予防ケアマネジメントの実施を検討する。
    2  総合相談支援業務として、長男の状態について同センターの保健師と相談し、気分の落ち込みや睡眠の問題に対応できる専門機関を探す。
    3  権利擁護業務として、Ａさんへの虐待リスクがあることについて、市に通報する。
    4  包括的・継続的ケアマネジメント支援業務として、Ａさんを担当する居宅介護支援事業所の介護支援専門員とともに、早急に今後の対応を検討する。
    5  Ａさんと長男が住む地域の課題を検討するため、地域ケア会議で報告する。

問題135  「高齢者虐待防止法」に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  この法律における高齢者とは、65歳以上で介護保険制度における要介護認定・要支援認定を受けた者と定義されている。
    2  この法律では、セルフネグレクト（自己放任）の状態も高齢者虐待に該当することが定義されている。
    3  この法律における高齢者虐待の定義には、保険医療機関における医療専門職による虐待が含まれている。
    4  この法律では、市町村が養護者による虐待を受けた高齢者の居所等への立入調査を行う場合、所轄の警察署長に援助を求めることができると規定されている。
    5  この法律は、市町村に対し、高齢者虐待の防止・高齢者とその養護者に対する支援のため、司法書士若しくは弁護士の確保に関する義務を課している。

    （注）  「高齢者虐待防止法」とは、「高齢者虐待の防止、高齢者の養護者に対する支援等に関する法律」のことである。

児童や家庭に対する支援と児童・家庭福祉制度

問題136  子ども・家庭の生活実態に関する次の記述のうち、正しいものを1つ選びなさい。
    1  「令和4年版男女共同参画白書」（内閣府）によると、子供がいる世帯の妻の就業状態は、パートタイム労働よりフルタイム労働の割合が高くなっている。
    2  「令和4年版犯罪白書」（法務省）によると、少年の刑法犯等検挙人員は令和3年には戦後最大となった。
    3  「令和3年度児童生徒の問題行動・不登校等生徒指導上の諸課題に関する調査結果について」（文部科学省）によると、いじめの認知（発生）件数は、令和2年度に比べ減少した。
    4  「令和3年度全国ひとり親世帯等調査結果の概要」（厚生労働省）によると、母子家庭の世帯の平均年間収入は、同年の国民生活基礎調査による児童のいる世帯の平均所得の約8割である。
    5  「令和3年度ヤングケアラーの実態に関する調査研究」の小学校調査によると、「ヤングケアラーと思われる子どもの状況」（複数回答）では、「家族の通訳をしている（日本語や手話など）」に比べて、「家族の代わりに、幼いきょうだいの世話をしている」が多い。

    （注）  「令和3年度ヤングケアラーの実態に関する調査研究」とは、株式会社日本総合研究所が、令和3年度子ども・子育て支援推進調査研究事業（厚生労働省）として実施したものである。

問題137  児童福祉法の総則規定に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  全て国民は、児童の年齢及び発達の程度に応じて、その意見が尊重されるよう努めなければならない。
    2  全て保護者は、その養育する児童の福祉を等しく保障される権利を有する。
    3  国は、児童を育成する第一義的責任がある。
    4  全て国民は、児童の最善の利益を実現しなければならない。
    5  全て児童は、家庭で育てられなければならない。

問題138  事例を読んで、Ｒ市子育て支援課のＢ相談員（社会福祉士）がＲ市で利用可能なサービスの中から紹介するものとして、最も適切なものを1つ選びなさい。
〔事  例〕
Ｃさん（2歳）の母親であるＤさんは、他の子どもと比べてＣさんの言葉が遅れていると気に病むようになり、外に出かけにくくなった。心配したＣさんの祖母がＤさんと共にＲ市子育て支援課に相談に来た。Ｂは、2人の話を聞き、どのようなサービスが利用可能かを一緒に検討することにした。
    1  保育所への入所
    2  母子健康包括支援センター（子育て世代包括支援センター）の利用
    3  児童館の利用
    4  子育て援助活動支援事業（ファミリー・サポート・センター事業）の利用
    5  児童相談所の利用

問題139  児童扶養手当に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  生活保護を受給していることが支給要件である。
    2  児童扶養手当法における児童とは、障害がない子どもの場合、18歳到達後の最初の3月31日までの間にある者をいう。
    3  児童扶養手当は児童手当と併給できない。
    4  支給額は、世帯の収入にかかわらず一定である。
    5  父子世帯は、支給対象外となる。

問題140  次の記述のうち、次世代育成支援対策推進法に関して、最も適切なものを1つ選びなさい。
    1  少子化に対処するための施策を総合的に推進するために、全ての児童が医療を無償で受けることができる社会の実現を目的としている。
    2  都道府県及び市町村には、10年を1期とする次世代育成支援のための地域における行動計画を策定することが義務づけられている。
    3  政府には、少子化に対処するための施策を指針として、総合的かつ長期的な労働力確保のための施策の大綱を策定することが義務づけられている。
    4  常時雇用する労働者の数が100名を超える事業主（国及び地方公共団体を除く）は、一般事業主行動計画を策定しなければならない。
    5  都道府県を基盤とした一元的な保育の給付について規定されている。

問題141  特別養子縁組の制度に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  配偶者のない者でも養親となることができる。
    2  養子となることができる子の年齢上限は、6歳である。
    3  養親には離縁請求権はない。
    4  特別養子縁組の成立には、実親の同意は原則として必要ではない。
    5  特別養子縁組は、都道府県が養親となる者の請求により成立させることができる。

問題142  事例を読んで、この時点でのＵ児童養護施設のＥ家庭支援専門相談員（社会福祉士）の対応について、最も適切なものを1つ選びなさい。
〔事  例〕
Ｆさん（40歳代、男性）は、息子Ｇさん（8歳）と父子家庭で生活していた。Ｇさんが3歳の時に、Ｆさんによる妻への暴力が原因で離婚した。Ｆさんは、行儀が悪いと言ってはＧさんを殴る、蹴る等の行為が日常的にみられた。額にひどいあざがあるような状態でＧさんが登校したことから、学校が通告し、ＧさんはＵ児童養護施設に措置された。入所後、家庭支援専門相談員であるＥがＦさんに対応している。ＦさんはＥと会う度に、「自分の子どもなのだから、息子を返して欲しい」と訴えていた。Ｇさんとの面会交流が進んだ現在では、「返してもらうにはどうしたらよいのか」と発言している。
    1  Ｆさんに二度と叩｛たた｝かないことを約束すれば、家庭復帰できると伝える。
    2  Ｆさんが反省しているとわかったので、家庭復帰できると伝える。
    3  Ｆさんに「なぜ叩いたのですか」と問い反省を求める。
    4  Ｆさんが体罰によらない子育てができるよう一緒に考える。
    5  Ｆさんは暴力による方法しか知らないのだから、家庭復帰は諦めるようにと伝える。

就労支援サービス

問題143  次の記述のうち、就労定着支援に関する説明として、最も適切なものを1つ選びなさい。
    1  特別支援学校を卒業したばかりの新卒者の職場定着を支援する。
    2  支援は、障害者が通常の事業所に雇用される前から開始される。
    3  支援は、最大6か月間提供される。
    4  支援の内容には、生産活動の機会の提供を通じて、知識及び能力の向上のために必要な訓練を供与することが含まれる。
    5  支援の内容には、障害者が雇用されたことに伴い生じる日常生活又は社会生活を営む上での問題に関する相談、助言が含まれる。

問題144  「障害者雇用促進法」に定める常用雇用労働者数100人以下の一般事業主に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  障害者雇用納付金を徴収されない。
    2  報奨金の支給対象とならない。
    3  障害者に対する合理的配慮提供義務を負わない。
    4  重度身体障害者及び重度知的障害者を雇用した場合、実雇用率の算定に際し1人をもって3人雇用したものとみなされる。
    5  法定雇用率未達成の場合に、「対象障害者の雇入れに関する計画」の作成を命じられることはない。

    （注）  「障害者雇用促進法」とは、「障害者の雇用の促進等に関する法律」のことである。

問題145  次の記述のうち、公共職業安定所（ハローワーク）が実施する業務として、最も適切なものを1つ選びなさい。
    1  労災保険給付の支給
    2  無料職業紹介事業の許可
    3  有料の職業紹介
    4  生活保護における生業扶助の支給
    5  障害者雇用に関する技術的助言・指導

問題146  事例を読んで、公共職業安定所（ハローワーク）の職員が行う対応として、最も適切なものを1つ選びなさい。
〔事  例〕
民間企業で10年間働いてきたＨさん（33歳）は、新たな職務に強いストレスを感じるようになり、出勤できなくなった。医師からうつ病との診断を受け、6か月間休職したが、症状が改善せず退職した。退職から1年が経ち、まだ、うつの症状は残っており、就業面、生活面での不安を感じるものの、金銭面の問題から、とにかく働かなければならないと焦りを感じ、公共職業安定所（ハローワーク）を訪問した。
    1  一般就労の経験があるＨさんは、問題なく一般就労が可能であると判断し、一般企業からの求人情報を提供する。
    2  Ｈさんの希望は就職であることから、適応訓練についてはあっせんしない。
    3  Ｈさんの確実な就職のため、一般企業ではなく特例子会社の求人を紹介する。
    4  本人の了解を得て、障害者就業・生活支援センターを紹介するなど関係機関と連携する。
    5  一般就労には週の所定労働時間が20時間以上であることが求められる旨を説明する。

更生保護制度

問題147  事例を読んで、この場合の仮釈放の手続きに関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
裁判所の判決で3年の懲役刑を言い渡されて、刑事施設に収容されていたＪさんは、仮釈放の審理の対象となった。
    1  仮釈放の要件として、刑の執行から最短でも2年を経過している必要がある。
    2  仮釈放の要件として、改悛｛かいしゅん｝の状があることがある。
    3  仮釈放を許す処分を決定するのは、地方裁判所の裁判官である。
    4  仮釈放の対象となるのは、初めて刑事施設に入った者に限られる。
    5  仮釈放の期間中、Ｊさんの希望により、保護観察が付される。

問題148  保護司に関する次の記述のうち、正しいものを1つ選びなさい。
    1  法務大臣から委嘱される。
    2  検察官の指揮監督を受ける。
    3  保護観察における指導監督の権限はない。
    4  担当する事件内容によっては給与が支給される。
    5  刑事施設収容中の者との面会は禁じられている。

問題149  事例を読んで、社会復帰調整官の対応として、最も適切なものを1つ選びなさい。
〔事  例〕
精神保健観察中のＫさんは、地域生活を送っている中で家族関係が悪化し、仕事にも行けなくなってきた。保護観察所は、関係機関の担当者とともにケア会議を開催し、Ｋさんの状態の情報共有と今後の処遇について話し合った。
    1  Ｋさんが継続的に医療を受けるよう、保護司に指導を指示する。
    2  指定通院医療機関への通院状況を確認する。
    3  精神保健観察の期間延長を決定する。
    4  指定入院医療機関に入院させることを決定する。
    5  今回作成する処遇の実施計画の内容をＫさんに秘匿することを決定する。

問題150  刑の一部の執行猶予制度に関する次の記述のうち、正しいものを1つ選びなさい。
    1  本制度の導入により、検察官による起訴猶予の処分は廃止された。
    2  本制度の導入により、執行する刑の全てを猶予する制度は廃止された。
    3  本制度の導入により、釈放後の生活環境の調整をする制度は廃止された。
    4  本制度の刑の一部の執行猶予期間は、刑期とともに判決時に言い渡される。
    5  本制度において、保護観察が付されることはない。

「第36回音声読み上げ用試験問題一覧」のページに戻る 



問題83  成年被後見人Ｊさんへの成年後見人による意思決定支援に関する次の記述のうち、「意思決定支援を踏まえた後見事務のガイドライン」に沿った支援として、最も適切なものを1つ選びなさい。
    1  Ｊさんには意思決定能力がないものとして支援を行う。
    2  Ｊさんが自ら意思決定できるよう、実行可能なあらゆる支援を行う。
    3  一見して不合理にみえる意思決定をＪさんが行っていた場合には、意思決定能力がないものとみなして支援を行う。
    4  本人にとって見過ごすことのできない重大な影響を生ずる場合にも、Ｊさんにより表明された意思があればそのとおり行動する。
    5  やむを得ずＪさんの代行決定を行う場合には、成年後見人にとっての最善の利益に基づく方針を採る。

    （注）  「意思決定支援を踏まえた後見事務のガイドライン」とは、2020年（令和2年）に、最高裁判所、厚生労働省等により構成される意思決定支援ワーキング・グループが策定したものである。


## 解答一覧

1 2
2 3 
3 4
4 2
5 5
6 5 
7 1

8 3
9 4
10 5
11 3
12 4
13 2
14 1

15 3
16 2
17 1
18 4
19 5
20 2
21 1

22 4
23 1
24 2
25 5
26 4
27 4
28 5
29 1
30 3,4
31 5

32 5
33 3
34 3
35 1
36 2
37 3
38 4
39 2
40 1,3
41 1,3

42 5
43 4,5
44 3
45 5
46 1
47 2
48 1

49 2
50 1
51 4
52 3
53 2
54 1
55 5

56 2
57 3
58 1
59 1
60 3
61 4
62 4,5

63 3,5
64 1
65 2
66 5
67 5
68 3
69 4

70 2
71 1
72 1 
73 2
74 5
75 3,4
76 3

77 3,4
78 4
79 2
80 3
81 5
82 3
83 2

84 5
85 4
86 3
87 3,5
88 1
89 4
90 2,3

91 3
92 4,5
93 5
94 2,4
95 1
96 1,3
97 5

98 3
99 2
100 4
101 5
102 3
103 3
104 1,5
105 4
106 1
107 2
108 3

109 1
110 3
111 5
112 1
113 5
114 1,5
115 1,2
116 3
117 3
118 2

119 1,4
120 2
121 5
122 3
123 1,4
124 2
125 1

126 2
127 2
128 3,5
129 4
130 3
131 1
132 5
133 1
134 2,4
135 4

136 5
137 1
138 2
139 2
140 4
141 3
142 4

143 5
144 1
145 5
146 4

147 2
148 1
149 2
150 4
