
第37回（令和6年度）社会福祉士国家試験午前の問題
医学概論

問題1  思春期・青年期における心身の特徴に関する次の記述のうち、正しいものを1つ選びなさい。
    1  思春期には、男女ともに緩やかな身体の変化がみられる。
    2  思春期における心理的特徴としては、自意識過剰がある。
    3  思春期には、アイデンティティは形成されている。
    4  第二次性徴に性差はみられない。
    5  青年期の死亡原因としては心疾患が最も多い。

問題2  高齢者における薬害有害事象の発生予防や発生時の対処方法に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  服用法を複雑にする。
    2  定期的に処方内容を見直す。
    3  若年者と同じ投与量にする。
    4  投与薬剤の数はなるべく8剤以下にする。
    5  新規症状が出現した場合に薬剤を追加する。

問題3  筋骨格系に関する次の記述のうち、正しいものを1つ選びなさい。
    1  筋肉は骨格筋と心筋の2種類からなる。
    2  筋組織にはカルシウムを貯蔵する働きがある。
    3  人体は約400個の骨からなる。
    4  骨量は小児期に最大となり、青年期以降は減少する。
    5  骨には血球をつくる働きがある。

問題4  難病に関する次の記述のうち、正しいものを2つ選びなさい。
    1  発病の機構が明らかでない疾患であることは、「指定難病」の要件の一つである。
    2  「指定難病」では、客観的な診断基準が定まっている。
    3  「指定難病」の患者数は我が国において人口の1％程度に達する。
    4  「障害者総合支援法」の対象疾患は、「指定難病」より対象範囲が狭い。
    5  小児の難病については、法律に基づく難病対策はない。

    （注）1  「指定難病」とは、「難病の患者に対する医療等に関する法律」に基づき、厚生労働大臣が指定する疾病をいう。
    2  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。

問題5  肺炎に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  市中肺炎の起因菌は肺炎球菌が最も多い。
    2  誤嚥｛えん｝性肺炎は若年者に多い。
    3  口腔｛くう｝ケアによって増悪する。
    4  経皮的酸素飽和度（SpO2）が上昇する。
    5  肺炎の診断には発熱が必須である。

問題6  事例を読んで、Ａさんに最も適切な入院形態を1つ選びなさい。
〔事  例〕
Ｂ市に住むＡさん（21歳）は、大学4年生で就職活動中であったが、なかなかうまくいかず、次第に抑うつ気分、意欲の低下、思考制止、不安、不眠を呈するようになった。同居する両親（両親ともに50歳代で共働き）とともに、精神科のクリニックを受診し、うつ病の診断となり治療開始となった。しかし、自宅では生活が乱れ、家に閉じこもりがちになり、定期的な受診や薬物治療が困難な状況となった。自傷行為や家族に対する他害行為はみられないが、なかなか抑うつ症状は改善を認めなかったため、主治医が入院加療の必要性があると判断した。主治医が本人及び両親に入院加療の必要性を説明したところ、本人は入院加療を希望した。その後、紹介状を持参のうえで、入院病床を有する精神科病院に受診した。
    1  医療保護入院
    2  措置入院
    3  緊急措置入院
    4  任意入院
    5  応急入院

心理学と心理的支援

問題7  次の記述のうち、エピソード記憶の事例として、最も適切なものを1つ選びなさい。
    1  暗算をする際に、途中の計算結果を覚えておきながら計算を進めた。
    2  相手の電話番号を聞いて、携帯電話に登録するまで覚えていた。
    3  カナダは北アメリカ大陸にある国だと覚えていた。
    4  昔、練習して乗れるようになった自転車に、今でもうまく乗ることができた。
    5  昨日の晩御飯にとんかつを食べたことを思い出した。

問題8  職場における人間関係や意思決定に関する課題が生じたときに、その原因を理解したうえで、対応策を考えることが重要である。次の記述のような課題が職場で生じたときに、社会的抑制による事例として、最も適切なものを1つ選びなさい。
    1  上司があまり成長を期待していなかった職員よりも、期待をしていた職員の方が次第に業績が向上するようになった。
    2  会議中、本当は反対したかったが、他の多くの参加者が賛成したので賛成してしまった。
    3  一人で考えていた内容よりも、全員が参加した会議で決めた内容の方が極端な結論になった。
    4  上司が仕事上の指導をするときに非常に近い距離まで接近してくるため、強い不快感が生じた。
    5  個室で一人で作業に取り組んだときよりも、大勢が一緒にいる部屋で取り組んだときの方が、他人の目が気になって効率が悪くなってしまった。

問題9  エリクソン（Erikson, E.）の発達段階説における青年期の心理社会的危機として、正しいものを1つ選びなさい。
    1  基本的信頼  対  基本的不信
    2  同一性  対  同一性混乱
    3  勤勉性  対  劣等感
    4  自発性  対  羞恥心
    5  ジェネラティビティ  対  停滞

問題10  レジリエンスに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  ストレスをもたらす原因となる出来事のことである。
    2  強いストレスや心理的傷つきを伴う経験から、個人が持つ回復していく力のことである。
    3  ストレスに伴って生じた不快な情動を、意識的に低減する方略のことである。
    4  心的外傷となった過去の出来事を、あたかも今生じているかのように経験することである。
    5  社会的な関係の中で行われる支え合いや支援のことである。

問題11  事例を読んで、マイクロカウンセリングのかかわり行動や基本的傾聴技法に基づいた面接の最初の段階の応答として、最も適切なものを1つ選びなさい。
〔事  例〕
認知症のある親の介護について負担を感じている相談者が、地域包括支援センターを訪れ、社会福祉士が面接を行った。相談者は「何度も同じことを聞いてくるのでイライラして、つい強い口調で怒ってしまう」と訴えた。
    1  「同じことを聞かれても、いつも初めてのように答えるといいですよ」
    2  「それは適切な行動ではないですよね」
    3  「私もあなたと同じような経験をしたので、あなたの気持ちがよくわかります」
    4  「その状況について、もう少し詳しく話してもらえませんか」
    5  「正確に記録したいので、ゆっくり話してもらえませんか」

問題12  認知行動療法に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  不安を「生の欲望」と捉え、不安にとらわれずに行動するよう指導する。
    2  クライエントが記憶や夢などを語る自由連想法が用いられる。
    3  抑圧されていることによって、対象者が気づいていない無意識への気づきを促す。
    4  不適応を生み出している行動や思考を、適応的なスタイルに変化させるように働きかける。
    5  クライエントの行動に焦点を当てて、強化因子を用いて介入するため、感情面の変化は目標としない。

社会学と社会システム

問題13  社会集団などに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  大衆とは、利害関心に基づき意図的に選択された集団のことである。
    2  外集団とは、そこに属していながら、帰属感や愛着心をもてない集団のことである。
    3  アソシエーションとは、特定の目的を達成するための集団のことである。
    4  ゲゼルシャフトとは、伝統的な地縁、血縁、友愛などによって形成された集団のことである。
    5  準拠集団とは、敵意を持ち嫌悪や軽蔑の対象となる集団のことである。

問題14  都市に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  サムナー（Sumner, W.G.）は、都市に特徴的な生活様式をアーバニズムとした。
    2  ジンメル（Simmel, G.）は、都市では多様な下位文化が形成されるとした。
    3  フィッシャー（Fischer, C.）は、都市を人間生態学的に分析した。
    4  倉沢進は、都市は同心円状的に形成されるとした。
    5  鈴木榮太郎｛すずきえいたろう｝は、都市は結節機関を持つ聚落社会｛じゅらくしゃかい｝であるとした。

問題15  「過疎関連法」及び「令和4年度版 過疎対策の現況」（総務省）に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  2020年（令和2年）国勢調査時点の過疎地域の産業別就業人口割合は、第一次産業就業者数が5割を超えている。
    2  2020年（令和2年）国勢調査時点の過疎地域の人口は、全人口の2割に満たない。
    3  2023年（令和5年）4月1日時点の過疎地域の市町村数は、全市町村数の4割に満たない。
    4  2020年（令和2年）国勢調査時点の過疎地域の高齢化率は、全国平均よりも低い。
    5  過疎地域とは、人口減少率によって定義されてきた。

    （注）  「過疎関連法」とは、現行の「過疎地域の持続的発展の支援に関する特別措置法」に至る一連の過疎関連の法律である。

問題16  次の記述のうち、2022（令和4）年の国民生活基礎調査の結果（「2022（令和4）年国民生活基礎調査の概況」（厚生労働省））についての説明として、最も適切なものを1つ選びなさい。
    1  1世帯当たり平均所得金額は300万円を下回っている。
    2  現在の暮らしの状況が「大変苦しい」「やや苦しい」とした世帯は、50％を超えている。
    3  相対的貧困率は20％を超えた。
    4  子ども（17歳以下）の相対的貧困率は25％を超えた。
    5  公的年金・恩給を受給している高齢者世帯の中で「公的年金・恩給の総所得に占める割合が100％の世帯」は、90％を超えている。

問題17  差別や偏見に関する次の記述のうち、適切なものを2つ選びなさい。
    1  ゴッフマン（Goffman, E.）は、主に身体に付随し、それが他者にとっての偏見を呼び起こす「印」として機能するものをスティグマと呼んだ。
    2  オルポート（Allport, G.）は、民族的偏見を「誤った、柔軟性のない一般化に基づいた反感」と定義づけた。
    3  リップマン（Lippmann, W.）は、人々の知覚や認識を単純化して理解することをダブル・コンティンジェンシーと呼んだ。
    4  コールマン（Coleman, J.）は、政治・経済・軍事などの分野のトップが社会の権力を握るとするパワーエリート論を展開した。
    5  ミルズ（Mills, C.）は、一次的逸脱と二次的逸脱という概念を用いて、逸脱的アイデンティティが形成されるメカニズムを説明した。

問題18  災害時におけるレジリエンスの意味として、最も適切なものを1つ選びなさい。
    1  災害の発生から復旧・復興に加え、次の災害に備えていくための諸活動を一つのサイクルとして捉えることである。
    2  支援ニーズに対して支援者側から積極的に働きかけて情報や支援を提供することである。
    3  被災者並びに被災地が被害から立ち直っていく際に持つ力のことである。
    4  予期しない出来事に遭遇した際に、事態が悪化しているにもかかわらず楽観的な見方を維持する態度のことである。
    5  大規模災害の後に一時的な現象として発生する理想郷的コミュニティのことである。

社会福祉の原理と政策

問題19  次の人物のうち、英国において「福祉国家」から「小さな政府」への転換を図った首相として、最も適切なものを1つ選びなさい。
    1  ウィンストン・チャーチル（Churchill, W.）
    2  クレメント・アトリー（Attlee, C.）
    3  マーガレット・サッチャー（Thatcher, M.）
    4  トニー・ブレア（Blair, T.）
    5  ゴードン・ブラウン（Brown, G.）

問題20  大正期の社会事業に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  感化法が制定された。
    2  中央慈善協会が設立された。
    3  恤救規則が制定された。
    4  大阪府で方面委員制度が創設された。
    5  石井十次によって岡山孤児院が設立された。

問題21  次の記述のうち、ニィリエ（Nirje, B.）が示したノーマライゼーションの考え方に基づく支援として、最も適切なものを1つ選びなさい。
    1  知的障害者と知的障害児を同じ施設で生活できるように支援する。
    2  要保護児童に対しては、大規模な入所型施設で専門的なケアを提供する。
    3  障害のある成人は、同性だけで生活するように支援する。
    4  知的障害者の生活を、ノーマルな生活状態に近づけることを目指す。
    5  知的障害者の自己選択よりも、支援者の決定を優先する。

問題22  「持続可能な開発目標」（ＳＤＧｓ）がターゲットとしている「極度の貧困」の参照基準として、最も適切なものを1つ選びなさい。
    1  ラウントリー（Rowntree, B.S.）が貧困調査で使用した「第1次貧困」
    2  経済協力開発機構（ＯＥＣＤ）で使用される「相対的貧困率」
    3  国連開発計画（ＵＮＤＰ）で使用される「人間開発指数」
    4  世界銀行で使用される「国際貧困線」
    5  タウンゼント（Townsend, P.）が貧困調査で使用した「相対的剥奪指標」

問題23  多文化共生社会の実現に向けた取組に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  「在留支援のためのやさしい日本語ガイドライン」では、外国人に情報を伝えるときは、外来語（カタカナ語）を多く使用するよう示している。
    2  「地域における多文化共生推進プラン（改訂）」では、外国人材の都市部への居住を促すことを目指している。
    3  多文化共生に取り組もうとする地方自治体への情報提供等のために、総務省は多文化共生アドバイザーの名簿を作成することとなっている。
    4  災害時外国人支援情報コーディネーターは、外国語を母語とする者を充てることとされている。
    5  「ヘイトスピーチ解消法」では、本邦外出身者も、日本文化の理解に努めなければならないと規定している。

    （注）1  「在留支援のためのやさしい日本語ガイドライン」とは、出入国在留管理庁と文化庁が2020年（令和2年）8月に作成したガイドラインのことである。
    2  「地域における多文化共生推進プラン（改訂）」とは、総務省が2006年（平成18年）3月に策定し、2020年（令和2年）9月に改訂したプランのことである。
    3  「ヘイトスピーチ解消法」とは、「本邦外出身者に対する不当な差別的言動の解消に向けた取組の推進に関する法律」のことである。

問題24  次の記述のうち、「国民の健康の増進の総合的な推進を図るための基本的な方針」で示された内容として、適切なものを2つ選びなさい。
    1  平均寿命の延伸に関する具体的な数値目標を設定する。
    2  女性については、ライフステージごとに女性ホルモンが劇的に変化するという特性等を踏まえ、人生の各段階における健康課題の解決を図ることが重要である。
    3  健康管理は個人の自己責任である。
    4  生活習慣病の発症予防や重症化予防よりも、再発や後遺症の予防を重視する。
    5  地域の人々のつながりや様々な社会参加を促すことを目標として設定する。

    （注）  「国民の健康の増進の総合的な推進を図るための基本的な方針」とは、「国民の健康の増進の総合的な推進を図るための基本的な方針の全部を改正する件（令和5年厚生労働省告示第207号）」として公表されたものである。これを踏まえ健康日本21（第三次）が示された。

問題25  福祉の措置に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  福祉サービスにかかる費用は全額国の負担となる。
    2  被措置者とサービス提供事業者との間で、サービス提供に関する契約を結ばなければならない。
    3  行政処分として福祉サービスの提供が決定される。
    4  介護保険法の施行により、老人福祉法による措置入所は廃止された。
    5  「障害者総合支援法」の施行に伴い、身体障害者福祉法及び知的障害者福祉法にかかる施設入所の措置を都道府県が採ることとなった。

    （注）  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。

問題26  社会福祉法に定められた福祉に関する事務所（福祉事務所）についての次の記述のうち、最も適切なものを1つ選びなさい。
    1  市町村は、福祉事務所を設置しなければならない。
    2  現業を行う所員については、社会福祉主事を充てるよう努めなければならない。
    3  現業を行う所員の数については、事務所ごとに標準数が定められている。
    4  指導監督を行う所員は、社会福祉士でなければならない。
    5  都道府県が設置する福祉事務所は、老人福祉法に定める福祉の措置に関する事務を行わなければならない。

問題27  次のうち、日本において、法令に照らして「間接差別」となる事例として、最も適切なものを1つ選びなさい。
    1  男女同数の職場にもかかわらず、法人内の管理職がほとんど男性のため、次の昇任人事では女性職員を優先して管理職に登用することにした。
    2  職場内で複数の職員が集まって、同僚の職員Ａの私生活を噂し、それを聞いた職員Ｂが不快に思った。
    3  広域にわたり展開する施設・事業所がなく、新規展開の計画がないにもかかわらず、転居を伴う転勤を要件として職員を募集し、男性だけを採用した。
    4  車いすを利用する障害者が、正当な理由がないにもかかわらず公共交通機関の利用を拒否された。
    5  特定の民族や国籍の人々に対し、その民族や国籍のみを理由として、地域社会からの排除を煽動｛せんどう｝する言動がなされた。

社会保障

問題28  事例を読んで、社会保険制度の加入に関する次の記述のうち、正しいものを1つ選びなさい。
〔事  例〕
Ａさん（23歳）は常勤の国家公務員である。Ａさんの配偶者であるＢさん（18歳）は無職であり、Ａさんに扶養されている。
    1  Ａさんは厚生年金保険の被保険者である。
    2  Ａさんは介護保険の第二号被保険者である。
    3  Ａさんは雇用保険の被保険者である。
    4  Ｂさんは健康保険の被保険者である。
    5  Ｂさんは国民年金の第三号被保険者である。

問題29  日本の社会保障の歴史に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  第二次世界大戦後間もなく、児童福祉法、身体障害者福祉法、老人福祉法が制定され、福祉三法の体制が確立した。
    2  厚生年金保険法の改正により、1961年（昭和36年）に国民皆保険が実現した。
    3  ひとり親世帯を対象とする手当の支給のために、1971年（昭和46年）に児童手当法が制定された。
    4  老人医療費の無料化が1982年（昭和57年）の老人保健法の制定により行われた。
    5  2000年度（平成12年度）から、新しい社会保険制度として、介護保険法が施行された。

問題30  「令和3年度社会保障費用統計」（国立社会保障・人口問題研究所）による社会保障の費用等に関する次の記述のうち、正しいものを1つ選びなさい。
    1  2021年度（令和3年度）の社会保障給付費の総額は、160兆円を超過している。
    2  2021年度（令和3年度）の部門別（「医療」、「年金」、「福祉その他」）の社会保障給付費のうち、「福祉その他」の割合は、2割を超過している。
    3  2021年度（令和3年度）の政策分野別社会支出の割合が最も大きいのは「家族」である。
    4  2021年度（令和3年度）の社会保障財源における公費負担の割合は、社会保険料の割合よりも大きい。
    5  2020年度（令和2年度）の日本の社会支出は、対国内総生産比でみると、ＯＥＣＤ加盟国の中で最も大きい。

問題31  社会保障の給付に係る国の負担に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  基礎年金の給付費の3分の2を負担する。
    2  年金生活者支援給付金の費用の2分の1を負担する。
    3  介護保険の給付費の2分の1を負担する。
    4  児童扶養手当の費用の3分の1を負担する。
    5  生活保護費の2分の1を負担する。

問題32  事例を読んで、社会保険の適用に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（47歳）は、大学卒業と就職氷河期が重なったことにより、正社員として就職することができず、現在に至るまでアルバイトとして働いている。Ａさんは7歳の子と二人で暮らしている。被用者保険の適用拡大によって、それまで国民健康保険の被保険者だったＡさんは初めて健康保険の被保険者となった。これにより、Ａさんの状況はどのように変化するか。
    1  新たに、国民年金の第二号被保険者となる。
    2  児童手当の支給額が増額される。
    3  新たに、労働者災害補償保険が適用される。
    4  新たに、介護保険の第二号被保険者となる。
    5  健康保険の保険料を、Ａさんが3分の2、事業主が3分の1を負担することになる。

問題33  公的年金の給付に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  老齢厚生年金は、受給権者が請求の手続きをとらなくても、支給開始年齢に達すれば自動的に支給が開始される。
    2  老齢厚生年金を受給しながら就労する場合、収入によっては老齢厚生年金の一部又は全部の支給が停止される場合がある。
    3  老齢基礎年金は、繰上げ受給又は繰下げ受給を選択できるが、いずれを選択しても受給額は変わらない。
    4  障害基礎年金の受給者が遺族基礎年金の受給要件を満たした場合、両方の年金を受給することができる。
    5  国民年金には、第三号被保険者を対象とする独自の給付として、付加年金がある。

問題34  事例を読んで、Ａさんに適用される社会保険制度に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（55歳）は配偶者のＢさんと離婚した。Ａさんは離婚以前、国民年金の第三号被保険者及び健康保険の被扶養者であった。二人の間に子はおらず、Ａさんは、現在、単身で暮らしている。離婚時に年金分割の手続きは済ませている。
    1  離婚前は、Ｂさんが、Ｂさん自身の厚生年金保険料に加えて、Ａさんの国民年金保険料を納付していた。
    2  Ａさんは、離婚前に被扶養者の認定を受けていた健康保険の任意継続被保険者となることができる。
    3  Ａさんは、離婚の前後を通じて、介護保険料を市町村から直接徴収されている。
    4  Ａさんは、分割した年金記録に基づく老齢厚生年金を、自身の支給開始年齢に達するまでは受給できない。
    5  Ａさんは、国民年金保険料の納付猶予制度を利用することができる。

問題35  雇用保険制度に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  基本手当の支給に係る失業の認定は、労働基準監督署において行われる。
    2  基本手当の所定給付日数は、被保険者期間には関係なく決定される。
    3  高年齢求職者給付金は、失業し、一定の要件を満たした高年齢被保険者に支給される。
    4  介護休業給付金では、介護休業開始時の賃金の50％相当額が支給される。
    5  出生時育児休業給付金は、産後休業中の労働者に対して支給される。

問題36  諸外国における公的医療と公的年金の制度に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  フランスの公的医療保険は、制度創設以来、外来診療については現物給付を原則としている。
    2  ドイツの公的年金制度は、全国民共通の一元的な所得比例年金の構造となっている。
    3  スウェーデンの公的年金制度は、完全積立の財政方式をとっている。
    4  イギリスでは、租税を主財源とする医療サービスにより公的医療を保障している。
    5  アメリカでは、連邦政府運営の公的医療保険によって国民皆保険を実現している。

権利擁護を支える法制度

問題37  次のうち、三親等の親族として、正しいものを1つ選びなさい。
    1  祖母
    2  配偶者の姉
    3  いとこ
    4  弟
    5  甥｛おい｝の配偶者

問題38  事例を読んで、障害者福祉施設従事者等による障害者虐待への対応に関する次の記述のうち、適切なものを2つ選びなさい。
〔事  例〕
Ａ県Ｂ市に所在するＣ障害者支援施設に勤務するＤ生活支援員は、同僚のＥ生活支援員が知的障害のある利用者のＦさんに対して、著しい暴言を投げかけている場面を目撃した。
    1  Ｄは、Ｆさんの同意の有無にかかわらずＢ市に通報する。
    2  Ｄは、施設長の許可を得てからＢ市に通報する。
    3  Ｂ市は、知的障害者福祉法に基づき立入調査を実施する。
    4  Ｂ市は、Ｄからの通報であることを施設に伝える。
    5  Ｂ市はＡ県に、Ｃ施設での障害者虐待に関する事項を報告する。

問題39  「障害者差別解消法」に関する次の記述のうち、正しいものを1つ選びなさい。
    1  都道府県知事は、障害を理由とする差別の解消に関する施策の総合的かつ一体的な実施のため、基本方針を定めなければならない。
    2  市町村長は、障害を理由とする差別の禁止に関して、事業者が適切に対応するために必要な指針を定めなければならない。
    3  事業者は、障害を理由とする差別の禁止に関する職員対応要領を定める義務がある。
    4  事業者は、障害者から社会的障壁の除去につき意思の表明があり、過重な負担でない場合、社会的障壁の除去について必要かつ合理的な配慮をしなければならない。
    5  事業主が労働者に対して行う障害を理由とする差別の解消のための措置についても「障害者差別解消法」の定めるところにより実施される。

    （注）  「障害者差別解消法」とは、「障害を理由とする差別の解消の推進に関する法律」のことである。

問題40  事例を読んで、Ａさんの状態に応じた権利擁護の方針に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ｂ県Ｃ町では、Ｃ町の社会福祉協議会が運営する成年後見センターにおいて、随時、成年後見制度の利用に関する判断を兼ねたケース会議を開催している。ある日、身寄りのない高齢者Ａさん（85歳）のケースがこの会議に諮られ、権利擁護の方針を検討した。
    1  Ａさんの判断能力に多少問題があるが、他の支援によってＡさんの利益が十分に図られていると認められる場合には、法定後見制度の利用を急がず、引き続き見守る方針を立てた。
    2  Ａさんの判断能力に問題はないが、身体的な障害があるので、補助開始の審判を申し立てる方針を立てた。
    3  Ａさんの判断能力に問題があるが、成年後見制度の利用をＡさんが拒んでいるので、補助開始の審判を市町村長により申し立てる方針を立てた。
    4  Ａさんの判断能力に問題があり、預金の管理に支援が必要と考えられるものの、申立費用の捻出が困難であるために、後見等開始審判の申立てを断念する方針を立てた。
    5  Ａさんの判断能力は補助相当と考えられるが、支援者に広い権限を付与した方が職務がしやすいという視点から、成年後見開始の審判を申し立てる方針を立てた。

問題41  成年後見制度の利用促進に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  市町村は、成年後見制度利用促進に係る地域連携ネットワークのコーディネートを担う中核機関を整備していくことが求められている。
    2  成年後見制度利用促進のため、都道府県知事による申立てを行うことができることとなった。
    3  都道府県は、成年後見制度の利用促進における意思決定支援の浸透を図るため「意思決定支援ガイドライン」の策定をしなければならない。
    4  都道府県は、成年後見制度の利用の促進に関し、専門的知識を有する者により構成される成年後見制度利用促進専門家会議の設置をしなければならない。
    5  市町村は、毎年一回、成年後見制度の利用の促進に関する施策の実施状況を公表することとされている。

問題42  事例を読んで、成年後見の開始がＡさんに及ぼす影響に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（30歳）は、交通事故の被害に起因する高次脳機能障害で判断力が著しく低下し生活が困難となったので、親族のＢさんが成年後見開始の審判の申立てをすることとなった。Ａさんは、この審判によって自分にどのような影響が及ぶのかを心配している。
    1  Ａさんは当然に国政の選挙権を失うこととなる。
    2  Ａさんは当然に公務員になることができなくなる。
    3  Ａさんは当然に社会福祉法人の理事になることができなくなる。
    4  Ａさんは当然に株式会社の役員になることができなくなる。
    5  上記1から4までの記述はいずれも不適切である。

地域福祉と包括的支援体制

問題43  市民による福祉の担い手に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  認知症サポーターは、専門職のサポートを行うため、地域包括支援センターに配属される。
    2  主任児童委員は、子どもや子育て家庭に関する相談に応じるため、児童家庭支援センターに配属される。
    3  労働者協同組合は、地域における多様な需要に応じた仕事を創出するために、組合員自らが出資し事業に従事する。
    4  民生委員は、市町村長の推薦によって、都道府県知事から委嘱される。
    5  社会的企業は、株主の利益を最優先しながら、ビジネスの手法によって社会課題を解決する。

問題44  「令和6年版地方財政の状況」（総務省）に示された2022年度（令和4年度）の民生費などに関する次の記述のうち、正しいものを1つ選びなさい。
    1  市町村の目的別歳出決算額の構成比は、大きい方から、民生費、総務費、教育費の順となっている。
    2  目的別歳出決算額において、都道府県では、2012年（平成24年）以降、災害救助費が一貫して増加している。
    3  市町村と都道府県の目的別歳出決算額に占める民生費の割合を比較すると、都道府県の方が大きい。
    4  目的別歳出決算額において、都道府県の民生費では、社会福祉費の割合が最も大きい。
    5  目的別歳出決算額において、市町村の民生費では、生活保護費の割合が最も大きい。

問題45  厚生労働省が発表した「地域福祉（支援）計画策定状況等の調査結果概要」（令和5年4月1日時点）に示された地域福祉（支援）計画の策定状況に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  地域福祉支援計画を策定済みでない都道府県も存在している。
    2  地域福祉計画の策定済み市町村の割合は、市部よりも町村部の方が高い。
    3  「包括的な支援体制の整備に関する事項」について、いずれかの項目を計画に位置付けている市町村は、8割を超えている。
    4  計画期間を3年とする市町村が最も多い。
    5  計画の評価実施体制を構築している市町村は全体の2割程度である。

    （注）  令和6年能登半島地震の影響により調査への対応が困難となった市町については、調査結果に当該市町は含まれていない。

問題46  事例を読んで、Ａ市社会福祉協議会が開催したボランティア養成講座の評価に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａ市社会福祉協議会では、数年間にわたり民間企業との連携によるボランティア活動の活性化を目的として、地域住民向けのボランティア養成講座を開催してきた。ボランティア養成講座は、地元企業や地域住民からの寄付金で運営されており、開催目的に即した効果が得られているかを検証するため、Ｂ社会福祉士は、プログラム評価を実施することにした。
    1  講座の内容が、計画どおりに実施されたかを検証するために、効率性評価を実施する。
    2  講座を開催したことにより民間企業との連携によるボランティア活動が活性化しているかどうかを調べるため、アウトカム評価を行う。
    3  講座の運営のために用いた寄付金が結果的に効果的・効率的に執行されたかを明らかにするため、プロセス評価を実施する。
    4  講座のカリキュラム内容が、開催目的と見合った内容であったかを検証するため、インパクト評価を実施する。
    5  ボランティア活動に対する地域住民の意向を明らかにするために、セオリー評価を行う。

問題47  日本における世帯や地域社会などの動向に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  総務省の「令和2年国勢調査」によると、単独世帯が一般世帯に占める割合は約10％となっている。
    2  法務省の「在留外国人統計」によると、2022年（令和4年）12月現在、在留外国人が総人口に占める割合は20％を超えている。
    3  総務省の「人口推計」によると、2022年（令和4年）10月現在、15歳から64歳までの生産年齢人口が総人口に占める割合は約30％となっている。
    4  内閣官房の「孤独・孤立の実態把握に関する全国調査（令和5年）」によると「孤独であると感じることがある」と回答した者の割合は約40％となっている。
    5  厚生労働省の「国民生活基礎調査」によると、2022年（令和4年）現在、生活状況を苦しいと感じている母子世帯が母子世帯全体に占める割合は約50％となっている。

    （注）  「孤独・孤立の実態把握に関する全国調査（令和5年）」とは、「孤独・孤立の実態把握に関する全国調査（令和5年人々のつながりに関する基礎調査）」のことである。また、「孤独であると感じることがある」と回答した者の割合とは、「しばしばある・常にある」「時々ある」「たまにある」と回答した者の割合の合計である。

問題48  包括的支援体制に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  重層的支援体制整備事業によって包括的支援体制の整備に取り組んでいる自治体数は、令和5年度の時点で全体の半数を超えている。
    2  包括的相談支援事業とは「複数の支援関係機関が有機的な連携の下、世帯が抱える地域生活課題の解決に資する支援を一体的に行う体制を整備する事業」である。
    3  アウトリーチ等を通じた継続的支援事業とは「虐待の防止及びその早期発見のための援助を行う事業」である。
    4  重層的支援会議とは「自ら支援を求めることが困難な人への支援について、支援を始める前に関係機関が情報を共有し、協議をする場」である。
    5  「地域共生社会推進検討会」では、地域づくりに向けた支援において、多様な人や機関がその都度集い、相談、協議し、学び合う場としてのプラットフォームづくりが重要であると指摘した。

    （注）  「地域共生社会推進検討会」とは、「地域共生社会に向けた包括的支援と多様な参加・協働の推進に関する検討会」のことである。

問題49  事例を読んで、Ａ市社会福祉協議会の地区担当のＢ職員（社会福祉士）の今後の対応として、適切なものを2つ選びなさい。
〔事  例〕
Ｃさん（20歳、知的障害）は、特別支援学校を卒業後、市内にある知的障害者通所施設に通っているが、地域の活動にも参加したいと思っている。そこでＣさんの両親は、社会福祉協議会が主催する地区の住民懇談会に参加した際に、息子が参加できるような地域活動はないかとＢに相談をした。Ｂは、この地区では高齢化が進み、地域活動の担い手の減少によって継続が困難となっており、商店も人手不足による閉店が増えていると感じている。
    1  Ｃさんから得意なことや、やってみたいことを聞き、この地区の中で活用できる社会資源を探す。
    2  地域住民に対して、知的障害者に対するサービスを立ち上げるように促す。
    3  Ｃさんに対して、施設通所を一時休ませて、地域活動に参加するよう助言する。
    4  Ｃさんに対して、商店の後継者となれるように経営の技術を学んでもらう。
    5  地域活動や商店の状況を把握し、Ｃさんのような人々の力を生かせる活動を地域住民と考える。

問題50  災害時の支援に関する次の記述のうち、適切なものを2つ選びなさい。
    1  被災者生活再建支援制度の対象とする自然災害は、市町村において1000世帯以上の住宅全壊被害が発生した場合である。
    2  介護保険制度では、全ての介護サービス事業者に対して、業務継続計画（ＢＣＰ）の策定とその計画に従って必要な措置を講ずることが定められている。
    3  災害救助法では、災害ボランティアセンターの設置を市町村社会福祉協議会に義務づけている。
    4  厚生労働省の「災害時の福祉支援体制の整備に向けたガイドライン」では、災害派遣福祉チーム（ＤＷＡＴ）の一般避難所への派遣について明記している。
    5  内閣府の「福祉避難所の確保・運営ガイドライン」では、指定福祉避難所は受入対象となる者をあらかじめ特定してはならないと定めている。

    （注）1  ＢＣＰとは、Business Continuity Planのことである。
    2  ＤＷＡＴとは、Disaster Welfare Assistance Teamのことである。

問題51  事例を読んで、Ａ市で重層的支援体制整備事業を所管するＢ職員（社会福祉士）の対応として、適切なものを2つ選びなさい。
〔事  例〕
就労経験のない若者やその家族から「働きたいと思っても、長年ひきこもっていることもあり、心身の状態に合わせて働ける場所がない」との意見が集まっていた。Ｂは、本人達の状態に合わせた多様な就労の機会を確保することを目指して、今後の参加支援事業の実施方法について関係者と検討することとした。
    1  一般就労が事業の支援目標であるため、ハローワークの求職票の探し方を学ぶプログラムを導入する。
    2  参加支援事業の独自性を明確化するため、地域づくり事業や相談支援事業と切り離して取組を進める。
    3  本人や家族の支援ニーズを踏まえ、社会参加に向けた取組を検討するための会議を開催する。
    4  中小企業や商店街などに働きかけ、短時間就労や就労体験などの支援メニューを創出する。
    5  ひきこもりに関する参加支援は、ひきこもり地域支援センターに対応を委ねる。

障害者福祉

問題52  「令和4年生活のしづらさなどに関する調査」（厚生労働省）、「令和5年度障害者雇用実態調査」（厚生労働省）及び「令和5年版障害者白書」（厚生労働省）にみられる障害児・者の実態に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  2012年（平成24年）から2022年（令和4年）の間に、特別支援教育を受ける児童生徒の数は減少した。
    2  身体障害者と知的障害者を比較すると、知的障害者の方が身体障害者よりも施設入所者の割合が高い。
    3  19歳以上65歳未満の在宅の身体障害者と知的障害者を比較すると、知的障害者の方が身体障害者よりも親との同居率が低い。
    4  在宅の身体障害者と知的障害者を比較すると、知的障害者の方が身体障害者よりも65歳以上の者の割合が高い。
    5  雇用されている身体障害者と知的障害者を比較すると、知的障害者の方が身体障害者よりも週の所定労働時間が30時間以上である者の割合が高い。

問題53  「障害者総合支援法」における基幹相談支援センターに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  地域における中核的な役割を担う機関として、総合的・専門的な相談支援や成年後見制度利用支援事業の実施等の業務を行う。
    2  障害者を通わせ、創作的活動又は生産活動の機会の提供、社会との交流の促進等の便宜を供与する役割を担う。
    3  障害者の職業生活における自立を図るため、就業面及び生活面の一体的な相談を行う。
    4  矯正施設を退所した障害者に対し、適切な福祉サービスに結び付けるための特別調整を行う。
    5  障害児の発達において中核的な役割を担う機関として、障害児の家族等に対し、相談、助言その他の必要な援助を行う。

    （注）  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。

問題54  事例を読んで、Ａさんの状況にあてはまる、「精神保健福祉法」に基づく入院形態として、最も適切なものを1つ選びなさい。
〔事  例〕
統合失調症のＡさん（40歳）は、この1週間で絶え間ない幻聴と、常に誰かに監視されているという妄想がひどくなってきた。さらに盗聴器を探して家具を壊すなどの行為が始まったため、同居する母親に付き添われ、かかりつけのＢ精神科病院を受診した。精神保健指定医であるＣ医師は診察の結果、入院治療を要すると判断し、Ａさんにその旨を説明したが、Ａさんはおびえた様子で意味不明な独語を繰り返すのみで、応答は得られなかった。Ｃ医師はＡさんが入院治療の必要性について納得できるよう丁寧に説明を重ねたが、やはり入院についての同意を得ることはできず、また、症状の緩和も見られなかったため、やむを得ず母親の同意によって即日入院してもらうことになった。
    1  措置入院
    2  緊急措置入院
    3  医療保護入院
    4  任意入院
    5  応急入院

    （注）  「精神保健福祉法」とは、「精神保健及び精神障害者福祉に関する法律」のことである。

問題55  「障害者差別解消法」に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  この法律が施行される前から、障害者基本法に「差別の禁止」の規定があった。
    2  民間事業者の合理的配慮の提供は、努力義務である。
    3  この法律に基づき、市町村障害者虐待防止センターが設けられている。
    4  障害者差別をした事業者には、この法律に基づき科料が科される。
    5  この法律に基づく障害者の定義は、障害者基本法に規定されている障害者の定義より狭い。

    （注）  「障害者差別解消法」とは、「障害を理由とする差別の解消の推進に関する法律」のことである。

問題56  「障害者雇用促進法」に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  就労継続支援Ａ型事業は、この法律に基づき就労支援サービスを提供するものである。
    2  公共職業安定所（ハローワーク）は、就労を希望した障害者の就職後の助言、指導は行わない。
    3  事業主は、障害者である労働者を雇用する事業所において障害者職業生活相談員を外部委託することができる。
    4  雇用義務の対象となる障害者であるかどうかの確認は、精神障害者については、精神障害者保健福祉手帳により行う。
    5  事業主は、障害者と障害者でない者との機会均等を図るために、過重な負担となるときであっても、合理的配慮を講じなければならない。

    （注）  「障害者雇用促進法」とは、「障害者の雇用の促進等に関する法律」のことである。

問題57  事例を読んで、大学の学生支援センターのＡ相談員（社会福祉士）のＢさんへの対応に関する次の記述のうち、適切なものを2つ選びなさい。
〔事  例〕
統合失調症の診断を受けた大学3年生のＢさんは、周囲から聞こえてくる悪口と薬の副作用に悩み、授業も休みがちである。Ｂさんは、主治医から「悪口は幻聴である。薬物療法で緩和できる」との説明を受けているものの、不安は消えない。悩んだＢさんは、学生支援センターを訪れ「薬の副作用がつらい。今後の就職活動も不安でたまらない。自分と同じ経験をしている学生は他にもいるのか。いるなら話をしてみたい」とＡに訴えた。Ｂさんの不安や焦燥感を受け止めたＡは、Ｂさんにどのように対応すべきかを考えている。
    1  主治医に相談するよう伝える。
    2  学生支援センターに登録しているピアサポートスタッフの紹介を検討する。
    3  地域の指定特定相談支援事業所の相談支援専門員の紹介を検討する。
    4  就労移行支援事業所のサービス管理責任者の紹介を検討する。
    5  精神障害者保健福祉手帳の取得を勧める。

刑事司法と福祉

問題58  犯罪の成立要件と責任能力に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  正当行為、正当防衛、あるいは緊急避難が認められた場合には、有責性がないものとして、無罪になる。
    2  正当防衛とは、正当な侵害に対して、自己または他人の権利を防衛するため、やむを得ずにした行為のことをいう。
    3  弁識能力及び制御能力の両方またはいずれかが欠けていれば、心神喪失となり、またどちらかでも能力が著しく減退していれば心神耗弱となる。
    4  心神喪失の場合には、刑法上の犯罪が成立せずに無罪となり、心神耗弱の場合には、刑の言渡しが猶予される。
    5  16歳未満の者の行為については、一律に責任能力に欠けるものとされており、犯罪は成立しない。

問題59  事例を読んで、次のうち、この手続きを表す名称として、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（30歳）は、自動車の大幅な速度超過により、道路交通法違反の罪で検挙された。Ａさんの事件は、簡易裁判所が、検察官の請求に基づき、命令により100万円以下の罰金または科料を科することができる手続きで処理されることになった。この手続きがとられるに当たって、Ａさんは、被疑者として異議がないことを示していた。
    1  起訴猶予
    2  微罪処分
    3  簡易送致手続
    4  交通反則通告制度
    5  略式手続

問題60  事例を読んで、刑の全部執行猶予中の保護観察に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（30歳）は、覚醒剤の自己使用により検挙され、懲役1年執行猶予3年保護観察付の判決が確定し、保護観察中である。Ａさんには「薬物再乱用防止プログラムを受けること」という特別遵守事項が設定されている。また、Ａさんには担当保護司が指名されている。
    1  Ａさんは、一般遵守事項に違反しても、執行猶予が取り消されることはない。
    2  Ａさんは、簡易薬物検出検査を受けなければならない。
    3  Ａさんに対する不良措置として、保護観察の期間の延長がある。
    4  Ａさんの担当保護司は、Ａさんの補導援護はできるが指導監督はできない。
    5  Ａさんが特別遵守事項に違反した場合には、保護観察所長が執行猶予を取り消す。

問題61  更生保護に関わる人または組織に関する次の記述のうち、正しいものを2つ選びなさい。
    1  地方更生保護委員会の事務局及び保護観察所に保護観察官を置くこととされている。
    2  保護司が備える条件の一つとして「人格及び行動について、社会的信望を有すること」がある。
    3  保護司活動の拠点として、各都道府県に1か所ずつ更生保護サポートセンターが設置された。
    4  更生保護法人は、厚生労働大臣の許可を受けて設立される。
    5  更生保護女性会は、更生保護法の制定に伴い設立された。

問題62  事例を読んで、「医療観察法」に基づく地域処遇に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（30歳）は「医療観察法」に基づく入院決定を受け、指定入院医療機関に入院していたが、その後、退院許可の決定を受け、現在は、地域処遇を受けて指定通院医療機関に通院している。
    1  Ａさんの精神保健観察は、保護観察所の保護観察官が担当する。
    2  Ａさんが「精神保健福祉法」に基づく医療保護入院となることはない。
    3  Ａさんの地域処遇が3年を超えて実施されることはない。
    4  Ａさんの地域処遇の期間は、保護観察所長の決定により短縮することがある。
    5  Ａさんの処遇の実施計画は、保護観察所長が関係機関と協議して定める。

    （注）1  「医療観察法」とは、「心神喪失等の状態で重大な他害行為を行った者の医療及び観察等に関する法律」のことである。
    2  「精神保健福祉法」とは、「精神保健及び精神障害者福祉に関する法律」のことである。

問題63  2004年（平成16年）に制定された犯罪被害者等基本法に関する次の記述のうち、正しいものを2つ選びなさい。
    1  同法における犯罪被害者等とは、犯罪等により害を被った者及び遺族を除いた家族をいう。
    2  同法の目的の一つに、再犯の防止と犯罪による被害を受けることの防止がある。
    3  同法に基づき、ストーカー行為を規制するための処罰が整備された。
    4  同法の基本的施策の一つに、損害賠償の請求についての援助がある。
    5  同法に基づき、政府は犯罪被害者等基本計画を定めなければならない。

ソーシャルワークの基盤と専門職

問題64  次の記述のうち、社会福祉士及び介護福祉士法において社会福祉士が努めなければならないと規定されていることとして、最も適切なものを1つ選びなさい。
    1  社会福祉士の信用を傷つけるような行為をしないこと。
    2  福祉サービス関係者等との連携を保つこと。
    3  相談援助に関する知識及び技能の向上を行うこと。
    4  正当な理由がなく、その業務に関して知り得た人の秘密を漏らさないこと。
    5  常にその者の立場に立って誠実にその業務を行うこと。

問題65  「ソーシャルワーク専門職のグローバル定義」（2014年）におけるソーシャルワークの知（Knowledge）に関する次の記述のうち、適切なものを2つ選びなさい。
    1  ソーシャルワークの理論的基盤及び研究は、専ら医学の知見に基づいて構成されている。
    2  ソーシャルワークの研究と理論の独自性は、閉鎖性と応用性にある。
    3  人々と作り上げてきたソーシャルワークの知は、それぞれの国や各地域においても、また国を越えて普遍的に、それぞれの形で、より適切に実践されることになる。
    4  ソーシャルワークの知は、西洋の理論や知識を根拠としたものであることが期待されている。
    5  多くのソーシャルワーク研究と理論は、サービス利用者との双方向性のある対話的過程を通して共同で作られている。

    （注）  「ソーシャルワーク専門職のグローバル定義」とは、2014年7月の国際ソーシャルワーカー連盟（ＩＦＳＷ）と国際ソーシャルワーク学校連盟（ＩＡＳＳＷ）の総会・合同会議で採択されたものを指す。

問題66  事例を読んで、Ａ社会福祉士の発言の基盤となっている考え方を提示した人物として、最も適切なものを1つ選びなさい。
〔事  例〕
地域活動支援センターで指導員として勤務するＡが、地域自立支援協議会の実務者会議に出席したところ、管轄地域内における今後の生活支援の方向性を問われた。そのため、日頃の相談支援活動を踏まえて「私は、障害のある方々の様々な活動が価値ある役割として、社会に認められていくための取組を、私たちはこれからも続けていくことが大切だと思います」と発言し、出席者から賛同を得た。
    1  バンク-ミケルセン（Bank-Mikkelsen, N.）
    2  ニィリエ（Nirje, B.）
    3  ソロモン（Solomon, B.）
    4  ヴォルフェンスベルガー（Wolfensberger, W.）
    5  バンクス（Banks, S.）

問題67  事例を読んで、被保護者との関係に苦慮するＡ現業員に対する査察指導員Ｂ（社会福祉士）のスーパービジョンの助言として、適切なものを2つ選びなさい。
〔事  例〕
Ｃ福祉事務所の査察指導員Ｂは、生活保護を担当して1年目のＡから、単身世帯のＤさん（70歳）への対応について相談を受けた。Ａによると、Ｄさんは、Ｄさんの誤解によるトラブルから近隣とのつきあいはほとんどなく、買い物以外は家に閉じこもっている。私（Ａ）が訪問すると毎回のように「あなたも近所の人たちと同じだ。あなたの話もわからない。福祉は困っている人を助けるためにあるはずだ。なのに、なぜ、もっと自分を助けてくれないのか」と言われる。内容を尋ねるも具体的なことはわからず、どのように応答してよいのか困っているとのことであった。
    1  「家庭訪問でのＤさんとのやりとりを振り返ってみましょう」
    2  「話し相手がいる近隣のサロンを紹介すると伝えてみましょう」
    3  「日頃の生活をご近所の方々に尋ねることについてＤさんから了解を得てください」
    4  「他の事例を適用してＤさんへの対応を検討してみましょう」
    5  「生活保護担当者としての業務と役割について、一緒に確認してみましょう」

問題68  アメリカにおける初期のセツルメントに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  「施与｛せよ｝ではなく友人を」を掲げて友愛訪問活動を行った。
    2  貧困を社会的・経済的な問題として捉えた。
    3  ケーススタディを通して貧困状態にある人の救済を行った。
    4  援助の効率化を図るために「援助に値する貧民」を選別した。
    5  シカゴにはトインビーホールが設立された。

問題69  ドルゴフ（Dolgoff, R.）らによって提示された倫理原則に関する次の記述のうち、正しいものを1つ選びなさい。
    1  平等と不平等に関する倫理原則では、同じ環境に置かれている人には誰に対しても同じように対応しなければならない。
    2  プライバシーと守秘義務に関する倫理原則では、全ての人が自らのプライバシーと守秘義務を強化しなければならない。
    3  自律と自由に関する倫理原則では、全ての人々の生活の質を高めるような選択肢を選ばなければならない。
    4  最小限の害に関する倫理原則では、あらゆる人の生活や生命を守らなければならない。
    5  誠実と情報の開示に関する倫理原則では、クライエントへの関連の有無に関係なく、全ての情報を伝えなければならない。

    （注）  「ドルゴフ（Dolgoff, R.）ら」とは、2009年にEthical Decisions for Social Work Practice（8th ed.）を著したドルゴフ、ローウェンバーグ（Loewenberg, F.M.）とハリントン（Harrington, D.）のことである。

ソーシャルワークの理論と方法

問題70  事例を読んで、保護観察所がＡさんの特別調整の協力を求めた機関について、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（84歳）は、来月で6回目の刑期を終える。Ａさんは帰る先もなく、頼れる人もいない。Ａさんは「帰るところも探せないし、お金もない」と話しており、特別調整を希望している。矯正施設では、福祉専門官がＡさんと面談し本人の意向を確かめた結果、特別調整対象者として判断したため、保護観察所に通知した。保護観察所長は、Ａさんの状況を確認するために特別調整協力の依頼を求めることにした。
    1  地域生活定着支援センター
    2  養護老人ホーム
    3  更生保護施設
    4  障害者支援施設
    5  福祉事務所

問題71  問題解決アプローチに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  クライエントのもつ主体的な意志の力に注目し、支援機関の活用を図る。
    2  クライエントの動機づけ、能力、機会を把握して支援を進める。
    3  クライエントが直面している危機状況に対して、短期集中的に働きかける。
    4  クライエントへの直接的な支援とともに、個人を取り巻く環境に働きかけを行う。
    5  クライエントが解決を望む問題について、目標と期限を設定し課題に取り組む。

問題72  事例を読んで、この段階のＡ病院のＢ医療ソーシャルワーカー（社会福祉士）が行った実践モデルやアプローチに関して、最も適切なものを1つ選びなさい。
〔事  例〕
Ｃさん（46歳、男性）は夫婦で生まれ故郷に戻り、5年前から喫茶店を営んでいる。1か月前に、脳出血を患い、Ａ病院でリハビリテーションを受け、数週間後に自宅退院を控えている。ＢはＣさんと退院に向けた面談を行った。Ｃさんは「左片麻痺｛ひだりかたまひ｝があるのは仕方がないとしても、妻もまた一緒にお店をやっていこうと言ってくれているので仕事がしたい。地元の友達も戻ってきたら店に行くよと声をかけてくれているから」と語った。Ｂは「奥様もお友達もＣさんがお店に戻ってこられるのを待っておられるんですね。お店に戻られるまで、どのように暮らしを整えていったら良いか、ご一緒に考えていきましょう」と提案した。
    1  行動変容アプローチ
    2  治療モデル
    3  実存主義アプローチ
    4  生活モデル
    5  課題中心アプローチ

問題73  事例を読んで、この時点でＡさんを担当する若年性認知症支援コーディネーターが行った支援に関する次の記述のうち、適切なものを2つ選びなさい。
〔事  例〕
総合商社に勤務するＡさん（44歳）は、半年前から商品の発注ミスや大事な商談の約束を忘れてしまうことが度々あり、Ｂ上司と産業医の勧めにより認知症疾患医療センターを受診し、若年性アルツハイマー型認知症と診断された。先日、Ｂ上司から、若年性認知症支援コーディネーターに電話相談があった。「Ａさんから、認知症だと診断されたと報告を受けた。実は、責任のある仕事を一人で任せることも難しくなった。Ａさんが自信なさそうに仕事をしており、時折、休むようになった。落ち込んでいる様子もあり、周りの社員も戸惑っている。私も社員も認知症のことがよくわからないので、今後どのように対応してあげたらよいのか正直わからずに困っている」とのことだった。
    1  Ａさんの仕事のミスがなくなるように、諦めずに教えてあげてください。
    2  Ａさんの意向を聴いて、仕事のサポート体制の構築を検討してください。
    3  Ａさんの家族にはＡさんの自尊心を尊重して今の社内での様子を伝えないようにしてください。
    4  Ａさんの短期記憶を活用できる業務への配置転換を検討してください。
    5  認知症の理解を進めるために認知症の学習会を実施する場合は、ご相談ください。

問題74  事例を読んで、地域包括支援センターのＡ社会福祉士がこの段階で行う援助に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ｂさん（75歳、女性）は、一人暮らしが不安になり、長男家族と同居することになったが、転居後すぐに自宅に閉じこもるようになった。心配した長男が地域包括支援センターを訪ね「以前は、社交的で友人と外出することもあったが、それがなくなり心配」と相談した。Ａは、Ｂさんと数回の面接を行った。Ｂさんは「長男家族が食事内容を私に合わせて作ってくれるのが、申し訳ない」「人と話すのが好きで、前に住んでいた地域では毎日楽しかった。きっかけがあれば外に出たい」と語った。Ｂさんは要支援1の認定を受けている。Ａは、得られた情報を踏まえてＢさんの支援計画を立てようと考えている。
    1  Ｂさんに元の地域に戻ってみても良いのではないかと助言する。
    2  Ｂさんと長男家族との関係修復を行い、閉じこもりを解消する。
    3  Ｂさんの食事は給食サービスを利用し、食事は家族と別にしても良いのではないかと助言する。
    4  Ｂさんの社交性は強みなので、地域の茶話会への参加を促す。
    5  代弁者として、Ｂさんの意向を長男に伝える。

問題75  ソーシャルワークの事後評価に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  クライエントが望んだ場合においてモニタリングの前に行う。
    2  クライエントの状況の変化に応じて行う。
    3  ワーカーがクライエントのプランニングに至る前に行う。
    4  結果評価の他、クライエントの主観的な満足度や支援者の関わり方について行う。
    5  クライエントの希望や望みを聞き、エンゲージメントのプロセスに基づいて行う。

問題76  コノプカ（Konopka, G.）の提唱したグループワークの原則に関する次の記述のうち、適切なものを2つ選びなさい。
    1  メンバー個々に新しい体験を付与することよりも、過去の体験を重視する。
    2  援助者が積極的にプログラムに参加し、メンバーの問題を解決する。
    3  グループ活動のルールを決め、メンバーの成長を阻害する場合には制限を設ける。
    4  メンバー個人の相違点、及び当該グループが他のグループとは違う特徴をもつグループであることを認識するために個別化を行う。
    5  メンバー間の相互作用の中で生じる葛藤は、表面化しないように働きかける。

問題77  事例を読んで、地域活動支援センターのＡ社会福祉士がＢさんの家族と面談を行った時点で用いた方法として、最も適切なものを1つ選びなさい。
〔事  例〕
Ａは、複数の利用者家族から子どもの自立と今後についての心配があるという声を聞くことが多くなった。このことから、家族同士が不安を話し合い、将来の子どもの生活について考えるグループワークを行うことにした。Ａは、その一環として開催前に参加を決定した利用者家族と個別面談を行った。面談の際、利用者Ｂさんの母親は「皆さんになじめるか不安です」と話した。ＡはＢさんの母親がグループに期待していることや不安に感じていることを聴いた。
    1  スクリーニング
    2  波長合わせ
    3  アイスブレイク
    4  集団規範の形成
    5  リーダーシップ

問題78  事例を読んで、Ａ相談支援事業所のＢ相談支援専門員が新任のＣ相談支援専門員に行ったスーパービジョンについて、適切なものを2つ選びなさい。
〔事  例〕
Ｂは、一人暮らしのＤさん（60歳）からＣが不在中に電話を受けた。「担当のＣに体調が良くないことを話したら、病院に付き添うから明日一緒に行こうと言ってくれたんですが、先週から保険証（マイナンバーカード）が見あたらなくて病院に行けないんです。明日も無理だと思うので断りたい」というものであった。Ｄさんを担当しているＣに伝えると「Ｄさんは、昨日会った時にどうして言ってくれなかったんだろう」と落ち込み、どうしたらよいかわからない様子だった。Ｂは、Ｃにスーパービジョンを行った。
    1  「ＤさんがＣに話せなかったことをＣはどう思っていますか」
    2  「Ｄさんの安心のために保険証（マイナンバーカード）を一緒に探してあげてください」
    3  「Ｃのような悩みはよくあることなので、あまり気にしすぎないようにしましょう」
    4  「Ｄさんと約束した時の状況について詳しく聞かせてもらえますか」
    5  「私が対応した類似事例を話すので、同じように対応してみましょう」

社会福祉調査の基礎

問題79  ブース（Booth, C.）のロンドン調査に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  ロンドン市民の人口統計の作成が目的だった。
    2  調査対象となった市民の自宅へ調査票を配布する郵送調査だった。
    3  当時のロンドン市民の一部を調査対象とする標本調査だった。
    4  貧困の主たる原因が、個人的習慣であることを明らかにした。
    5  ロンドンの街を経済階層で色分けした貧困地図を作成した。

問題80  調査における倫理に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  調査者と対象者との利害関係についての検討は不要である。
    2  調査の目的や対象等に関する倫理審査は、調査終了後に行う必要がある。
    3  対象者本人について調べる場合、対象者の認知機能を考慮することは不要である。
    4  調査が対象者に及ぼす心理的な影響については、検討する必要がある。
    5  想定していた結果と異なるデータは、削除する必要がある。

問題81  Ａ市こども家庭センターでは、担当圏域の地域住民を対象に、児童虐待の発生予防に向けた活動への協力意向について多肢選択法による質問紙調査を実施することにした。その際、用いる質問文として、最も適切なものを1つ選びなさい。
    1  「あなたは、児童虐待を防止するための活動や、児童虐待があった家庭を支援するための活動に協力したいと思いますか。あてはまるもの1つを選択してください」
    2  「児童虐待を予防するためには地域で協力することが必要不可欠ですが、あなたは、地域での見守り活動に協力したいと思いますか。あてはまるもの1つを選択してください」
    3  「あなたは、ネグレクトされている児童の早期発見に向けて、地域でのアセスメント活動に協力したいと思いますか。あてはまるもの1つを選択してください」
    4  「あなたは、児童虐待の予防に向けた小学校での取組に協力したいと思いますか。あてはまるもの1つを選択してください」
    5  「あなたは、虐待を受けた児童の心理面を支える活動に、地域のニートが協力することについて、どのようにお考えですか。あてはまるもの1つを選択してください」

問題82  事例を読んで、Ａ市地域包括支援センターが実施する調査票の配布・回収の方法として、最も適切なものを1つ選びなさい。
〔事  例〕
Ａ市地域包括支援センターでは、担当圏域における要支援状態の高齢者50名を対象に、高齢者が感じている困りごとの把握を目的とした標本調査を実施することとした。センター長からの「ご家族の困りごとではなく、高齢者ご自身が感じている困りごとの把握が目的である点に注意すること」という指示を踏まえて、調査票の配布・回収方法を検討することとなった。
    1  郵送調査
    2  留置調査
    3  個別面接調査
    4  集合調査
    5  インターネット調査

問題83  Ａ介護老人福祉施設では、夜間の睡眠時間を十分に確保できていない利用者Ｂさんへの対応が課題となっていた。検討の結果、日中の水分摂取量が要因のひとつとして取り上げられ、1か月間データを取って調べることとなった。
Ｂさんの日中の水分摂取量（ml）と夜間の睡眠時間（分）の関係を見るときに用いる方法として、最も適切なものを1つ選びなさい。
    1  t検定
    2  カイ2乗検定
    3  散布図
    4  箱ひげ図
    5  度数分布表

問題84  面接調査において調査者が行ったことに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  構造化面接において、調査の質問項目に設定していない内容についても自由に回答するよう対象者に求めた。
    2  半構造化面接において、インタビューガイドに設定した質問の順番に従って回答するよう対象者に求めた。
    3  非構造化面接において、調査開始前に対象者がテーマを設定するよう依頼した。
    4  フォーカスグループインタビューにおいて、司会者として最初に基本的なルールを説明した。
    5  面接後の逐語録作成において、録音データを聞き取れない部分は会話の流れから想像して記述した。

「第37回音声読み上げ用試験問題一覧」のページに戻る 


第37回（令和6年度）社会福祉士国家試験午後の問題
高齢者福祉

問題85  「令和6年版高齢社会白書」（内閣府）に示された日本の高齢者を取り巻く社会情勢に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  65歳以上人口増大により、死亡数は2006年（平成18年）から2022年（令和4年）まで増加傾向にあるが、2030年（令和12年）以降は減少に転じると見込まれている。
    2  65歳以上人口に占める一人暮らしの者の割合は増加傾向にあり、その傾向は、少なくとも2050年（令和32年）までは継続すると見込まれている。
    3  2023年（令和5年）現在の高齢化率を都道府県別にみると、最も高いのは島根県であり、最も低いのは埼玉県である。
    4  介護保険制度における要介護認定・要支援認定を受けた者は、2021年度（令和3年度）には第一号被保険者の3割を超えている。
    5  65歳以上の者について、2023年度（令和5年度）における住宅所有の状況をみると、持家（一戸建て・分譲マンションなどの集合住宅）が5割程度となっている。

問題86  日本の高齢者福祉制度の発展過程に関する次の記述のうち、正しいものを1つ選びなさい。
    1  1963年（昭和38年）の老人福祉法の制定によって、デイサービスやショートステイを含む在宅福祉サービスが法定化された。
    2  1982年（昭和57年）の老人保健法の制定によって、市町村及び都道府県における老人保健福祉計画の策定義務が法定化された。
    3  1997年（平成9年）の介護保険法の制定によって、介護保険の保険者は市町村及び特別区であることが法定化され、併せて広域連合や一部事務組合も保険者になることができるようになった。
    4  2005年（平成17年）の「高齢者虐待防止法」の制定によって、使用者（高齢者を雇用する事業主）による虐待が高齢者虐待の定義の一つとして、法定化された。
    5  2023年（令和5年）の「認知症基本法」の制定によって、国民に対して、認知症の人を不当に差別する行為を禁止することが法定化された。

    （注）1  「高齢者虐待防止法」とは、「高齢者虐待の防止、高齢者の養護者に対する支援等に関する法律」のことである。
    2  「認知症基本法」とは、「共生社会の実現を推進するための認知症基本法」のことである。

問題87  介護保険制度の介護報酬などに関する次の記述のうち、適切なものを2つ選びなさい。
    1  介護サービス事業者は、自己負担分を除いた介護報酬を国民健康保険団体連合会に請求する。
    2  介護報酬の額の基準を厚生労働大臣が定めるときには、あらかじめ介護保険審査会の意見を聴かなければならない。
    3  介護サービス事業者からの介護報酬の請求などに関する審査の事務は、社会保険診療報酬支払基金が行う。
    4  介護保険施設入所者のうち、低所得者など一定の条件に該当する者を対象として、入所中の食費と居住費の負担軽減を図るための補足給付が設定されている。
    5  介護報酬の1単位当たりの単価は、介護サービス事業所の所在する地域やサービス種別にかかわらず、全国一律に定められている。

問題88  Ａ社員（社会福祉士）は、Ｂ社の総務部門に在籍し、企業内での相談支援を担当している。事例を読んで、ＡによるＣさんへの介護休業制度に関する助言として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｃさん（52歳、無期雇用の正社員、入社後1年4か月）は母親（84歳）との二人暮らしである。この母親は、20日前にインフルエンザにかかり5日間入院した後、現在も自宅療養中であるが、退院後は歩行もできず、排せつや食事摂取に常時の介助が必要となった。要介護認定はまだ受けていない。Ｃさんは10日前から時間単位で年次有給休暇を取得して母親を介護しているが「仕事を辞めるわけにはいかず、母親の今後の介護はどうすべきか」と悩み、直属の上司からＡへの相談を勧められた。なお、Ｃさんは母親以外に介護が必要な家族・親族はいない。
    1  現時点でのＣさんの母親の状態は、介護休業制度の対象に該当する可能性があると助言した。
    2  介護休業を取得するためには、あと2か月の勤務期間が必要と助言した。
    3  介護休業を取得する場合、医療保険制度の介護休業給付が受給可能と助言した。
    4  介護休暇の取得は、年度あたり14日間が可能なことを助言した。
    5  現在の状況では、所定労働時間の短縮の措置を受けることは難しいと助言した。

問題89  事例を読んで、Ａ介護老人保健施設の支援相談員であるＢ職員（社会福祉士）が、通所介護事業所のＣ生活相談員から受けた情報提供の依頼に回答するにあたり、Ａ施設に勤務する他の職員に専門的な意見を求める際、最も適切な職種を1つ選びなさい。
〔事  例〕
入所後2か月が経過したＤさん（81歳、要介護2）は「介護サービスを利用しながら家族と自宅で暮らしたい」と希望しており、施設内で家庭復帰支援に向けたサービス担当者会議が開かれた。Ｄさんは脳梗塞後遺症で左片麻痺｛ひだりかたまひ｝があるが、屋内での日常生活動作は補助具などを使っておおむね自立している。しかし、球麻痺によって食事や飲水の際にむせ込むことがある。Ｂは、数日前にＤさんが退所後に利用を希望している通所介護のＣに連絡をとった際「Ｄさんの嚥下｛えんげ｝に関する訓練の状況や誤嚥を防ぐ適切な方法を知りたい」と情報提供の依頼を受けており、その情報をこのサービス担当者会議の場で取得しようと考えた。
    1  看護師
    2  介護福祉士
    3  薬剤師
    4  作業療法士
    5  言語聴覚士

問題90  事例を読んで、地域包括支援センターのＡ社会福祉士が、Ｂさんとともに利用を検討するサービスのうち、最も適切なものを1つ選びなさい。
〔事  例〕
一人暮らしのＢさん（80歳）は、心身の不調を感じたため要介護認定を申請した。その結果は要介護及び要支援ともに非該当であったが「基本チェックリスト」により運動機能の低下と閉じこもりの傾向にあることが示され、介護予防・生活支援サービス事業対象者に該当した。ＢさんはＡと相談した結果「自宅の中だけで過ごすことが多いため、運動や気分転換のために外出の機会をもつ必要があると思う。そうして人と関わる機会が増えれば、今後の生活に向けた意欲も増すかも知れない」と考えるに至った。
    1  第1号通所事業（通所型サービス）
    2  地域密着型通所介護
    3  介護予防通所リハビリテーション
    4  小規模多機能型居宅介護
    5  居宅介護支援
児童・家庭福祉

問題91  意見表明等支援事業などに関する次の記述のうち、適切なものを2つ選びなさい。
    1  意見表明等支援員は、子どもの未熟さを補い、専門知識に基づいて児童を指導するものである。
    2  児童福祉に関する知識等を有する者が、児童の意向などを勘案して、児童相談所等の関係機関と連絡調整を行う。
    3  児童養護施設等に入所中の児童、里親委託中の児童、一時保護中の児童は、この事業の対象である。
    4  児童相談所の児童福祉司は、意見表明等支援員とは別に、単独で児童の意見を聴取することを控えなければならない。
    5  児童養護施設の職員や里親は、児童の最善の利益を考慮して、意見表明等支援員に対して、養育についての自分の意見は述べないことが望ましい。

問題92  事例を読んで、Ａ市子育て支援課が最優先すべき初期対応として、最も適切なものを1つ選びなさい。
〔事  例〕
Ｂさん（3歳）は、保育所を利用しているが、週1回も登園していない。父親は病気がちで仕事が続かず、母親は精神疾患があり自宅で寝ていることが多いため就労が難しく、家族は経済的に困窮している。Ｂさんはまだ発語がなく、このまま発育が遅れていくことを保育所は懸念している。Ｂさんがめずらしく登園した日、何日も入浴していないことに気づいた保育所は、Ｂさんがいる間にＡ市の虐待通告窓口にもなっている子育て支援課へ連絡し、ネグレクトの懸念を伝えた。
    1  保育所に児童相談所へ通告するよう、働きかける。
    2  保育所に児童発達支援センターと相談するよう、助言する。
    3  緊急の受理会議を行い、Ｂさんが保育所にいる間に複数の職員で訪問し、児童の状況を把握する。
    4  児童相談所へ連絡し、一時保護するように要請する。
    5  保育所に父母への生活保護制度の情報提供を依頼する。

問題93  事例を読んで、Ａさんの状況を踏まえ、Ｂ市子育て支援課がＡさん親子の支援のために、この時点で危機介入として速やかに連携すべき機関・施設として、適切なものを2つ選びなさい。
〔事  例〕
Ａさん（32歳）から、これまでも「夫（35歳）から繰り返し暴言を浴びせられ、時に暴力を振るわれている。どうしたらよいか悩んでいる。夫から逃れたい」という相談を受けてきた。ある日「もう限界です」という訴えがあった。Ａさんは、4歳の子を帯同しており、子には母親をかばう様子もみられる。Ａさんの家庭は夫の収入によって生計を立てているが、その収入はほとんど夫が管理しており、Ａさんは手元に所持金が全くない状況である。Ａさんは、子とともに生活したいと望んでいる。Ｂ市子育て支援課は緊急受理会議を行った。
    1  児童養護施設
    2  母子生活支援施設
    3  Ｂ市の女性相談支援員
    4  女性自立支援施設
    5  女性相談支援センター

問題94  事例を読んで、市で子育て相談を担当するＡ職員（社会福祉士）が保護者に伝える内容に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａのもとに保護者から下記の相談があった。
3歳児健診の際に医師から発達に課題があるかもしれないと指摘され、専門医を受診したところ、軽度の発達障害（自閉スペクトラム症）と診断された。しかし両親ともに発達障害や障害児福祉サービスについての知識がなく、不安だとのことだった。両親はともに常勤の会社員で、子どもは現在保育所を利用している。
    1  障害児福祉手当の受給が可能である。
    2  保育所の利用はできなくなる。
    3  児童発達支援の利用が可能である。
    4  放課後等デイサービスの利用が可能である。
    5  医療型障害児入所施設への入所が可能である。

問題95  こども基本法に関する次の記述のうち、適切なものを2つ選びなさい。
    1  「こども」について、18歳に満たない者と定義されている。
    2  「こども施策」には、子育てに伴う喜びを実感できる社会の実現に資するため、就労、結婚、妊娠、出産、育児等の各段階に応じて行われる支援が含まれている。
    3  基本理念の一つとして、教育基本法の精神にのっとり教育を受ける機会が等しく与えられることとされている。
    4  都道府県は、こども大綱を勘案して、都道府県こども計画を定めなければならない。
    5  児童虐待を受けたと思われる児童を発見した者の通告義務が明記されている。

問題96  困難な問題を抱える女性への支援に関する法律（女性支援新法）に関する次の記述のうち、正しいものを1つ選びなさい。
    1  本法成立前までは、配偶者からの暴力の防止及び被害者の保護等に関する法律に婦人相談所や婦人保護施設が規定されていた。
    2  本法における困難な問題を抱える女性とは、障害及び社会的障壁により継続的に日常生活または社会生活に相当な制限を受ける状態にある女性を指す。
    3  都道府県は、厚生労働大臣が定めた困難な問題を抱える女性への支援のための施策に関する基本的な方針に即して、基本的な計画を定めることができるとされている。
    4  都道府県は、女性相談支援センターを設置しなければならない。
    5  都道府県は、困難な問題を抱える女性を入所させて、その保護及び支援を目的とする女性自立支援施設を設置しなければならない。

貧困に対する支援

問題97  生活保護の種類と内容に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  小学生の学校給食費は、生活扶助で行われる。
    2  要介護認定を受けた80歳の被保護者の住宅改修費のうち介護給付にかかる自己負担分は、介護扶助で行われる。
    3  通院のための交通費（移送費）は、生活扶助で行われる。
    4  高等学校の教材代や通学のための交通費は、教育扶助で行われる。
    5  就職が確定した40歳の被保護者が、就職のため直接必要とする衣服類の購入費用は、生活扶助で行われる。

問題98  事例を読んで、Ａさんに対する福祉事務所の現業員（社会福祉士）の対応に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
ホームレスの男性Ａさん（55歳）は8年前にギャンブルが原因で多額の借金をつくり、会社を辞めて、その後就労しないままホームレスとして生活していた。婚姻歴はあるが30歳の時に離婚して子どもは妻が引き取りその後音信はない。最近、体調も悪くなったため生活保護を申請したいと考え福祉事務所に来所した。長年のホームレス生活のため、収入、資産に関する書類は所有していない。
    1  居住地がないため居住地を定めてから保護申請するように説明する。
    2  稼働年齢層なので就労先を決めてから保護申請するように説明する。
    3  ギャンブルによる多額の借金がある場合には保護申請はできないと説明する。
    4  収入、資産に関する書類がなくても保護申請は可能だとして、申請手続きについて説明する。
    5  保護申請に先立って、子どもへの扶養調査が必要だと説明する。

問題99  生活困窮者自立支援法に関する次の記述のうち、正しいものを1つ選びなさい。
    1  生活困窮者自立支援法の改正（2018年）により、任意事業に健康管理支援事業が追加された。
    2  住居確保給付金の支給審査や支給決定及び支給の業務は、福祉事務所設置自治体が行う。
    3  生活困窮者自立支援法では、相談支援とともに飲食物費や光熱水費について金銭給付を行うことを通じて自立を図ることを目的としている。
    4  一時生活支援事業は、低所得世帯であって世帯内の高齢者や子どものケアを行っている家族が一時的に休息をとれるようにサポートする事業である。
    5  生活困窮者自立支援法は、日本の永住者資格を有する外国籍の人を対象外としている。

問題100  次のうち、生活福祉資金貸付制度の総合支援資金に含まれるものとして、正しいものを2つ選びなさい。
    1  生活支援費
    2  緊急小口資金
    3  教育支援費
    4  就学支度費
    5  一時生活再建費

問題101  事例を読んで、生活困窮者自立相談支援機関の相談支援員による支援に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ａさん（25歳）は、両親と3人で暮らしている。高校卒業後、工場に就職したが職場での人間関係がうまくいかず3か月で離職した。その後も短期間での転職を繰り返し、ここ2年ほどは無職である。仕事上の失敗が続いたことから就労への意欲が低下して、引きこもり状態である。そこで、Ａさんの状況を見かねた両親は、本人とともに社会福祉協議会に設けられている生活困窮者自立相談支援機関の窓口に行って相談した。Ａさんもこのままではいけない、どうにか1歩前に進みたいと意欲を示し、両親からもＡさんを支えていきたいとの気持ちが示された。
    1  生活保護を受給する可能性を探るため、資力調査を行う。
    2  生活保護の受給に先立って、自立支援プログラムを策定し、参加を勧める。
    3  Ａさんの課題を把握し、自立相談支援機関による支援を継続するか、他機関につなげるかを判断する。
    4  ハローワークで求職活動を行うよう、生活困窮者自立支援法に基づく指導・指示を行う。
    5  自立生活のためのプラン案を策定するため、支援会議の開催を依頼する。

問題102  事例を読んで、退院を控えたＡさんに対する福祉事務所の現業員（社会福祉士）の説明に関する次の記述のうち、適切なものを2つ選びなさい。
〔事  例〕
Ａさん（26歳）は、両親を早くに亡くし、児童養護施設に入所した。退所後は就職した会社の寮に入っていたが病気のため退職し、入院治療となった。収入は途絶え預貯金もなくなったため、生活保護を受けて療養していたところ、医師はそろそろ退院でき、後遺症も残らないという。Ａさんは、退院後は地域で生活したいが、仕事や住まいに不安が大きいため、病院のソーシャルワーカーに相談したところ、現業員を交えて3人で話し合いをすることになった。
    1  「退院したら治療が必要なくなるので、医療扶助は廃止になります」
    2  「アパートを借りる場合には、敷金や礼金が住宅扶助から支給されます」
    3  「地域での生活が落ち着いてからハローワークに行ってはどうですか」
    4  「退院後、救護施設に入るよう手続きをしておきます」
    5  「退院後、しばらくは児童養護施設で生活できるように施設長にお願いしておきます」
保健医療と福祉

問題103  事例を読んで、Ａ医療ソーシャルワーカー（社会福祉士）によるＢさんへの説明に関する次の記述のうち、適切なものを2つ選びなさい。
〔事  例〕
Ｃ県で暮らすＢさん（56歳、会社員）は、1年前より箸が持ちにくい、重いものが持てない等の症状が見られ、1か月前より休職していた。1週間前に自宅の階段から転落し、病院に救急搬送された。大きなケガはなかったものの、両下肢の筋力低下が著しく、歩行が困難となっており、外来の医師より難病の疑いがあるとの説明を受け、Ｄ神経内科医師を紹介され受診した。その結果、筋萎縮性側索硬化症（ＡＬＳ）との診断結果を受けた。今後の療養生活の支援が必要と考えたＡは、Ｂさんへ次のような説明を行った。
    1  「難病の治療費については、育成医療が適用されます」
    2  「「難病法」による医療費の自己負担は徴収されません」
    3  「「難病法」により、医療費は公費優先となります」
    4  「一定の条件の下で、「障害者総合支援法」による障害福祉サービスの対象となります」
    5  「県内の難病相談支援センターのピアサポーターによる支援があります」

    （注）1  「難病法」とは、「難病の患者に対する医療等に関する法律」のことである。
    2  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。

問題104  事例を読んで、受診した病院のＡ医療ソーシャルワーカー（社会福祉士）による、この段階でのＢさんへの説明として、適切なものを2つ選びなさい。
〔事  例〕
Ｂさん（43歳、正社員）は、健康保険の被保険者であり、勤務する会社の倉庫での機械の入出庫や運搬に従事している。昨日、勤務中に会社の倉庫内でうっかり商品の機械を自分の足の上に落としてしまった。病院を受診した結果、左足の指2本を骨折と診断された。
    1  高額療養費制度の説明
    2  傷病手当金の説明
    3  療養補償給付の説明
    4  医療保険と労働者災害補償保険の違いの説明
    5  公費負担医療制度の説明

問題105  診療報酬制度に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  介護報酬改定の時期と診療報酬改定の時期が重なることはない。
    2  混合診療が行われた場合、診療報酬は減額して支払われる。
    3  診療報酬上で、社会福祉士の配置や関与が評価されているものがある。
    4  ＤＰＣ制度（ＤＰＣ／ＰＤＰＳ）とは、診療報酬の出来高算定制度のことである。
    5  診療報酬の全体の改定率は、社会保険診療報酬支払基金が決定する。

問題106  医療倫理の4つの原則に含まれるもののうち、正しいものを2つ選びなさい。
    1  人間の尊厳
    2  多様性の尊重
    3  必要即応
    4  正義
    5  自律尊重

問題107  「事業場における治療と仕事の両立支援のためのガイドライン（2024年（令和6年）3月改訂版）」（厚生労働省）に沿った治療と仕事の両立支援に関する次の記述のうち、正しいものを1つ選びなさい。
    1  ガイドラインでは、短期で治癒する疾病を対象としている。
    2  支援は、事業者からの申し出により開始される。
    3  医療機関の裁量で、労働者の疾病の情報を事業者へ提供することができる。
    4  職場復帰支援プランは、医療ソーシャルワーカーが単独で策定する。
    5  主治医等が就労継続困難と判断した場合、事業者は就業禁止の措置を取る必要がある。

問題108  事例を読んで、「医療ソーシャルワーカー業務指針」に基づいた、Ａ医療ソーシャルワーカー（社会福祉士）の実践に関する次の記述のうち、最も適切なものを1つ選びなさい。
〔事  例〕
Ｂさん（38歳、正社員）は、会社のラグビー同好会の練習で受傷し、病院に救急搬送され入院となった。主治医からＢさんに、今後車いす生活となること、回復期リハビリテーション病棟へ転院する必要があることが説明された。しかし、経済的不安を抱えたＢさんは自宅退院を訴えている。主治医から依頼を受けたＡはＢさんとインテーク面接を実施することとなった。
    1  まずは面接をリハビリ室で行う。
    2  守秘義務の観点から面接内容については主治医に報告しない。
    3  転院先の選定については、Ａが判断する。
    4  入院費、生活費などの問題解決について話し合う。
    5  自宅への退院支援を行う。

    （注）  「医療ソーシャルワーカー業務指針」とは、「医療ソーシャルワーカー業務指針（2002年（平成14年））」（厚生労働省健康局長通知）のことである。

ソーシャルワークの基盤と専門職（専門）

問題109  専門職化に関する次の記述のうち、グリーンウッド（Greenwood, E.）が述べたものとして、最も適切なものを1つ選びなさい。
    1  体系的な理論、権威、社会的承認、倫理綱領、専門職文化の5つの属性を示した。
    2  公衆の福祉という目的、理論と技術、教育と訓練、テストによる能力証明、専門職団体の組織化、倫理綱領の6つの属性を示した。
    3  専門職の目標、知識、及び技術についての認識を示した。
    4  専門職の成熟度として、4つの発達段階を示した。
    5  他の専門職と比較することによって「準専門職」という概念を確立した。

問題110  認定社会福祉士に関する次の記述のうち、正しいものを2つ選びなさい。
    1  地域や外部機関との対応窓口、他職種との連携よりも、所属機関の機能に応じた社会福祉専門職としての高度な支援を行うことが求められる。
    2  地域共生社会の実現に向けて求められるより高度な知識や技術等は、認定社会福祉士制度などを通して、継続して学ぶことが望まれる。
    3  スーパービジョンの実施にあたっては、スーパーバイザーとスーパーバイジ―の両者が、社会福祉士の倫理綱領及び行動規範を遵守しなければならないと定められている。
    4  認定社会福祉士を取得するには、社会福祉士として20年以上の相談援助実務経験があることが要件とされている。
    5  社会の変化とニーズの多様化・複雑化に対応するため、10年に一度の更新が求められる。

問題111  福祉職の任用または委嘱に関する次の記述のうち、正しいものを1つ選びなさい。
    1  社会福祉主事は、社会福祉法に規定されている。
    2  児童福祉司は、「児童虐待防止法」に規定されている。
    3  身体障害者福祉司は、障害者基本法に規定されている。
    4  知的障害者福祉司は、「障害者総合支援法」に規定されている。
    5  母子・父子自立支援員は、児童福祉法に規定されている。

    （注）1  「児童虐待防止法」とは、「児童虐待の防止等に関する法律」のことである。
    2  「障害者総合支援法」とは、「障害者の日常生活及び社会生活を総合的に支援するための法律」のことである。

問題112  「バークレイ報告」の内容として、最も適切なものを1つ選びなさい。
    1  年齢やカテゴリー別の援助ではなく、家族全体を視野に入れた、総合的なアセスメントに基づく家族ソーシャルワークの実施を強調した。
    2  地方自治体の議会にソーシャルサービス委員会を設置することが必要であると指摘した。
    3  ソーシャルワーカーの任務として、それぞれが責任を持つ地理的範囲やクライエントのためのネットワークを見いだすとともに、必要があれば作り出すことに関心を持たなければならないとされた。
    4  地域ケア計画を作成するにあたり、ケースマネジメントの技能を応用し、明確な財源システムを目指すことが期待された。
    5  福祉サービスと保健医療改革を一体的に法定化し、継ぎ目のないサービスの提供を目標とした。

    （注）  「バークレイ報告」とは、1982年の「Social Workers：Their Role and Tasks」のことである。

問題113  事例を読んで、Ａ市社会福祉協議会がソーシャルワーク実践の対象としたシステムとして、最も適切なものを1つ選びなさい。
〔事  例〕
Ａ市社会福祉協議会では、市内の視覚障害者から、行政機関が発信する生活や災害に関する情報が十分に届いていないため困っているという相談が相次いだ。こうした中、Ａ市社会福祉協議会は行政機関と視覚障害者をつなぐ情報伝達経路が不十分であり、その改善が必要であることをＡ市に要望した。それを受け、Ａ市は視覚障害者への情報提供支援として、点字や音声による情報提供や広報を開始し、情報が広く行き届くようになった。
    1  ミクロシステムのみ
    2  メゾシステムのみ
    3  マクロシステムのみ
    4  ミクロシステムとメゾシステム
    5  ミクロシステムとマクロシステム

問題114  事例を読んで、Ａ医療ソーシャルワーカー（社会福祉士）のＢさんへのアドボカシーを意図した最初の対応として、最も適切なものを1つ選びなさい。
〔事  例〕
脳卒中で4か月入院しているＢさん（83歳）は、現在は本人の意思を確認することが困難である。看取りの場を検討するにあたり、妻は可能な限り一緒に過ごしたいため、自宅退院を希望している。しかし、医師や看護師は、心臓に持病を持つ妻の自宅での介護は大変ではないかと妻に伝えた。その後、妻は、看取りの場について相談するために、医療相談室に来室した。Ａは、Ｂさんが病気で入院する前に、看取りの場についてＢさんと妻で話し合ったことがあるという話を聞いていた。
    1  妻に対して、自宅退院に向けて利用可能な介護サービスについて説明する。
    2  医師や看護師が心配する介護負担と妻の病状について、妻の考えを確認する。
    3  妻の希望は自宅退院であることを、Ａから医師と看護師に再度伝える。
    4  妻に対して、Ｂさんはどこで最期を迎えたいと言っておられましたかと尋ねる。
    5  妻に対して、看取りの場としての緩和ケア病棟の機能について説明する。

ソーシャルワークの理論と方法（専門）

問題115  バイステック（Biestek, F.）による援助関係の原則に関する次の記述のうち、適切なものを2つ選びなさい。
    1  非審判的態度の原則とは、問題・課題に対してクライエントが負う責任についてワーカーが承認・非承認を決定することである。
    2  自己決定の原則とは、クライエントが問題解決の方向などを自分で決める権利とニードをもっていることをワーカーがしっかりと認識し、クライエントの判断を促し、尊重することである。
    3  統制された情緒的関与の原則とは、クライエント自らの情緒的感情を意識化することである。
    4  意図的な感情表出の原則とは、クライエントの感情を大切にし、クライエントが特にその否定的感情も自由に表現できるよう、ワーカーが促すことである。
    5  秘密保持の原則とは、他の個人の権利が侵害される場合においてもクライエントの秘密は保持されることである。

問題116  事例を読んで、Ａ相談支援事業所のＢ相談支援専門員（社会福祉士）がＣさんや同僚とともに取り組んだ実践として、適切なものを2つ選びなさい。
〔事  例〕
Ｂは、担当するＣさん（35歳）から相談を受けた。Ｄ市に住むＣさんは難病で重度訪問介護を利用しており、自宅から外出することは難しい状態である。Ｃさんはパソコンスキルには自信があるが、在宅の重度の障害者には就労の機会がほとんどないことをＢに訴えた。Ｂは、同僚とともにＣさんと同様の重度の障害がある人達の自宅を訪問して話を聞いた。そして、Ｃさんらとともに重度障害者の就労の機会を増やしていくことについて行政に協力を呼び掛けた。
    1  パーソナライゼーション
    2  リファーラル
    3  ソーシャルアクション
    4  スクリーニング
    5  アウトリーチ

問題117  ソーシャルワーカーの面接技法に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  「明確化」によって、クライエントはワーカーから賞賛されたと理解する。
    2  「閉ざされた質問」によって、クライエントは面接における応答の自由度を逆に高める。
    3  「共感的応答」によって、クライエントはワーカーの持つ価値認識を理解する。
    4  「要約」によって、クライエントは今までの面接で自分の語った内容の整理を行う。
    5  「焦点化」によって、クライエントは面接で触れたくないテーマを回避することが可能となる。

問題118  事例を読んで、事例分析の視点から見て、クライエントのＡさんに関する事例検討会における参加者からの発言のうち、適切なものを2つ選びなさい。
〔事  例〕
地域の居宅介護支援事業所がケアマネジャーを対象とした定例の事例検討会を開催した。事例提供者のＢ居宅介護支援事業所のＣケアマネジャーから、一人暮らしのＡさん（85歳）の事例が報告された。ＣケアマネジャーはＡさん宅を訪問した際、近隣住民から「Ａさんは約2か月前からゴミ収集のない日にごみ出しをしている」「自分の部屋がわからなくなりマンションの管理人が何度も付き添って帰宅している」という話を聞いていることを参加者に報告し、今後の支援について参加者に意見を求めた。
    1  「Ａさんについて近隣住民が困っていることをヒアリングしてはどうでしょうか」
    2  「Ｃケアマネジャーは、Ａさんの強みや状態をどのように捉えていますか」
    3  「まずは、マンションの管理人にＡさんの今後についての考えを聞いてみてはいかがでしょうか」
    4  「一人暮らしの継続は難しいので、グループホームの利用を促してはどうでしょうか」
    5  「Ａさん自身は、今の状況についてどのようにお考えなのでしょうか」

問題119  事例を読んで、Ａ社会福祉士が事例検討を行う際に配慮すべきこととして、最も適切なものを1つ選びなさい。
〔事  例〕
Ｂ市高齢福祉課のＡは、ある日後輩のＣ相談員（社会福祉士）から「最近複雑な生活課題を持っているクライエントへの対応に苦慮しているので、事例検討の場を設けてほしい」と依頼を受けた。
    1  クライエントも含めて参加者を組織する。
    2  参加者は、Ｃと同じ経験年数の者で構成する。
    3  時間にとらわれずに、結論が出るまで検討する。
    4  Ｃが事例報告をする際には、資料を活用せず口頭で行う。
    5  Ｃが他の参加者からのコメントに防衛的にならないようにする。

問題120  事例を読んで、Ａ町社会福祉協議会のＢ職員（社会福祉士）の総合的かつ包括的支援に基づく次の記述のうち、最初の対応として、最も適切なものを1つ選びなさい。
〔事  例〕
    Ａ町では、大規模な工業団地が開発された結果、海外から来た労働者とその家族が増加傾向にある。街中を歩く外国人家族の姿が日常的となった。そのような中、民生委員から、Ｂに「慣れない文化に戸惑う外国籍家族の存在が顕著であることや、また一方で、在留外国人との交流を望んでいるものの、どのようにすればよいか困惑している地域住民の声が多く聞かれる」と情報提供があった。
    1  教育委員会に外国籍の子どもの生活状況の改善策を講じるよう要望する。
    2  在留外国人も加え、学校、自治会等がこの問題を共有化するための懇談の場を企画する。
    3  外国の文化や習慣について解説した日本人向けパンフレットを作成し、地域住民に配布する。
    4  企業の人事担当者に状況を説明し、問題解決を依頼する。
    5  外国籍住民と地域住民の交流の場を設け、広く参加を求める。

問題121  事例を読んで、Ａ市福祉なんでも相談窓口担当のＢ職員（社会福祉士）がこの時点で行う対応として、適切なものを2つ選びなさい。
〔事  例〕
Ｃさん（39歳）は3年前夫と離婚し、当時2歳の長男を連れて、それまで一人暮らしをしていた母親（73歳）と同居を始めた。同居開始時、生活全般を母親が支えてくれていたため、Ｃさんは仕事に専念でき、長男と過ごす時間も確保できていた。しかし数か月前から、母親の物忘れが目立つようになり、会話も成り立たなくなってきたため、家事等も全てＣさんが担うようになった。Ｃさんは心身ともに疲弊し、Ａ市福祉なんでも相談窓口を訪ねた。Ｃさんは窓口担当のＢとの面接において、これまでの経緯を話した後、このまま3人で暮らしていきたいと言った。
    1  Ｃさんの母親に、サービス付き高齢者向け住宅の情報を提供する。
    2  Ｃさんの不安や焦燥感を軽減するため、ピアサポートの会を紹介する。
    3  長男への虐待につながる恐れがあるため、近くの児童相談所に通告する。
    4  Ｃさん家族の対応を検討するため、子育て支援課や地域包括支援センターと連携する。
    5  長男の発達を優先し、育児に専念するよう勧める。

問題122  事例を読んで、Ａ市社会福祉協議会のＢ職員（社会福祉士）の会議における発言として、適切なものを2つ選びなさい。
〔事  例〕
Ｂは自治会役員Ｃさんから「新型感染症のためここ数年中止していた地域フェスタを再開したい。私としては、子どもをはじめ、高齢者や障害のある人も参加できるようにしたいと考えている。近々、他の自治会役員や関係者も含めて、実行委員会立ち上げのための会議を開催し、その会でご意見をいただきたい」と依頼を受けた。
    1  「Ｃさんを今回の企画・運営のリーダーに指名したいと思います」
    2  「社会福祉協議会主催で企画するので、自治会は協力してください」
    3  「地域フェスタについて、まずみなさんのお考えをお聞かせください」
    4  「今後のスケジュールと協力団体への依頼について、一緒に検討させてください」
    5  「子どもがいる家庭を手分けして全戸訪問してください」

問題123  事例を読んで、Ａがん拠点病院相談支援センターに勤務するＢ医療ソーシャルワーカー（社会福祉士）のこの時点での対応として、適切なものを2つ選びなさい。
〔事  例〕
大腸がんの治療後、定期受診中だったＣさん（44歳、男性）はＢのもとを訪れ「先日の受診で異常が指摘され、詳しい検査をしました。本日、がんの再発と転移が判明し、主治医から積極的な治療をするか、あるいは、緩和ケアに切り替えるかという2つの選択があることを伝えられました。今までなんとか乗り越えてきましたがもう限界です。家族になんて話したら良いか」と語った。
    1  今後の生活については、家族でよく話し合うことを勧める。
    2  Ｂの過去の経験から、この先の見通しについて説明する。
    3  カウンセリングを含め、心理的支援をすぐにでも受けることが可能であることを説明する。
    4  病状について再度説明してもらうよう、主治医への連絡が可能であることを説明する。
    5  混乱している気持ちを落ち着かせるため、帰宅を促す。

福祉サービスの組織と経営

問題124  事例を読んで、Ａ特定非営利活動法人がこれから取り組むべきこととして、最も適切なものを1つ選びなさい。
〔事  例〕
Ａ特定非営利活動法人は、Ｂ県Ｃ市において障害福祉事業を実施してきた。地域のニーズにさらに応えることができるよう規模を拡大し、組織を発展させていくため、関係者と協議してＡ特定非営利活動法人を解散し、社会福祉法人の設立を目指すこととなった。これまでのとおりＣ市に主たる事務所を置き、Ｃ市内でのみ事業を行っていく予定である。なお、Ｃ市は指定都市ではない。
    1  社会福祉法人の重要事項の議決機関となる評議員会を設置する。
    2  社会福祉法人の会員を募り、10名以上の会員名簿を作成する。
    3  Ａ特定非営利活動法人の解散を、所轄庁であるＣ市に届け出る。
    4  Ａ特定非営利活動法人の残余財産を、これまでの寄付者個人に分配する。
    5  社会福祉法人の設立のため、所轄庁であるＢ県からの認可を受ける。

問題125  次の記述のうち、2016年（平成28年）の社会福祉法改正により、新たに社会福祉法人が努めなければならないとされたこととして、正しいものを1つ選びなさい。
    1  福祉サービスの利用者の利益を保護する仕組みを導入すること。
    2  地域における公益的な取組を実施すること。
    3  従業員の給与基準を定めて公表すること。
    4  第一種社会福祉事業を実施すること。
    5  第三者評価を受審すること。

問題126  リーダーシップに関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  リーダーシップの行動理論は、リーダーになる人とならない人の差について、人の身体的特徴や性格の特性との関連で明らかにした。
    2  フォロワーシップの理論は、チームメンバーがリーダーに対して異議申し立てなどをせずに全面的に従うことの重要性を示した。
    3  リーダーシップのコンティンジェンシー理論は、どのような状況においても普遍的なリーダーシップ行動をとることの有効性を示した。
    4  サーバント・リーダーシップの考え方は、リーダーのもとにメンバーを従わせることにより、効果的に組織をコントロールすることの重要性を示した。
    5  シェアド・リーダーシップの考え方は、各メンバーが持つ情報・資源・スキルなどを必要な場面で効果的に用いて、一人一人がリーダーシップを発揮することの重要性を示した。

問題127  事例を読んで、Ａさんが苦情を申し立てることのできる仕組みとして、最も適切なものを1つ選びなさい。
〔事  例〕
Ｂ障害者支援施設を利用しているＡさんは、日頃からＣ職員の態度が怖いと感じており、そのことについて苦情を申し立てたいと考えている。ただし、事業所の苦情受付担当者がＣ職員自身であるため、相談しづらい。なお、Ａさんは、既に施設の苦情解決にかかわる第三者委員に相談したが、一向に状況が改善していない。
    1  障害福祉サービス等情報公表制度
    2  運営適正化委員会
    3  安全委員会
    4  福祉サービス第三者評価事業の評価機関
    5  公益通報者保護制度

問題128  「個人情報保護法」に基づく、個人情報取扱事業者である福祉サービス提供組織の情報管理に関する次の記述のうち、最も適切なものを1つ選びなさい。
    1  福祉サービスの利用者名簿を作成し活用している団体のうち、ボランティア団体や任意団体は、個人情報取扱事業者から除外されている。
    2  個人情報取扱事業者は、包括的な同意があれば、取得した個人情報の利用目的を事業者の都合のよいように自由に変更することができる。
    3  利用者本人の信条に関する情報は、支援のために必要があれば、本人の同意を得ずとも、取得し地域の関係機関と共有できる。
    4  要配慮個人情報とは、要配慮者の要介護認定や障害支援区分認定に関する情報を指し、犯罪の経歴は含まないとされている。
    5  個人データを第三者提供する際の本人からの同意は、人の生命・身体・財産の保護に必要で本人からの同意取得が困難な場合は、例外的に不要である。

    （注）  「個人情報保護法」とは、「個人情報の保護に関する法律」のことである。

問題129  社会福祉法人の財務に関する次の記述のうち、適切なものを2つ選びなさい。
    1  事業活動計算書は、流動資産と流動負債のバランスを見て財務の健全性をチェックすることができる計算書類である。
    2  社会福祉事業のほか、公益事業・収益事業を行う社会福祉法人は、法人全体とともに、事業区分ごとに計算書類を作成する必要がある。
    3  資金収支計算書とは、毎年資産額を一定のルールで減額させ、その年のコストとして計上して作成した計算書類である。
    4  介護サービスの提供に要した費用は、利用者に代わって国から指定介護サービス事業者に支払われる。
    5  貸借対照表は、法人全体や事業区分、拠点区分の会計年度末における財務状況を明らかにする計算書類である。

## 解答一覧

